{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='dialogflowCXFlow', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of DialogflowCXFlow', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'dialogflowcx.cnrm.cloud.google.com/v1alpha1',
    kind: 'DialogflowCXFlow',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#eventHandlers':: d.obj(help="\"A flow's event handlers serve two purposes:\\nThey are responsible for handling events (e.g. no match, webhook errors) in the flow.\\nThey are inherited by every page's [event handlers][Page.event_handlers], which can be used to handle common events regardless of the current page. Event handlers defined in the page have higher priority than those defined in the flow.\\nUnlike transitionRoutes, these handlers are evaluated on a first-match basis. The first one that matches the event get executed, with the rest being ignored.\""),
    eventHandlers: {
      '#triggerFulfillment':: d.obj(help='"The fulfillment to call when the event occurs. Handling webhook errors with a fulfillment enabled with webhook could cause infinite loop. It is invalid to specify such fulfillment for a handler handling webhooks."'),
      triggerFulfillment: {
        '#conditionalCases':: d.obj(help='"Conditional cases for this fulfillment."'),
        conditionalCases: {
          '#withCases':: d.fn(help='"A JSON encoded list of cascading if-else conditions. Cases are mutually exclusive. The first one with a matching condition is selected, all the rest ignored.\\nSee [Case](https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3/Fulfillment#case) for the schema."', args=[d.arg(name='cases', type=d.T.string)]),
          withCases(cases): { cases: cases },
        },
        '#messages':: d.obj(help='"The list of rich message responses to present to the user."'),
        messages: {
          '#conversationSuccess':: d.obj(help="\"Indicates that the conversation succeeded, i.e., the bot handled the issue that the customer talked to it about.\\nDialogflow only uses this to determine which conversations should be counted as successful and doesn't process the metadata in this message in any way. Note that Dialogflow also considers conversations that get to the conversation end page as successful even if they don't return ConversationSuccess.\\nYou may set this, for example:\\n* In the entryFulfillment of a Page if entering the page indicates that the conversation succeeded.\\n* In a webhook response when you determine that you handled the customer issue.\""),
          conversationSuccess: {
            '#withMetadata':: d.fn(help="\"Custom metadata. Dialogflow doesn't impose any structure on this.\"", args=[d.arg(name='metadata', type=d.T.string)]),
            withMetadata(metadata): { conversationSuccess+: { metadata: metadata } },
          },
          '#liveAgentHandoff':: d.obj(help='"Indicates that the conversation should be handed off to a live agent.\\nDialogflow only uses this to determine which conversations were handed off to a human agent for measurement purposes. What else to do with this signal is up to you and your handoff procedures.\\nYou may set this, for example:\\n* In the entryFulfillment of a Page if entering the page indicates something went extremely wrong in the conversation.\\n* In a webhook response when you determine that the customer issue can only be handled by a human."'),
          liveAgentHandoff: {
            '#withMetadata':: d.fn(help="\"Custom metadata. Dialogflow doesn't impose any structure on this.\"", args=[d.arg(name='metadata', type=d.T.string)]),
            withMetadata(metadata): { liveAgentHandoff+: { metadata: metadata } },
          },
          '#outputAudioText':: d.obj(help='"A text or ssml response that is preferentially used for TTS output audio synthesis, as described in the comment on the ResponseMessage message."'),
          outputAudioText: {
            '#withAllowPlaybackInterruption':: d.fn(help="\"Whether the playback of this message can be interrupted by the end user's speech and the client can then starts the next Dialogflow request.\"", args=[d.arg(name='allowPlaybackInterruption', type=d.T.boolean)]),
            withAllowPlaybackInterruption(allowPlaybackInterruption): { outputAudioText+: { allowPlaybackInterruption: allowPlaybackInterruption } },
            '#withSsml':: d.fn(help='"The SSML text to be synthesized. For more information, see SSML."', args=[d.arg(name='ssml', type=d.T.string)]),
            withSsml(ssml): { outputAudioText+: { ssml: ssml } },
            '#withText':: d.fn(help='"The raw text to be synthesized."', args=[d.arg(name='text', type=d.T.string)]),
            withText(text): { outputAudioText+: { text: text } },
          },
          '#playAudio':: d.obj(help='"Specifies an audio clip to be played by the client as part of the response."'),
          playAudio: {
            '#withAllowPlaybackInterruption':: d.fn(help="\"Whether the playback of this message can be interrupted by the end user's speech and the client can then starts the next Dialogflow request.\"", args=[d.arg(name='allowPlaybackInterruption', type=d.T.boolean)]),
            withAllowPlaybackInterruption(allowPlaybackInterruption): { playAudio+: { allowPlaybackInterruption: allowPlaybackInterruption } },
            '#withAudioUri':: d.fn(help='"URI of the audio clip. Dialogflow does not impose any validation on this value. It is specific to the client that reads it."', args=[d.arg(name='audioUri', type=d.T.string)]),
            withAudioUri(audioUri): { playAudio+: { audioUri: audioUri } },
          },
          '#telephonyTransferCall':: d.obj(help='"Represents the signal that telles the client to transfer the phone call connected to the agent to a third-party endpoint."'),
          telephonyTransferCall: {
            '#withPhoneNumber':: d.fn(help='"Transfer the call to a phone number in E.164 format."', args=[d.arg(name='phoneNumber', type=d.T.string)]),
            withPhoneNumber(phoneNumber): { telephonyTransferCall+: { phoneNumber: phoneNumber } },
          },
          '#text':: d.obj(help='"The text response message."'),
          text: {
            '#withAllowPlaybackInterruption':: d.fn(help="\"Whether the playback of this message can be interrupted by the end user's speech and the client can then starts the next Dialogflow request.\"", args=[d.arg(name='allowPlaybackInterruption', type=d.T.boolean)]),
            withAllowPlaybackInterruption(allowPlaybackInterruption): { text+: { allowPlaybackInterruption: allowPlaybackInterruption } },
            '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
            withText(text): { text+: { text: if std.isArray(v=text) then text else [text] } },
            '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
            withTextMixin(text): { text+: { text+: if std.isArray(v=text) then text else [text] } },
          },
          '#withChannel':: d.fn(help='"The channel which the response is associated with. Clients can specify the channel via QueryParameters.channel, and only associated channel response will be returned."', args=[d.arg(name='channel', type=d.T.string)]),
          withChannel(channel): { channel: channel },
          '#withPayload':: d.fn(help='"A custom, platform-specific payload."', args=[d.arg(name='payload', type=d.T.string)]),
          withPayload(payload): { payload: payload },
        },
        '#setParameterActions':: d.obj(help='"Set parameter values before executing the webhook."'),
        setParameterActions: {
          '#withParameter':: d.fn(help='"Display name of the parameter."', args=[d.arg(name='parameter', type=d.T.string)]),
          withParameter(parameter): { parameter: parameter },
          '#withValue':: d.fn(help='"The new JSON-encoded value of the parameter. A null value clears the parameter."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#withConditionalCases':: d.fn(help='"Conditional cases for this fulfillment."', args=[d.arg(name='conditionalCases', type=d.T.array)]),
        withConditionalCases(conditionalCases): { triggerFulfillment+: { conditionalCases: if std.isArray(v=conditionalCases) then conditionalCases else [conditionalCases] } },
        '#withConditionalCasesMixin':: d.fn(help='"Conditional cases for this fulfillment."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='conditionalCases', type=d.T.array)]),
        withConditionalCasesMixin(conditionalCases): { triggerFulfillment+: { conditionalCases+: if std.isArray(v=conditionalCases) then conditionalCases else [conditionalCases] } },
        '#withMessages':: d.fn(help='"The list of rich message responses to present to the user."', args=[d.arg(name='messages', type=d.T.array)]),
        withMessages(messages): { triggerFulfillment+: { messages: if std.isArray(v=messages) then messages else [messages] } },
        '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
        withMessagesMixin(messages): { triggerFulfillment+: { messages+: if std.isArray(v=messages) then messages else [messages] } },
        '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
        withReturnPartialResponses(returnPartialResponses): { triggerFulfillment+: { returnPartialResponses: returnPartialResponses } },
        '#withSetParameterActions':: d.fn(help='"Set parameter values before executing the webhook."', args=[d.arg(name='setParameterActions', type=d.T.array)]),
        withSetParameterActions(setParameterActions): { triggerFulfillment+: { setParameterActions: if std.isArray(v=setParameterActions) then setParameterActions else [setParameterActions] } },
        '#withSetParameterActionsMixin':: d.fn(help='"Set parameter values before executing the webhook."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='setParameterActions', type=d.T.array)]),
        withSetParameterActionsMixin(setParameterActions): { triggerFulfillment+: { setParameterActions+: if std.isArray(v=setParameterActions) then setParameterActions else [setParameterActions] } },
        '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
        withTag(tag): { triggerFulfillment+: { tag: tag } },
        '#withWebhook':: d.fn(help='"The webhook to call. Format: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/webhooks/<Webhook ID>."', args=[d.arg(name='webhook', type=d.T.string)]),
        withWebhook(webhook): { triggerFulfillment+: { webhook: webhook } },
      },
      '#withEvent':: d.fn(help='"The name of the event to handle."', args=[d.arg(name='event', type=d.T.string)]),
      withEvent(event): { event: event },
      '#withName':: d.fn(help='"The unique identifier of this event handler."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withTargetFlow':: d.fn(help='"The target flow to transition to.\\nFormat: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>."', args=[d.arg(name='targetFlow', type=d.T.string)]),
      withTargetFlow(targetFlow): { targetFlow: targetFlow },
      '#withTargetPage':: d.fn(help='"The target page to transition to.\\nFormat: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>/pages/<Page ID>."', args=[d.arg(name='targetPage', type=d.T.string)]),
      withTargetPage(targetPage): { targetPage: targetPage },
    },
    '#nluSettings':: d.obj(help='"NLU related settings of the flow."'),
    nluSettings: {
      '#withClassificationThreshold':: d.fn(help='"To filter out false positive results and still get variety in matched natural language inputs for your agent, you can tune the machine learning classification threshold.\\nIf the returned score value is less than the threshold value, then a no-match event will be triggered. The score values range from 0.0 (completely uncertain) to 1.0 (completely certain). If set to 0.0, the default of 0.3 is used."', args=[d.arg(name='classificationThreshold', type=d.T.number)]),
      withClassificationThreshold(classificationThreshold): { spec+: { nluSettings+: { classificationThreshold: classificationThreshold } } },
      '#withModelTrainingMode':: d.fn(help='"Indicates NLU model training mode.\\n* MODEL_TRAINING_MODE_AUTOMATIC: NLU model training is automatically triggered when a flow gets modified. User can also manually trigger model training in this mode.\\n* MODEL_TRAINING_MODE_MANUAL: User needs to manually trigger NLU model training. Best for large flows whose models take long time to train. Possible values: [\\"MODEL_TRAINING_MODE_AUTOMATIC\\", \\"MODEL_TRAINING_MODE_MANUAL\\"]."', args=[d.arg(name='modelTrainingMode', type=d.T.string)]),
      withModelTrainingMode(modelTrainingMode): { spec+: { nluSettings+: { modelTrainingMode: modelTrainingMode } } },
      '#withModelType':: d.fn(help='"Indicates the type of NLU model.\\n* MODEL_TYPE_STANDARD: Use standard NLU model.\\n* MODEL_TYPE_ADVANCED: Use advanced NLU model. Possible values: [\\"MODEL_TYPE_STANDARD\\", \\"MODEL_TYPE_ADVANCED\\"]."', args=[d.arg(name='modelType', type=d.T.string)]),
      withModelType(modelType): { spec+: { nluSettings+: { modelType: modelType } } },
    },
    '#transitionRoutes':: d.obj(help="\"A flow's transition routes serve two purposes:\\nThey are responsible for matching the user's first utterances in the flow.\\nThey are inherited by every page's [transition routes][Page.transition_routes] and can support use cases such as the user saying \\\"help\\\" or \\\"can I talk to a human?\\\", which can be handled in a common way regardless of the current page. Transition routes defined in the page have higher priority than those defined in the flow.\\n\\nTransitionRoutes are evalauted in the following order:\\n  TransitionRoutes with intent specified.\\n  TransitionRoutes with only condition specified.\\n  TransitionRoutes with intent specified are inherited by pages in the flow.\""),
    transitionRoutes: {
      '#triggerFulfillment':: d.obj(help='"The fulfillment to call when the condition is satisfied. At least one of triggerFulfillment and target must be specified. When both are defined, triggerFulfillment is executed first."'),
      triggerFulfillment: {
        '#conditionalCases':: d.obj(help='"Conditional cases for this fulfillment."'),
        conditionalCases: {
          '#withCases':: d.fn(help='"A JSON encoded list of cascading if-else conditions. Cases are mutually exclusive. The first one with a matching condition is selected, all the rest ignored.\\nSee [Case](https://cloud.google.com/dialogflow/cx/docs/reference/rest/v3/Fulfillment#case) for the schema."', args=[d.arg(name='cases', type=d.T.string)]),
          withCases(cases): { cases: cases },
        },
        '#messages':: d.obj(help='"The list of rich message responses to present to the user."'),
        messages: {
          '#conversationSuccess':: d.obj(help="\"Indicates that the conversation succeeded, i.e., the bot handled the issue that the customer talked to it about.\\nDialogflow only uses this to determine which conversations should be counted as successful and doesn't process the metadata in this message in any way. Note that Dialogflow also considers conversations that get to the conversation end page as successful even if they don't return ConversationSuccess.\\nYou may set this, for example:\\n* In the entryFulfillment of a Page if entering the page indicates that the conversation succeeded.\\n* In a webhook response when you determine that you handled the customer issue.\""),
          conversationSuccess: {
            '#withMetadata':: d.fn(help="\"Custom metadata. Dialogflow doesn't impose any structure on this.\"", args=[d.arg(name='metadata', type=d.T.string)]),
            withMetadata(metadata): { conversationSuccess+: { metadata: metadata } },
          },
          '#liveAgentHandoff':: d.obj(help='"Indicates that the conversation should be handed off to a live agent.\\nDialogflow only uses this to determine which conversations were handed off to a human agent for measurement purposes. What else to do with this signal is up to you and your handoff procedures.\\nYou may set this, for example:\\n* In the entryFulfillment of a Page if entering the page indicates something went extremely wrong in the conversation.\\n* In a webhook response when you determine that the customer issue can only be handled by a human."'),
          liveAgentHandoff: {
            '#withMetadata':: d.fn(help="\"Custom metadata. Dialogflow doesn't impose any structure on this.\"", args=[d.arg(name='metadata', type=d.T.string)]),
            withMetadata(metadata): { liveAgentHandoff+: { metadata: metadata } },
          },
          '#outputAudioText':: d.obj(help='"A text or ssml response that is preferentially used for TTS output audio synthesis, as described in the comment on the ResponseMessage message."'),
          outputAudioText: {
            '#withAllowPlaybackInterruption':: d.fn(help="\"Whether the playback of this message can be interrupted by the end user's speech and the client can then starts the next Dialogflow request.\"", args=[d.arg(name='allowPlaybackInterruption', type=d.T.boolean)]),
            withAllowPlaybackInterruption(allowPlaybackInterruption): { outputAudioText+: { allowPlaybackInterruption: allowPlaybackInterruption } },
            '#withSsml':: d.fn(help='"The SSML text to be synthesized. For more information, see SSML."', args=[d.arg(name='ssml', type=d.T.string)]),
            withSsml(ssml): { outputAudioText+: { ssml: ssml } },
            '#withText':: d.fn(help='"The raw text to be synthesized."', args=[d.arg(name='text', type=d.T.string)]),
            withText(text): { outputAudioText+: { text: text } },
          },
          '#playAudio':: d.obj(help='"Specifies an audio clip to be played by the client as part of the response."'),
          playAudio: {
            '#withAllowPlaybackInterruption':: d.fn(help="\"Whether the playback of this message can be interrupted by the end user's speech and the client can then starts the next Dialogflow request.\"", args=[d.arg(name='allowPlaybackInterruption', type=d.T.boolean)]),
            withAllowPlaybackInterruption(allowPlaybackInterruption): { playAudio+: { allowPlaybackInterruption: allowPlaybackInterruption } },
            '#withAudioUri':: d.fn(help='"URI of the audio clip. Dialogflow does not impose any validation on this value. It is specific to the client that reads it."', args=[d.arg(name='audioUri', type=d.T.string)]),
            withAudioUri(audioUri): { playAudio+: { audioUri: audioUri } },
          },
          '#telephonyTransferCall':: d.obj(help='"Represents the signal that telles the client to transfer the phone call connected to the agent to a third-party endpoint."'),
          telephonyTransferCall: {
            '#withPhoneNumber':: d.fn(help='"Transfer the call to a phone number in E.164 format."', args=[d.arg(name='phoneNumber', type=d.T.string)]),
            withPhoneNumber(phoneNumber): { telephonyTransferCall+: { phoneNumber: phoneNumber } },
          },
          '#text':: d.obj(help='"The text response message."'),
          text: {
            '#withAllowPlaybackInterruption':: d.fn(help="\"Whether the playback of this message can be interrupted by the end user's speech and the client can then starts the next Dialogflow request.\"", args=[d.arg(name='allowPlaybackInterruption', type=d.T.boolean)]),
            withAllowPlaybackInterruption(allowPlaybackInterruption): { text+: { allowPlaybackInterruption: allowPlaybackInterruption } },
            '#withText':: d.fn(help='"A collection of text responses."', args=[d.arg(name='text', type=d.T.array)]),
            withText(text): { text+: { text: if std.isArray(v=text) then text else [text] } },
            '#withTextMixin':: d.fn(help='"A collection of text responses."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='text', type=d.T.array)]),
            withTextMixin(text): { text+: { text+: if std.isArray(v=text) then text else [text] } },
          },
          '#withChannel':: d.fn(help='"The channel which the response is associated with. Clients can specify the channel via QueryParameters.channel, and only associated channel response will be returned."', args=[d.arg(name='channel', type=d.T.string)]),
          withChannel(channel): { channel: channel },
          '#withPayload':: d.fn(help='"A custom, platform-specific payload."', args=[d.arg(name='payload', type=d.T.string)]),
          withPayload(payload): { payload: payload },
        },
        '#setParameterActions':: d.obj(help='"Set parameter values before executing the webhook."'),
        setParameterActions: {
          '#withParameter':: d.fn(help='"Display name of the parameter."', args=[d.arg(name='parameter', type=d.T.string)]),
          withParameter(parameter): { parameter: parameter },
          '#withValue':: d.fn(help='"The new JSON-encoded value of the parameter. A null value clears the parameter."', args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { value: value },
        },
        '#withConditionalCases':: d.fn(help='"Conditional cases for this fulfillment."', args=[d.arg(name='conditionalCases', type=d.T.array)]),
        withConditionalCases(conditionalCases): { triggerFulfillment+: { conditionalCases: if std.isArray(v=conditionalCases) then conditionalCases else [conditionalCases] } },
        '#withConditionalCasesMixin':: d.fn(help='"Conditional cases for this fulfillment."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='conditionalCases', type=d.T.array)]),
        withConditionalCasesMixin(conditionalCases): { triggerFulfillment+: { conditionalCases+: if std.isArray(v=conditionalCases) then conditionalCases else [conditionalCases] } },
        '#withMessages':: d.fn(help='"The list of rich message responses to present to the user."', args=[d.arg(name='messages', type=d.T.array)]),
        withMessages(messages): { triggerFulfillment+: { messages: if std.isArray(v=messages) then messages else [messages] } },
        '#withMessagesMixin':: d.fn(help='"The list of rich message responses to present to the user."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='messages', type=d.T.array)]),
        withMessagesMixin(messages): { triggerFulfillment+: { messages+: if std.isArray(v=messages) then messages else [messages] } },
        '#withReturnPartialResponses':: d.fn(help='"Whether Dialogflow should return currently queued fulfillment response messages in streaming APIs. If a webhook is specified, it happens before Dialogflow invokes webhook. Warning: 1) This flag only affects streaming API. Responses are still queued and returned once in non-streaming API. 2) The flag can be enabled in any fulfillment but only the first 3 partial responses will be returned. You may only want to apply it to fulfillments that have slow webhooks."', args=[d.arg(name='returnPartialResponses', type=d.T.boolean)]),
        withReturnPartialResponses(returnPartialResponses): { triggerFulfillment+: { returnPartialResponses: returnPartialResponses } },
        '#withSetParameterActions':: d.fn(help='"Set parameter values before executing the webhook."', args=[d.arg(name='setParameterActions', type=d.T.array)]),
        withSetParameterActions(setParameterActions): { triggerFulfillment+: { setParameterActions: if std.isArray(v=setParameterActions) then setParameterActions else [setParameterActions] } },
        '#withSetParameterActionsMixin':: d.fn(help='"Set parameter values before executing the webhook."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='setParameterActions', type=d.T.array)]),
        withSetParameterActionsMixin(setParameterActions): { triggerFulfillment+: { setParameterActions+: if std.isArray(v=setParameterActions) then setParameterActions else [setParameterActions] } },
        '#withTag':: d.fn(help='"The tag used by the webhook to identify which fulfillment is being called. This field is required if webhook is specified."', args=[d.arg(name='tag', type=d.T.string)]),
        withTag(tag): { triggerFulfillment+: { tag: tag } },
        '#withWebhook':: d.fn(help='"The webhook to call. Format: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/webhooks/<Webhook ID>."', args=[d.arg(name='webhook', type=d.T.string)]),
        withWebhook(webhook): { triggerFulfillment+: { webhook: webhook } },
      },
      '#withCondition':: d.fn(help='"The condition to evaluate against form parameters or session parameters.\\nAt least one of intent or condition must be specified. When both intent and condition are specified, the transition can only happen when both are fulfilled."', args=[d.arg(name='condition', type=d.T.string)]),
      withCondition(condition): { condition: condition },
      '#withIntent':: d.fn(help='"The unique identifier of an Intent.\\nFormat: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/intents/<Intent ID>. Indicates that the transition can only happen when the given intent is matched. At least one of intent or condition must be specified. When both intent and condition are specified, the transition can only happen when both are fulfilled."', args=[d.arg(name='intent', type=d.T.string)]),
      withIntent(intent): { intent: intent },
      '#withName':: d.fn(help='"The unique identifier of this transition route."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withTargetFlow':: d.fn(help='"The target flow to transition to.\\nFormat: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>."', args=[d.arg(name='targetFlow', type=d.T.string)]),
      withTargetFlow(targetFlow): { targetFlow: targetFlow },
      '#withTargetPage':: d.fn(help='"The target page to transition to.\\nFormat: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>/flows/<Flow ID>/pages/<Page ID>."', args=[d.arg(name='targetPage', type=d.T.string)]),
      withTargetPage(targetPage): { targetPage: targetPage },
    },
    '#withDescription':: d.fn(help='"The description of the flow. The maximum length is 500 characters. If exceeded, the request is rejected."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withDisplayName':: d.fn(help='"The human-readable name of the flow."', args=[d.arg(name='displayName', type=d.T.string)]),
    withDisplayName(displayName): { spec+: { displayName: displayName } },
    '#withEventHandlers':: d.fn(help="\"A flow's event handlers serve two purposes:\\nThey are responsible for handling events (e.g. no match, webhook errors) in the flow.\\nThey are inherited by every page's [event handlers][Page.event_handlers], which can be used to handle common events regardless of the current page. Event handlers defined in the page have higher priority than those defined in the flow.\\nUnlike transitionRoutes, these handlers are evaluated on a first-match basis. The first one that matches the event get executed, with the rest being ignored.\"", args=[d.arg(name='eventHandlers', type=d.T.array)]),
    withEventHandlers(eventHandlers): { spec+: { eventHandlers: if std.isArray(v=eventHandlers) then eventHandlers else [eventHandlers] } },
    '#withEventHandlersMixin':: d.fn(help="\"A flow's event handlers serve two purposes:\\nThey are responsible for handling events (e.g. no match, webhook errors) in the flow.\\nThey are inherited by every page's [event handlers][Page.event_handlers], which can be used to handle common events regardless of the current page. Event handlers defined in the page have higher priority than those defined in the flow.\\nUnlike transitionRoutes, these handlers are evaluated on a first-match basis. The first one that matches the event get executed, with the rest being ignored.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='eventHandlers', type=d.T.array)]),
    withEventHandlersMixin(eventHandlers): { spec+: { eventHandlers+: if std.isArray(v=eventHandlers) then eventHandlers else [eventHandlers] } },
    '#withLanguageCode':: d.fn(help="\"Immutable. The language of the following fields in flow:\\nFlow.event_handlers.trigger_fulfillment.messages\\nFlow.event_handlers.trigger_fulfillment.conditional_cases\\nFlow.transition_routes.trigger_fulfillment.messages\\nFlow.transition_routes.trigger_fulfillment.conditional_cases\\nIf not specified, the agent's default language is used. Many languages are supported. Note: languages must be enabled in the agent before they can be used.\"", args=[d.arg(name='languageCode', type=d.T.string)]),
    withLanguageCode(languageCode): { spec+: { languageCode: languageCode } },
    '#withParent':: d.fn(help='"Immutable. The agent to create a flow for.\\nFormat: projects/<Project ID>/locations/<Location ID>/agents/<Agent ID>."', args=[d.arg(name='parent', type=d.T.string)]),
    withParent(parent): { spec+: { parent: parent } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The service-generated name of the resource. Used for acquisition only. Leave unset to create a new resource."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withTransitionRouteGroups':: d.fn(help="\"A flow's transition route group serve two purposes:\\nThey are responsible for matching the user's first utterances in the flow.\\nThey are inherited by every page's [transition route groups][Page.transition_route_groups]. Transition route groups defined in the page have higher priority than those defined in the flow.\\nFormat:projects/\u003cProject ID\u003e/locations/\u003cLocation ID\u003e/agents/\u003cAgent ID\u003e/flows/\u003cFlow ID\u003e/transitionRouteGroups/\u003cTransitionRouteGroup ID\u003e.\"", args=[d.arg(name='transitionRouteGroups', type=d.T.array)]),
    withTransitionRouteGroups(transitionRouteGroups): { spec+: { transitionRouteGroups: if std.isArray(v=transitionRouteGroups) then transitionRouteGroups else [transitionRouteGroups] } },
    '#withTransitionRouteGroupsMixin':: d.fn(help="\"A flow's transition route group serve two purposes:\\nThey are responsible for matching the user's first utterances in the flow.\\nThey are inherited by every page's [transition route groups][Page.transition_route_groups]. Transition route groups defined in the page have higher priority than those defined in the flow.\\nFormat:projects/\u003cProject ID\u003e/locations/\u003cLocation ID\u003e/agents/\u003cAgent ID\u003e/flows/\u003cFlow ID\u003e/transitionRouteGroups/\u003cTransitionRouteGroup ID\u003e.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='transitionRouteGroups', type=d.T.array)]),
    withTransitionRouteGroupsMixin(transitionRouteGroups): { spec+: { transitionRouteGroups+: if std.isArray(v=transitionRouteGroups) then transitionRouteGroups else [transitionRouteGroups] } },
    '#withTransitionRoutes':: d.fn(help="\"A flow's transition routes serve two purposes:\\nThey are responsible for matching the user's first utterances in the flow.\\nThey are inherited by every page's [transition routes][Page.transition_routes] and can support use cases such as the user saying \\\"help\\\" or \\\"can I talk to a human?\\\", which can be handled in a common way regardless of the current page. Transition routes defined in the page have higher priority than those defined in the flow.\\n\\nTransitionRoutes are evalauted in the following order:\\n  TransitionRoutes with intent specified.\\n  TransitionRoutes with only condition specified.\\n  TransitionRoutes with intent specified are inherited by pages in the flow.\"", args=[d.arg(name='transitionRoutes', type=d.T.array)]),
    withTransitionRoutes(transitionRoutes): { spec+: { transitionRoutes: if std.isArray(v=transitionRoutes) then transitionRoutes else [transitionRoutes] } },
    '#withTransitionRoutesMixin':: d.fn(help="\"A flow's transition routes serve two purposes:\\nThey are responsible for matching the user's first utterances in the flow.\\nThey are inherited by every page's [transition routes][Page.transition_routes] and can support use cases such as the user saying \\\"help\\\" or \\\"can I talk to a human?\\\", which can be handled in a common way regardless of the current page. Transition routes defined in the page have higher priority than those defined in the flow.\\n\\nTransitionRoutes are evalauted in the following order:\\n  TransitionRoutes with intent specified.\\n  TransitionRoutes with only condition specified.\\n  TransitionRoutes with intent specified are inherited by pages in the flow.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='transitionRoutes', type=d.T.array)]),
    withTransitionRoutesMixin(transitionRoutes): { spec+: { transitionRoutes+: if std.isArray(v=transitionRoutes) then transitionRoutes else [transitionRoutes] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
