{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='apiKeysKey', url='', help='"APIKeysKey is the Schema for the APIKeys Key resource."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of APIKeysKey', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'apikeys.cnrm.cloud.google.com/v1alpha1',
    kind: 'APIKeysKey',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#projectRef':: d.obj(help='"Immutable. The Project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"The `projectID` field of a project, when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withKind':: d.fn(help='"The kind of the Project resource; optional but must be `Project` if provided."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { projectRef+: { kind: kind } } },
      '#withName':: d.fn(help='"The `name` field of a `Project` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `Project` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#restrictions':: d.obj(help='"Key restrictions."'),
    restrictions: {
      '#androidKeyRestrictions':: d.obj(help='"The Android apps that are allowed to use the key."'),
      androidKeyRestrictions: {
        '#allowedApplications':: d.obj(help='"A list of Android applications that are allowed to make API calls with this key."'),
        allowedApplications: {
          '#withPackageName':: d.fn(help='"The package name of the application."', args=[d.arg(name='packageName', type=d.T.string)]),
          withPackageName(packageName): { packageName: packageName },
          '#withSha1Fingerprint':: d.fn(help='"The SHA1 fingerprint of the application. For example, both sha1 formats are acceptable : DA:39:A3:EE:5E:6B:4B:0D:32:55:BF:EF:95:60:18:90:AF:D8:07:09 or DA39A3EE5E6B4B0D3255BFEF95601890AFD80709. Output format is the latter."', args=[d.arg(name='sha1Fingerprint', type=d.T.string)]),
          withSha1Fingerprint(sha1Fingerprint): { sha1Fingerprint: sha1Fingerprint },
        },
        '#withAllowedApplications':: d.fn(help='"A list of Android applications that are allowed to make API calls with this key."', args=[d.arg(name='allowedApplications', type=d.T.array)]),
        withAllowedApplications(allowedApplications): { spec+: { restrictions+: { androidKeyRestrictions+: { allowedApplications: if std.isArray(v=allowedApplications) then allowedApplications else [allowedApplications] } } } },
        '#withAllowedApplicationsMixin':: d.fn(help='"A list of Android applications that are allowed to make API calls with this key."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedApplications', type=d.T.array)]),
        withAllowedApplicationsMixin(allowedApplications): { spec+: { restrictions+: { androidKeyRestrictions+: { allowedApplications+: if std.isArray(v=allowedApplications) then allowedApplications else [allowedApplications] } } } },
      },
      '#apiTargets':: d.obj(help='"A restriction for a specific service and optionally one or more specific methods. Requests are allowed if they match any of these restrictions. If no restrictions are specified, all targets are allowed."'),
      apiTargets: {
        '#withMethods':: d.fn(help='"Optional. List of one or more methods that can be called. If empty, all methods for the service are allowed. A wildcard (*) can be used as the last symbol. Valid examples: `google.cloud.translate.v2.TranslateService.GetSupportedLanguage` `TranslateText` `Get*` `translate.googleapis.com.Get*`"', args=[d.arg(name='methods', type=d.T.array)]),
        withMethods(methods): { methods: if std.isArray(v=methods) then methods else [methods] },
        '#withMethodsMixin':: d.fn(help='"Optional. List of one or more methods that can be called. If empty, all methods for the service are allowed. A wildcard (*) can be used as the last symbol. Valid examples: `google.cloud.translate.v2.TranslateService.GetSupportedLanguage` `TranslateText` `Get*` `translate.googleapis.com.Get*`"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='methods', type=d.T.array)]),
        withMethodsMixin(methods): { methods+: if std.isArray(v=methods) then methods else [methods] },
        '#withService':: d.fn(help='"The service for this restriction. It should be the canonical service name, for example: `translate.googleapis.com`. You can use [`gcloud services list`](/sdk/gcloud/reference/services/list) to get a list of services that are enabled in the project."', args=[d.arg(name='service', type=d.T.string)]),
        withService(service): { service: service },
      },
      '#browserKeyRestrictions':: d.obj(help='"The HTTP referrers (websites) that are allowed to use the key."'),
      browserKeyRestrictions: {
        '#withAllowedReferrers':: d.fn(help='"A list of regular expressions for the referrer URLs that are allowed to make API calls with this key."', args=[d.arg(name='allowedReferrers', type=d.T.array)]),
        withAllowedReferrers(allowedReferrers): { spec+: { restrictions+: { browserKeyRestrictions+: { allowedReferrers: if std.isArray(v=allowedReferrers) then allowedReferrers else [allowedReferrers] } } } },
        '#withAllowedReferrersMixin':: d.fn(help='"A list of regular expressions for the referrer URLs that are allowed to make API calls with this key."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedReferrers', type=d.T.array)]),
        withAllowedReferrersMixin(allowedReferrers): { spec+: { restrictions+: { browserKeyRestrictions+: { allowedReferrers+: if std.isArray(v=allowedReferrers) then allowedReferrers else [allowedReferrers] } } } },
      },
      '#iosKeyRestrictions':: d.obj(help='"The iOS apps that are allowed to use the key."'),
      iosKeyRestrictions: {
        '#withAllowedBundleIds':: d.fn(help='"A list of bundle IDs that are allowed when making API calls with this key."', args=[d.arg(name='allowedBundleIds', type=d.T.array)]),
        withAllowedBundleIds(allowedBundleIds): { spec+: { restrictions+: { iosKeyRestrictions+: { allowedBundleIds: if std.isArray(v=allowedBundleIds) then allowedBundleIds else [allowedBundleIds] } } } },
        '#withAllowedBundleIdsMixin':: d.fn(help='"A list of bundle IDs that are allowed when making API calls with this key."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedBundleIds', type=d.T.array)]),
        withAllowedBundleIdsMixin(allowedBundleIds): { spec+: { restrictions+: { iosKeyRestrictions+: { allowedBundleIds+: if std.isArray(v=allowedBundleIds) then allowedBundleIds else [allowedBundleIds] } } } },
      },
      '#serverKeyRestrictions':: d.obj(help='"The IP addresses of callers that are allowed to use the key."'),
      serverKeyRestrictions: {
        '#withAllowedIps':: d.fn(help='"A list of the caller IP addresses that are allowed to make API calls with this key."', args=[d.arg(name='allowedIps', type=d.T.array)]),
        withAllowedIps(allowedIps): { spec+: { restrictions+: { serverKeyRestrictions+: { allowedIps: if std.isArray(v=allowedIps) then allowedIps else [allowedIps] } } } },
        '#withAllowedIpsMixin':: d.fn(help='"A list of the caller IP addresses that are allowed to make API calls with this key."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedIps', type=d.T.array)]),
        withAllowedIpsMixin(allowedIps): { spec+: { restrictions+: { serverKeyRestrictions+: { allowedIps+: if std.isArray(v=allowedIps) then allowedIps else [allowedIps] } } } },
      },
      '#withApiTargets':: d.fn(help='"A restriction for a specific service and optionally one or more specific methods. Requests are allowed if they match any of these restrictions. If no restrictions are specified, all targets are allowed."', args=[d.arg(name='apiTargets', type=d.T.array)]),
      withApiTargets(apiTargets): { spec+: { restrictions+: { apiTargets: if std.isArray(v=apiTargets) then apiTargets else [apiTargets] } } },
      '#withApiTargetsMixin':: d.fn(help='"A restriction for a specific service and optionally one or more specific methods. Requests are allowed if they match any of these restrictions. If no restrictions are specified, all targets are allowed."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='apiTargets', type=d.T.array)]),
      withApiTargetsMixin(apiTargets): { spec+: { restrictions+: { apiTargets+: if std.isArray(v=apiTargets) then apiTargets else [apiTargets] } } },
    },
    '#withDisplayName':: d.fn(help='"Human-readable display name of this key that you can modify. The maximum length is 63 characters."', args=[d.arg(name='displayName', type=d.T.string)]),
    withDisplayName(displayName): { spec+: { displayName: displayName } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
