{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='computeRegionAutoscaler', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of ComputeRegionAutoscaler', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'compute.cnrm.cloud.google.com/v1alpha1',
    kind: 'ComputeRegionAutoscaler',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#autoscalingPolicy':: d.obj(help='"The configuration parameters for the autoscaling algorithm. You can\\ndefine one or more of the policies for an autoscaler: cpuUtilization,\\ncustomMetricUtilizations, and loadBalancingUtilization.\\n\\nIf none of these are specified, the default will be to autoscale based\\non cpuUtilization to 0.6 or 60%."'),
    autoscalingPolicy: {
      '#cpuUtilization':: d.obj(help='"Defines the CPU utilization policy that allows the autoscaler to\\nscale based on the average CPU utilization of a managed instance\\ngroup."'),
      cpuUtilization: {
        '#withPredictiveMethod':: d.fn(help='"Indicates whether predictive autoscaling based on CPU metric is enabled. Valid values are:\\n\\n- NONE (default). No predictive method is used. The autoscaler scales the group to meet current demand based on real-time metrics.\\n\\n- OPTIMIZE_AVAILABILITY. Predictive autoscaling improves availability by monitoring daily and weekly load patterns and scaling out ahead of anticipated demand."', args=[d.arg(name='predictiveMethod', type=d.T.string)]),
        withPredictiveMethod(predictiveMethod): { spec+: { autoscalingPolicy+: { cpuUtilization+: { predictiveMethod: predictiveMethod } } } },
        '#withTarget':: d.fn(help='"The target CPU utilization that the autoscaler should maintain.\\nMust be a float value in the range (0, 1]. If not specified, the\\ndefault is 0.6.\\n\\nIf the CPU level is below the target utilization, the autoscaler\\nscales down the number of instances until it reaches the minimum\\nnumber of instances you specified or until the average CPU of\\nyour instances reaches the target utilization.\\n\\nIf the average CPU is above the target utilization, the autoscaler\\nscales up until it reaches the maximum number of instances you\\nspecified or until the average utilization reaches the target\\nutilization."', args=[d.arg(name='target', type=d.T.number)]),
        withTarget(target): { spec+: { autoscalingPolicy+: { cpuUtilization+: { target: target } } } },
      },
      '#loadBalancingUtilization':: d.obj(help='"Configuration parameters of autoscaling based on a load balancer."'),
      loadBalancingUtilization: {
        '#withTarget':: d.fn(help='"Fraction of backend capacity utilization (set in HTTP(s) load\\nbalancing configuration) that autoscaler should maintain. Must\\nbe a positive float value. If not defined, the default is 0.8."', args=[d.arg(name='target', type=d.T.number)]),
        withTarget(target): { spec+: { autoscalingPolicy+: { loadBalancingUtilization+: { target: target } } } },
      },
      '#metric':: d.obj(help='"Configuration parameters of autoscaling based on a custom metric."'),
      metric: {
        '#withFilter':: d.fn(help='"A filter string to be used as the filter string for\\na Stackdriver Monitoring TimeSeries.list API call.\\nThis filter is used to select a specific TimeSeries for\\nthe purpose of autoscaling and to determine whether the metric\\nis exporting per-instance or per-group data.\\n\\nYou can only use the AND operator for joining selectors.\\nYou can only use direct equality comparison operator (=) without\\nany functions for each selector.\\nYou can specify the metric in both the filter string and in the\\nmetric field. However, if specified in both places, the metric must\\nbe identical.\\n\\nThe monitored resource type determines what kind of values are\\nexpected for the metric. If it is a gce_instance, the autoscaler\\nexpects the metric to include a separate TimeSeries for each\\ninstance in a group. In such a case, you cannot filter on resource\\nlabels.\\n\\nIf the resource type is any other value, the autoscaler expects\\nthis metric to contain values that apply to the entire autoscaled\\ninstance group and resource label filtering can be performed to\\npoint autoscaler at the correct TimeSeries to scale upon.\\nThis is called a per-group metric for the purpose of autoscaling.\\n\\nIf not specified, the type defaults to gce_instance.\\n\\nYou should provide a filter that is selective enough to pick just\\none TimeSeries for the autoscaled group or for each of the instances\\n(if you are using gce_instance resource type). If multiple\\nTimeSeries are returned upon the query execution, the autoscaler\\nwill sum their respective values to obtain its scaling value."', args=[d.arg(name='filter', type=d.T.string)]),
        withFilter(filter): { filter: filter },
        '#withName':: d.fn(help='"The identifier (type) of the Stackdriver Monitoring metric.\\nThe metric cannot have negative values.\\n\\nThe metric must have a value type of INT64 or DOUBLE."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withSingleInstanceAssignment':: d.fn(help="\"If scaling is based on a per-group metric value that represents the\\ntotal amount of work to be done or resource usage, set this value to\\nan amount assigned for a single instance of the scaled group.\\nThe autoscaler will keep the number of instances proportional to the\\nvalue of this metric, the metric itself should not change value due\\nto group resizing.\\n\\nFor example, a good metric to use with the target is\\n'pubsub.googleapis.com/subscription/num_undelivered_messages'\\nor a custom metric exporting the total number of requests coming to\\nyour instances.\\n\\nA bad example would be a metric exporting an average or median\\nlatency, since this value can't include a chunk assignable to a\\nsingle instance, it could be better used with utilization_target\\ninstead.\"", args=[d.arg(name='singleInstanceAssignment', type=d.T.number)]),
        withSingleInstanceAssignment(singleInstanceAssignment): { singleInstanceAssignment: singleInstanceAssignment },
        '#withTarget':: d.fn(help='"The target value of the metric that autoscaler should\\nmaintain. This must be a positive value. A utilization\\nmetric scales number of virtual machines handling requests\\nto increase or decrease proportionally to the metric.\\n\\nFor example, a good metric to use as a utilizationTarget is\\nwww.googleapis.com/compute/instance/network/received_bytes_count.\\nThe autoscaler will work to keep this value constant for each\\nof the instances."', args=[d.arg(name='target', type=d.T.number)]),
        withTarget(target): { target: target },
        '#withType':: d.fn(help='"Defines how target utilization value is expressed for a\\nStackdriver Monitoring metric. Possible values: [\\"GAUGE\\", \\"DELTA_PER_SECOND\\", \\"DELTA_PER_MINUTE\\"]."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { type: type },
      },
      '#scaleDownControl':: d.obj(help='"Defines scale down controls to reduce the risk of response latency\\nand outages due to abrupt scale-in events."'),
      scaleDownControl: {
        '#maxScaledDownReplicas':: d.obj(help='"A nested object resource."'),
        maxScaledDownReplicas: {
          '#withFixed':: d.fn(help='"Specifies a fixed number of VM instances. This must be a positive\\ninteger."', args=[d.arg(name='fixed', type=d.T.integer)]),
          withFixed(fixed): { spec+: { autoscalingPolicy+: { scaleDownControl+: { maxScaledDownReplicas+: { fixed: fixed } } } } },
          '#withPercent':: d.fn(help='"Specifies a percentage of instances between 0 to 100%, inclusive.\\nFor example, specify 80 for 80%."', args=[d.arg(name='percent', type=d.T.integer)]),
          withPercent(percent): { spec+: { autoscalingPolicy+: { scaleDownControl+: { maxScaledDownReplicas+: { percent: percent } } } } },
        },
        '#withTimeWindowSec':: d.fn(help='"How long back autoscaling should look when computing recommendations\\nto include directives regarding slower scale down, as described above."', args=[d.arg(name='timeWindowSec', type=d.T.integer)]),
        withTimeWindowSec(timeWindowSec): { spec+: { autoscalingPolicy+: { scaleDownControl+: { timeWindowSec: timeWindowSec } } } },
      },
      '#scaleInControl':: d.obj(help='"Defines scale in controls to reduce the risk of response latency\\nand outages due to abrupt scale-in events."'),
      scaleInControl: {
        '#maxScaledInReplicas':: d.obj(help='"A nested object resource."'),
        maxScaledInReplicas: {
          '#withFixed':: d.fn(help='"Specifies a fixed number of VM instances. This must be a positive\\ninteger."', args=[d.arg(name='fixed', type=d.T.integer)]),
          withFixed(fixed): { spec+: { autoscalingPolicy+: { scaleInControl+: { maxScaledInReplicas+: { fixed: fixed } } } } },
          '#withPercent':: d.fn(help='"Specifies a percentage of instances between 0 to 100%, inclusive.\\nFor example, specify 80 for 80%."', args=[d.arg(name='percent', type=d.T.integer)]),
          withPercent(percent): { spec+: { autoscalingPolicy+: { scaleInControl+: { maxScaledInReplicas+: { percent: percent } } } } },
        },
        '#withTimeWindowSec':: d.fn(help='"How long back autoscaling should look when computing recommendations\\nto include directives regarding slower scale down, as described above."', args=[d.arg(name='timeWindowSec', type=d.T.integer)]),
        withTimeWindowSec(timeWindowSec): { spec+: { autoscalingPolicy+: { scaleInControl+: { timeWindowSec: timeWindowSec } } } },
      },
      '#scalingSchedules':: d.obj(help='"Scaling schedules defined for an autoscaler. Multiple schedules can be set on an autoscaler and they can overlap."'),
      scalingSchedules: {
        '#withDescription':: d.fn(help='"A description of a scaling schedule."', args=[d.arg(name='description', type=d.T.string)]),
        withDescription(description): { description: description },
        '#withDisabled':: d.fn(help='"A boolean value that specifies if a scaling schedule can influence autoscaler recommendations. If set to true, then a scaling schedule has no effect."', args=[d.arg(name='disabled', type=d.T.boolean)]),
        withDisabled(disabled): { disabled: disabled },
        '#withDurationSec':: d.fn(help='"The duration of time intervals (in seconds) for which this scaling schedule will be running. The minimum allowed value is 300."', args=[d.arg(name='durationSec', type=d.T.integer)]),
        withDurationSec(durationSec): { durationSec: durationSec },
        '#withMinRequiredReplicas':: d.fn(help='"Minimum number of VM instances that autoscaler will recommend in time intervals starting according to schedule."', args=[d.arg(name='minRequiredReplicas', type=d.T.integer)]),
        withMinRequiredReplicas(minRequiredReplicas): { minRequiredReplicas: minRequiredReplicas },
        '#withName':: d.fn(help='', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withSchedule':: d.fn(help='"The start timestamps of time intervals when this scaling schedule should provide a scaling signal. This field uses the extended cron format (with an optional year field)."', args=[d.arg(name='schedule', type=d.T.string)]),
        withSchedule(schedule): { schedule: schedule },
        '#withTimeZone':: d.fn(help='"The time zone to be used when interpreting the schedule. The value of this field must be a time zone name from the tz database: http://en.wikipedia.org/wiki/Tz_database."', args=[d.arg(name='timeZone', type=d.T.string)]),
        withTimeZone(timeZone): { timeZone: timeZone },
      },
      '#withCooldownPeriod':: d.fn(help='"The number of seconds that the autoscaler should wait before it\\nstarts collecting information from a new instance. This prevents\\nthe autoscaler from collecting information when the instance is\\ninitializing, during which the collected usage would not be\\nreliable. The default time autoscaler waits is 60 seconds.\\n\\nVirtual machine initialization times might vary because of\\nnumerous factors. We recommend that you test how long an\\ninstance may take to initialize. To do this, create an instance\\nand time the startup process."', args=[d.arg(name='cooldownPeriod', type=d.T.integer)]),
      withCooldownPeriod(cooldownPeriod): { spec+: { autoscalingPolicy+: { cooldownPeriod: cooldownPeriod } } },
      '#withMaxReplicas':: d.fn(help='"The maximum number of instances that the autoscaler can scale up\\nto. This is required when creating or updating an autoscaler. The\\nmaximum number of replicas should not be lower than minimal number\\nof replicas."', args=[d.arg(name='maxReplicas', type=d.T.integer)]),
      withMaxReplicas(maxReplicas): { spec+: { autoscalingPolicy+: { maxReplicas: maxReplicas } } },
      '#withMetric':: d.fn(help='"Configuration parameters of autoscaling based on a custom metric."', args=[d.arg(name='metric', type=d.T.array)]),
      withMetric(metric): { spec+: { autoscalingPolicy+: { metric: if std.isArray(v=metric) then metric else [metric] } } },
      '#withMetricMixin':: d.fn(help='"Configuration parameters of autoscaling based on a custom metric."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metric', type=d.T.array)]),
      withMetricMixin(metric): { spec+: { autoscalingPolicy+: { metric+: if std.isArray(v=metric) then metric else [metric] } } },
      '#withMinReplicas':: d.fn(help='"The minimum number of replicas that the autoscaler can scale down\\nto. This cannot be less than 0. If not provided, autoscaler will\\nchoose a default value depending on maximum number of instances\\nallowed."', args=[d.arg(name='minReplicas', type=d.T.integer)]),
      withMinReplicas(minReplicas): { spec+: { autoscalingPolicy+: { minReplicas: minReplicas } } },
      '#withMode':: d.fn(help='"Defines operating mode for this policy."', args=[d.arg(name='mode', type=d.T.string)]),
      withMode(mode): { spec+: { autoscalingPolicy+: { mode: mode } } },
      '#withScalingSchedules':: d.fn(help='"Scaling schedules defined for an autoscaler. Multiple schedules can be set on an autoscaler and they can overlap."', args=[d.arg(name='scalingSchedules', type=d.T.array)]),
      withScalingSchedules(scalingSchedules): { spec+: { autoscalingPolicy+: { scalingSchedules: if std.isArray(v=scalingSchedules) then scalingSchedules else [scalingSchedules] } } },
      '#withScalingSchedulesMixin':: d.fn(help='"Scaling schedules defined for an autoscaler. Multiple schedules can be set on an autoscaler and they can overlap."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scalingSchedules', type=d.T.array)]),
      withScalingSchedulesMixin(scalingSchedules): { spec+: { autoscalingPolicy+: { scalingSchedules+: if std.isArray(v=scalingSchedules) then scalingSchedules else [scalingSchedules] } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#withDescription':: d.fn(help='"An optional description of this resource."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withRegion':: d.fn(help='"Immutable. URL of the region where the instance group resides."', args=[d.arg(name='region', type=d.T.string)]),
    withRegion(region): { spec+: { region: region } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withTarget':: d.fn(help='"URL of the managed instance group that this autoscaler will scale."', args=[d.arg(name='target', type=d.T.string)]),
    withTarget(target): { spec+: { target: target } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
