{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='computeNetworkFirewallPolicyRule', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of ComputeNetworkFirewallPolicyRule', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'compute.cnrm.cloud.google.com/v1alpha1',
    kind: 'ComputeNetworkFirewallPolicyRule',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#firewallPolicyRef':: d.obj(help='"The firewall policy of the resource."'),
    firewallPolicyRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `networkFirewallPolicyId` field of a `ComputeNetworkFirewallPolicy` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { firewallPolicyRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { firewallPolicyRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { firewallPolicyRef+: { namespace: namespace } } },
    },
    '#match':: d.obj(help="\"A match condition that incoming traffic is evaluated against. If it evaluates to true, the corresponding 'action' is enforced.\""),
    match: {
      '#layer4Configs':: d.obj(help='"Pairs of IP protocols and ports that the rule should match."'),
      layer4Configs: {
        '#withIpProtocol':: d.fn(help='"The IP protocol to which this rule applies. The protocol type is required when creating a firewall rule. This value can either be one of the following well known protocol strings (`tcp`, `udp`, `icmp`, `esp`, `ah`, `ipip`, `sctp`), or the IP protocol number."', args=[d.arg(name='ipProtocol', type=d.T.string)]),
        withIpProtocol(ipProtocol): { ipProtocol: ipProtocol },
        '#withPorts':: d.fn(help='"An optional list of ports to which this rule applies. This field is only applicable for UDP or TCP protocol. Each entry must be either an integer or a range. If not specified, this rule applies to connections through any port. Example inputs include: ``."', args=[d.arg(name='ports', type=d.T.array)]),
        withPorts(ports): { ports: if std.isArray(v=ports) then ports else [ports] },
        '#withPortsMixin':: d.fn(help='"An optional list of ports to which this rule applies. This field is only applicable for UDP or TCP protocol. Each entry must be either an integer or a range. If not specified, this rule applies to connections through any port. Example inputs include: ``."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ports', type=d.T.array)]),
        withPortsMixin(ports): { ports+: if std.isArray(v=ports) then ports else [ports] },
      },
      '#srcSecureTags':: d.obj(help='"List of secure tag values, which should be matched at the source of the traffic. For INGRESS rule, if all the <code>srcSecureTag</code> are INEFFECTIVE, and there is no <code>srcIpRange</code>, this rule will be ignored. Maximum number of source tag values allowed is 256."'),
      srcSecureTags: {
        '#withName':: d.fn(help="\"Name of the secure tag, created with TagManager's TagValue API. @pattern tagValues/[0-9]+.\"", args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withState':: d.fn(help='"[Output Only] State of the secure tag, either `EFFECTIVE` or `INEFFECTIVE`. A secure tag is `INEFFECTIVE` when it is deleted or its network is deleted."', args=[d.arg(name='state', type=d.T.string)]),
        withState(state): { state: state },
      },
      '#withDestAddressGroups':: d.fn(help='"Address groups which should be matched against the traffic destination. Maximum number of destination address groups is 10. Destination address groups is only supported in Egress rules."', args=[d.arg(name='destAddressGroups', type=d.T.array)]),
      withDestAddressGroups(destAddressGroups): { spec+: { match+: { destAddressGroups: if std.isArray(v=destAddressGroups) then destAddressGroups else [destAddressGroups] } } },
      '#withDestAddressGroupsMixin':: d.fn(help='"Address groups which should be matched against the traffic destination. Maximum number of destination address groups is 10. Destination address groups is only supported in Egress rules."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='destAddressGroups', type=d.T.array)]),
      withDestAddressGroupsMixin(destAddressGroups): { spec+: { match+: { destAddressGroups+: if std.isArray(v=destAddressGroups) then destAddressGroups else [destAddressGroups] } } },
      '#withDestFqdns':: d.fn(help='"Domain names that will be used to match against the resolved domain name of destination of traffic. Can only be specified if DIRECTION is egress."', args=[d.arg(name='destFqdns', type=d.T.array)]),
      withDestFqdns(destFqdns): { spec+: { match+: { destFqdns: if std.isArray(v=destFqdns) then destFqdns else [destFqdns] } } },
      '#withDestFqdnsMixin':: d.fn(help='"Domain names that will be used to match against the resolved domain name of destination of traffic. Can only be specified if DIRECTION is egress."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='destFqdns', type=d.T.array)]),
      withDestFqdnsMixin(destFqdns): { spec+: { match+: { destFqdns+: if std.isArray(v=destFqdns) then destFqdns else [destFqdns] } } },
      '#withDestIpRanges':: d.fn(help='"CIDR IP address range. Maximum number of destination CIDR IP ranges allowed is 5000."', args=[d.arg(name='destIpRanges', type=d.T.array)]),
      withDestIpRanges(destIpRanges): { spec+: { match+: { destIpRanges: if std.isArray(v=destIpRanges) then destIpRanges else [destIpRanges] } } },
      '#withDestIpRangesMixin':: d.fn(help='"CIDR IP address range. Maximum number of destination CIDR IP ranges allowed is 5000."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='destIpRanges', type=d.T.array)]),
      withDestIpRangesMixin(destIpRanges): { spec+: { match+: { destIpRanges+: if std.isArray(v=destIpRanges) then destIpRanges else [destIpRanges] } } },
      '#withDestRegionCodes':: d.fn(help='"The Unicode country codes whose IP addresses will be used to match against the source of traffic. Can only be specified if DIRECTION is egress."', args=[d.arg(name='destRegionCodes', type=d.T.array)]),
      withDestRegionCodes(destRegionCodes): { spec+: { match+: { destRegionCodes: if std.isArray(v=destRegionCodes) then destRegionCodes else [destRegionCodes] } } },
      '#withDestRegionCodesMixin':: d.fn(help='"The Unicode country codes whose IP addresses will be used to match against the source of traffic. Can only be specified if DIRECTION is egress."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='destRegionCodes', type=d.T.array)]),
      withDestRegionCodesMixin(destRegionCodes): { spec+: { match+: { destRegionCodes+: if std.isArray(v=destRegionCodes) then destRegionCodes else [destRegionCodes] } } },
      '#withDestThreatIntelligences':: d.fn(help='"Name of the Google Cloud Threat Intelligence list."', args=[d.arg(name='destThreatIntelligences', type=d.T.array)]),
      withDestThreatIntelligences(destThreatIntelligences): { spec+: { match+: { destThreatIntelligences: if std.isArray(v=destThreatIntelligences) then destThreatIntelligences else [destThreatIntelligences] } } },
      '#withDestThreatIntelligencesMixin':: d.fn(help='"Name of the Google Cloud Threat Intelligence list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='destThreatIntelligences', type=d.T.array)]),
      withDestThreatIntelligencesMixin(destThreatIntelligences): { spec+: { match+: { destThreatIntelligences+: if std.isArray(v=destThreatIntelligences) then destThreatIntelligences else [destThreatIntelligences] } } },
      '#withLayer4Configs':: d.fn(help='"Pairs of IP protocols and ports that the rule should match."', args=[d.arg(name='layer4Configs', type=d.T.array)]),
      withLayer4Configs(layer4Configs): { spec+: { match+: { layer4Configs: if std.isArray(v=layer4Configs) then layer4Configs else [layer4Configs] } } },
      '#withLayer4ConfigsMixin':: d.fn(help='"Pairs of IP protocols and ports that the rule should match."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='layer4Configs', type=d.T.array)]),
      withLayer4ConfigsMixin(layer4Configs): { spec+: { match+: { layer4Configs+: if std.isArray(v=layer4Configs) then layer4Configs else [layer4Configs] } } },
      '#withSrcAddressGroups':: d.fn(help='"Address groups which should be matched against the traffic source. Maximum number of source address groups is 10. Source address groups is only supported in Ingress rules."', args=[d.arg(name='srcAddressGroups', type=d.T.array)]),
      withSrcAddressGroups(srcAddressGroups): { spec+: { match+: { srcAddressGroups: if std.isArray(v=srcAddressGroups) then srcAddressGroups else [srcAddressGroups] } } },
      '#withSrcAddressGroupsMixin':: d.fn(help='"Address groups which should be matched against the traffic source. Maximum number of source address groups is 10. Source address groups is only supported in Ingress rules."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='srcAddressGroups', type=d.T.array)]),
      withSrcAddressGroupsMixin(srcAddressGroups): { spec+: { match+: { srcAddressGroups+: if std.isArray(v=srcAddressGroups) then srcAddressGroups else [srcAddressGroups] } } },
      '#withSrcFqdns':: d.fn(help='"Domain names that will be used to match against the resolved domain name of source of traffic. Can only be specified if DIRECTION is ingress."', args=[d.arg(name='srcFqdns', type=d.T.array)]),
      withSrcFqdns(srcFqdns): { spec+: { match+: { srcFqdns: if std.isArray(v=srcFqdns) then srcFqdns else [srcFqdns] } } },
      '#withSrcFqdnsMixin':: d.fn(help='"Domain names that will be used to match against the resolved domain name of source of traffic. Can only be specified if DIRECTION is ingress."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='srcFqdns', type=d.T.array)]),
      withSrcFqdnsMixin(srcFqdns): { spec+: { match+: { srcFqdns+: if std.isArray(v=srcFqdns) then srcFqdns else [srcFqdns] } } },
      '#withSrcIpRanges':: d.fn(help='"CIDR IP address range. Maximum number of source CIDR IP ranges allowed is 5000."', args=[d.arg(name='srcIpRanges', type=d.T.array)]),
      withSrcIpRanges(srcIpRanges): { spec+: { match+: { srcIpRanges: if std.isArray(v=srcIpRanges) then srcIpRanges else [srcIpRanges] } } },
      '#withSrcIpRangesMixin':: d.fn(help='"CIDR IP address range. Maximum number of source CIDR IP ranges allowed is 5000."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='srcIpRanges', type=d.T.array)]),
      withSrcIpRangesMixin(srcIpRanges): { spec+: { match+: { srcIpRanges+: if std.isArray(v=srcIpRanges) then srcIpRanges else [srcIpRanges] } } },
      '#withSrcRegionCodes':: d.fn(help='"The Unicode country codes whose IP addresses will be used to match against the source of traffic. Can only be specified if DIRECTION is ingress."', args=[d.arg(name='srcRegionCodes', type=d.T.array)]),
      withSrcRegionCodes(srcRegionCodes): { spec+: { match+: { srcRegionCodes: if std.isArray(v=srcRegionCodes) then srcRegionCodes else [srcRegionCodes] } } },
      '#withSrcRegionCodesMixin':: d.fn(help='"The Unicode country codes whose IP addresses will be used to match against the source of traffic. Can only be specified if DIRECTION is ingress."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='srcRegionCodes', type=d.T.array)]),
      withSrcRegionCodesMixin(srcRegionCodes): { spec+: { match+: { srcRegionCodes+: if std.isArray(v=srcRegionCodes) then srcRegionCodes else [srcRegionCodes] } } },
      '#withSrcSecureTags':: d.fn(help='"List of secure tag values, which should be matched at the source of the traffic. For INGRESS rule, if all the <code>srcSecureTag</code> are INEFFECTIVE, and there is no <code>srcIpRange</code>, this rule will be ignored. Maximum number of source tag values allowed is 256."', args=[d.arg(name='srcSecureTags', type=d.T.array)]),
      withSrcSecureTags(srcSecureTags): { spec+: { match+: { srcSecureTags: if std.isArray(v=srcSecureTags) then srcSecureTags else [srcSecureTags] } } },
      '#withSrcSecureTagsMixin':: d.fn(help='"List of secure tag values, which should be matched at the source of the traffic. For INGRESS rule, if all the <code>srcSecureTag</code> are INEFFECTIVE, and there is no <code>srcIpRange</code>, this rule will be ignored. Maximum number of source tag values allowed is 256."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='srcSecureTags', type=d.T.array)]),
      withSrcSecureTagsMixin(srcSecureTags): { spec+: { match+: { srcSecureTags+: if std.isArray(v=srcSecureTags) then srcSecureTags else [srcSecureTags] } } },
      '#withSrcThreatIntelligences':: d.fn(help='"Name of the Google Cloud Threat Intelligence list."', args=[d.arg(name='srcThreatIntelligences', type=d.T.array)]),
      withSrcThreatIntelligences(srcThreatIntelligences): { spec+: { match+: { srcThreatIntelligences: if std.isArray(v=srcThreatIntelligences) then srcThreatIntelligences else [srcThreatIntelligences] } } },
      '#withSrcThreatIntelligencesMixin':: d.fn(help='"Name of the Google Cloud Threat Intelligence list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='srcThreatIntelligences', type=d.T.array)]),
      withSrcThreatIntelligencesMixin(srcThreatIntelligences): { spec+: { match+: { srcThreatIntelligences+: if std.isArray(v=srcThreatIntelligences) then srcThreatIntelligences else [srcThreatIntelligences] } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#targetSecureTags':: d.obj(help='"A list of secure tags that controls which instances the firewall rule applies to. If <code>targetSecureTag</code> are specified, then the firewall rule applies only to instances in the VPC network that have one of those EFFECTIVE secure tags, if all the target_secure_tag are in INEFFECTIVE state, then this rule will be ignored. <code>targetSecureTag</code> may not be set at the same time as <code>targetServiceAccounts</code>. If neither <code>targetServiceAccounts</code> nor <code>targetSecureTag</code> are specified, the firewall rule applies to all instances on the specified network. Maximum number of target label tags allowed is 256."'),
    targetSecureTags: {
      '#withName':: d.fn(help="\"Name of the secure tag, created with TagManager's TagValue API. @pattern tagValues/[0-9]+.\"", args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withState':: d.fn(help='"[Output Only] State of the secure tag, either `EFFECTIVE` or `INEFFECTIVE`. A secure tag is `INEFFECTIVE` when it is deleted or its network is deleted."', args=[d.arg(name='state', type=d.T.string)]),
      withState(state): { state: state },
    },
    '#targetServiceAccountRefs':: d.obj(help=''),
    targetServiceAccountRefs: {
      '#withExternal':: d.fn(help='"Allowed value: The `email` field of an `IAMServiceAccount` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { external: external },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { name: name },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { namespace: namespace },
    },
    '#withAction':: d.fn(help='"The Action to perform when the client connection triggers the rule. Valid actions are \\"allow\\", \\"deny\\" and \\"goto_next\\"."', args=[d.arg(name='action', type=d.T.string)]),
    withAction(action): { spec+: { action: action } },
    '#withDescription':: d.fn(help='"An optional description for this resource."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withDirection':: d.fn(help='"The direction in which this rule applies. Possible values: INGRESS, EGRESS."', args=[d.arg(name='direction', type=d.T.string)]),
    withDirection(direction): { spec+: { direction: direction } },
    '#withDisabled':: d.fn(help='"Denotes whether the firewall policy rule is disabled. When set to true, the firewall policy rule is not enforced and traffic behaves as if it did not exist. If this is unspecified, the firewall policy rule will be enabled."', args=[d.arg(name='disabled', type=d.T.boolean)]),
    withDisabled(disabled): { spec+: { disabled: disabled } },
    '#withEnableLogging':: d.fn(help='"Denotes whether to enable logging for a particular rule. If logging is enabled, logs will be exported to the configured export destination in Stackdriver. Logs may be exported to BigQuery or Pub/Sub. Note: you cannot enable logging on \\"goto_next\\" rules."', args=[d.arg(name='enableLogging', type=d.T.boolean)]),
    withEnableLogging(enableLogging): { spec+: { enableLogging: enableLogging } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The priority of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withRuleName':: d.fn(help='"An optional name for the rule. This field is not a unique identifier and can be updated."', args=[d.arg(name='ruleName', type=d.T.string)]),
    withRuleName(ruleName): { spec+: { ruleName: ruleName } },
    '#withTargetSecureTags':: d.fn(help='"A list of secure tags that controls which instances the firewall rule applies to. If <code>targetSecureTag</code> are specified, then the firewall rule applies only to instances in the VPC network that have one of those EFFECTIVE secure tags, if all the target_secure_tag are in INEFFECTIVE state, then this rule will be ignored. <code>targetSecureTag</code> may not be set at the same time as <code>targetServiceAccounts</code>. If neither <code>targetServiceAccounts</code> nor <code>targetSecureTag</code> are specified, the firewall rule applies to all instances on the specified network. Maximum number of target label tags allowed is 256."', args=[d.arg(name='targetSecureTags', type=d.T.array)]),
    withTargetSecureTags(targetSecureTags): { spec+: { targetSecureTags: if std.isArray(v=targetSecureTags) then targetSecureTags else [targetSecureTags] } },
    '#withTargetSecureTagsMixin':: d.fn(help='"A list of secure tags that controls which instances the firewall rule applies to. If <code>targetSecureTag</code> are specified, then the firewall rule applies only to instances in the VPC network that have one of those EFFECTIVE secure tags, if all the target_secure_tag are in INEFFECTIVE state, then this rule will be ignored. <code>targetSecureTag</code> may not be set at the same time as <code>targetServiceAccounts</code>. If neither <code>targetServiceAccounts</code> nor <code>targetSecureTag</code> are specified, the firewall rule applies to all instances on the specified network. Maximum number of target label tags allowed is 256."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetSecureTags', type=d.T.array)]),
    withTargetSecureTagsMixin(targetSecureTags): { spec+: { targetSecureTags+: if std.isArray(v=targetSecureTags) then targetSecureTags else [targetSecureTags] } },
    '#withTargetServiceAccountRefs':: d.fn(help='', args=[d.arg(name='targetServiceAccountRefs', type=d.T.array)]),
    withTargetServiceAccountRefs(targetServiceAccountRefs): { spec+: { targetServiceAccountRefs: if std.isArray(v=targetServiceAccountRefs) then targetServiceAccountRefs else [targetServiceAccountRefs] } },
    '#withTargetServiceAccountRefsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetServiceAccountRefs', type=d.T.array)]),
    withTargetServiceAccountRefsMixin(targetServiceAccountRefs): { spec+: { targetServiceAccountRefs+: if std.isArray(v=targetServiceAccountRefs) then targetServiceAccountRefs else [targetServiceAccountRefs] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
