{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='v1alpha1', url='', help=''),
  computeAutoscaler: (import 'computeAutoscaler.libsonnet'),
  computeBackendBucketSignedURLKey: (import 'computeBackendBucketSignedURLKey.libsonnet'),
  computeBackendServiceSignedURLKey: (import 'computeBackendServiceSignedURLKey.libsonnet'),
  computeDiskResourcePolicyAttachment: (import 'computeDiskResourcePolicyAttachment.libsonnet'),
  computeGlobalNetworkEndpoint: (import 'computeGlobalNetworkEndpoint.libsonnet'),
  computeGlobalNetworkEndpointGroup: (import 'computeGlobalNetworkEndpointGroup.libsonnet'),
  computeInstanceGroupNamedPort: (import 'computeInstanceGroupNamedPort.libsonnet'),
  computeMachineImage: (import 'computeMachineImage.libsonnet'),
  computeManagedSSLCertificate: (import 'computeManagedSSLCertificate.libsonnet'),
  computeNetworkEndpoint: (import 'computeNetworkEndpoint.libsonnet'),
  computeNetworkFirewallPolicyRule: (import 'computeNetworkFirewallPolicyRule.libsonnet'),
  computeNetworkPeeringRoutesConfig: (import 'computeNetworkPeeringRoutesConfig.libsonnet'),
  computeOrganizationSecurityPolicy: (import 'computeOrganizationSecurityPolicy.libsonnet'),
  computeOrganizationSecurityPolicyAssociation: (import 'computeOrganizationSecurityPolicyAssociation.libsonnet'),
  computeOrganizationSecurityPolicyRule: (import 'computeOrganizationSecurityPolicyRule.libsonnet'),
  computePerInstanceConfig: (import 'computePerInstanceConfig.libsonnet'),
  computeRegionAutoscaler: (import 'computeRegionAutoscaler.libsonnet'),
  computeRegionDiskResourcePolicyAttachment: (import 'computeRegionDiskResourcePolicyAttachment.libsonnet'),
  computeRegionPerInstanceConfig: (import 'computeRegionPerInstanceConfig.libsonnet'),
  computeRegionSSLPolicy: (import 'computeRegionSSLPolicy.libsonnet'),
}
