{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='gkeBackupBackupPlan', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of GKEBackupBackupPlan', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'gkebackup.cnrm.cloud.google.com/v1alpha1',
    kind: 'GKEBackupBackupPlan',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#backupConfig':: d.obj(help='"Defines the configuration of Backups created via this BackupPlan."'),
    backupConfig: {
      '#encryptionKey':: d.obj(help='"This defines a customer managed encryption key that will be used to encrypt the \\"config\\"\\nportion (the Kubernetes resources) of Backups created via this plan."'),
      encryptionKey: {
        '#withGcpKmsEncryptionKey':: d.fn(help='"Google Cloud KMS encryption key. Format: projects/*/locations/*/keyRings/*/cryptoKeys/*."', args=[d.arg(name='gcpKmsEncryptionKey', type=d.T.string)]),
        withGcpKmsEncryptionKey(gcpKmsEncryptionKey): { spec+: { backupConfig+: { encryptionKey+: { gcpKmsEncryptionKey: gcpKmsEncryptionKey } } } },
      },
      '#selectedApplications':: d.obj(help='"A list of namespaced Kubernetes Resources."'),
      selectedApplications: {
        '#namespacedNames':: d.obj(help='"A list of namespaced Kubernetes resources."'),
        namespacedNames: {
          '#withName':: d.fn(help='"The name of a Kubernetes Resource."', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { name: name },
          '#withNamespace':: d.fn(help='"The namespace of a Kubernetes Resource."', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { namespace: namespace },
        },
        '#withNamespacedNames':: d.fn(help='"A list of namespaced Kubernetes resources."', args=[d.arg(name='namespacedNames', type=d.T.array)]),
        withNamespacedNames(namespacedNames): { spec+: { backupConfig+: { selectedApplications+: { namespacedNames: if std.isArray(v=namespacedNames) then namespacedNames else [namespacedNames] } } } },
        '#withNamespacedNamesMixin':: d.fn(help='"A list of namespaced Kubernetes resources."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='namespacedNames', type=d.T.array)]),
        withNamespacedNamesMixin(namespacedNames): { spec+: { backupConfig+: { selectedApplications+: { namespacedNames+: if std.isArray(v=namespacedNames) then namespacedNames else [namespacedNames] } } } },
      },
      '#selectedNamespaces':: d.obj(help='"If set, include just the resources in the listed namespaces."'),
      selectedNamespaces: {
        '#withNamespaces':: d.fn(help='"A list of Kubernetes Namespaces."', args=[d.arg(name='namespaces', type=d.T.array)]),
        withNamespaces(namespaces): { spec+: { backupConfig+: { selectedNamespaces+: { namespaces: if std.isArray(v=namespaces) then namespaces else [namespaces] } } } },
        '#withNamespacesMixin':: d.fn(help='"A list of Kubernetes Namespaces."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='namespaces', type=d.T.array)]),
        withNamespacesMixin(namespaces): { spec+: { backupConfig+: { selectedNamespaces+: { namespaces+: if std.isArray(v=namespaces) then namespaces else [namespaces] } } } },
      },
      '#withAllNamespaces':: d.fn(help='"If True, include all namespaced resources."', args=[d.arg(name='allNamespaces', type=d.T.boolean)]),
      withAllNamespaces(allNamespaces): { spec+: { backupConfig+: { allNamespaces: allNamespaces } } },
      '#withIncludeSecrets':: d.fn(help='"This flag specifies whether Kubernetes Secret resources should be included\\nwhen they fall into the scope of Backups."', args=[d.arg(name='includeSecrets', type=d.T.boolean)]),
      withIncludeSecrets(includeSecrets): { spec+: { backupConfig+: { includeSecrets: includeSecrets } } },
      '#withIncludeVolumeData':: d.fn(help='"This flag specifies whether volume data should be backed up when PVCs are\\nincluded in the scope of a Backup."', args=[d.arg(name='includeVolumeData', type=d.T.boolean)]),
      withIncludeVolumeData(includeVolumeData): { spec+: { backupConfig+: { includeVolumeData: includeVolumeData } } },
    },
    '#backupSchedule':: d.obj(help='"Defines a schedule for automatic Backup creation via this BackupPlan."'),
    backupSchedule: {
      '#withCronSchedule':: d.fn(help='"A standard cron string that defines a repeating schedule for\\ncreating Backups via this BackupPlan.\\nIf this is defined, then backupRetainDays must also be defined."', args=[d.arg(name='cronSchedule', type=d.T.string)]),
      withCronSchedule(cronSchedule): { spec+: { backupSchedule+: { cronSchedule: cronSchedule } } },
      '#withPaused':: d.fn(help='"This flag denotes whether automatic Backup creation is paused for this BackupPlan."', args=[d.arg(name='paused', type=d.T.boolean)]),
      withPaused(paused): { spec+: { backupSchedule+: { paused: paused } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#retentionPolicy':: d.obj(help='"RetentionPolicy governs lifecycle of Backups created under this plan."'),
    retentionPolicy: {
      '#withBackupDeleteLockDays':: d.fn(help="\"Minimum age for a Backup created via this BackupPlan (in days).\\nMust be an integer value between 0-90 (inclusive).\\nA Backup created under this BackupPlan will not be deletable\\nuntil it reaches Backup's (create time + backup_delete_lock_days).\\nUpdating this field of a BackupPlan does not affect existing Backups.\\nBackups created after a successful update will inherit this new value.\"", args=[d.arg(name='backupDeleteLockDays', type=d.T.integer)]),
      withBackupDeleteLockDays(backupDeleteLockDays): { spec+: { retentionPolicy+: { backupDeleteLockDays: backupDeleteLockDays } } },
      '#withBackupRetainDays':: d.fn(help='"The default maximum age of a Backup created via this BackupPlan.\\nThis field MUST be an integer value >= 0 and <= 365. If specified,\\na Backup created under this BackupPlan will be automatically deleted\\nafter its age reaches (createTime + backupRetainDays).\\nIf not specified, Backups created under this BackupPlan will NOT be\\nsubject to automatic deletion. Updating this field does NOT affect\\nexisting Backups under it. Backups created AFTER a successful update\\nwill automatically pick up the new value.\\nNOTE: backupRetainDays must be >= backupDeleteLockDays.\\nIf cronSchedule is defined, then this must be <= 360 * the creation interval.]."', args=[d.arg(name='backupRetainDays', type=d.T.integer)]),
      withBackupRetainDays(backupRetainDays): { spec+: { retentionPolicy+: { backupRetainDays: backupRetainDays } } },
      '#withLocked':: d.fn(help='"This flag denotes whether the retention policy of this BackupPlan is locked.\\nIf set to True, no further update is allowed on this policy, including\\nthe locked field itself."', args=[d.arg(name='locked', type=d.T.boolean)]),
      withLocked(locked): { spec+: { retentionPolicy+: { locked: locked } } },
    },
    '#withCluster':: d.fn(help='"Immutable. The source cluster from which Backups will be created via this BackupPlan."', args=[d.arg(name='cluster', type=d.T.string)]),
    withCluster(cluster): { spec+: { cluster: cluster } },
    '#withDeactivated':: d.fn(help='"This flag indicates whether this BackupPlan has been deactivated.\\nSetting this field to True locks the BackupPlan such that no further updates will be allowed\\n(except deletes), including the deactivated field itself. It also prevents any new Backups\\nfrom being created via this BackupPlan (including scheduled Backups)."', args=[d.arg(name='deactivated', type=d.T.boolean)]),
    withDeactivated(deactivated): { spec+: { deactivated: deactivated } },
    '#withDescription':: d.fn(help='"User specified descriptive string for this BackupPlan."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withLocation':: d.fn(help='"Immutable. The region of the Backup Plan."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
