{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='apiGatewayAPIConfig', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of APIGatewayAPIConfig', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'apigateway.cnrm.cloud.google.com/v1alpha1',
    kind: 'APIGatewayAPIConfig',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#gatewayConfig':: d.obj(help='"Immutable. Immutable. Gateway specific configuration.\\nIf not specified, backend authentication will be set to use OIDC authentication using the default compute service account."'),
    gatewayConfig: {
      '#backendConfig':: d.obj(help='"Backend settings that are applied to all backends of the Gateway."'),
      backendConfig: {
        '#withGoogleServiceAccount':: d.fn(help='"Immutable. Google Cloud IAM service account used to sign OIDC tokens for backends that have authentication configured\\n(https://cloud.google.com/service-infrastructure/docs/service-management/reference/rest/v1/services.configs#backend)."', args=[d.arg(name='googleServiceAccount', type=d.T.string)]),
        withGoogleServiceAccount(googleServiceAccount): { spec+: { gatewayConfig+: { backendConfig+: { googleServiceAccount: googleServiceAccount } } } },
      },
    },
    '#grpcServices':: d.obj(help='"gRPC service definition files. If specified, openapiDocuments must not be included."'),
    grpcServices: {
      '#fileDescriptorSet':: d.obj(help='"Immutable. Input only. File descriptor set, generated by protoc.\\nTo generate, use protoc with imports and source info included. For an example test.proto file, the following command would put the value in a new file named out.pb.\\n\\n$ protoc --include_imports --include_source_info test.proto -o out.pb."'),
      fileDescriptorSet: {
        '#withContents':: d.fn(help='"Immutable. Base64 encoded content of the file."', args=[d.arg(name='contents', type=d.T.string)]),
        withContents(contents): { fileDescriptorSet+: { contents: contents } },
        '#withPath':: d.fn(help='"Immutable. The file path (full or relative path). This is typically the path of the file when it is uploaded."', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { fileDescriptorSet+: { path: path } },
      },
      '#source':: d.obj(help="\"Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate fileDescriptorSet.\""),
      source: {
        '#withContents':: d.fn(help='"Immutable. Base64 encoded content of the file."', args=[d.arg(name='contents', type=d.T.string)]),
        withContents(contents): { contents: contents },
        '#withPath':: d.fn(help='"Immutable. The file path (full or relative path). This is typically the path of the file when it is uploaded."', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { path: path },
      },
      '#withSource':: d.fn(help="\"Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate fileDescriptorSet.\"", args=[d.arg(name='source', type=d.T.array)]),
      withSource(source): { source: if std.isArray(v=source) then source else [source] },
      '#withSourceMixin':: d.fn(help="\"Uncompiled proto files associated with the descriptor set, used for display purposes (server-side compilation is not supported). These should match the inputs to 'protoc' command used to generate fileDescriptorSet.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='source', type=d.T.array)]),
      withSourceMixin(source): { source+: if std.isArray(v=source) then source else [source] },
    },
    '#managedServiceConfigs':: d.obj(help='"Optional. Service Configuration files. At least one must be included when using gRPC service definitions. See https://cloud.google.com/endpoints/docs/grpc/grpc-service-config#service_configuration_overview for the expected file contents.\\nIf multiple files are specified, the files are merged with the following rules: * All singular scalar fields are merged using \\"last one wins\\" semantics in the order of the files uploaded. * Repeated fields are concatenated. * Singular embedded messages are merged using these rules for nested fields."'),
    managedServiceConfigs: {
      '#withContents':: d.fn(help='"Immutable. Base64 encoded content of the file."', args=[d.arg(name='contents', type=d.T.string)]),
      withContents(contents): { contents: contents },
      '#withPath':: d.fn(help='"Immutable. The file path (full or relative path). This is typically the path of the file when it is uploaded."', args=[d.arg(name='path', type=d.T.string)]),
      withPath(path): { path: path },
    },
    '#openapiDocuments':: d.obj(help='"OpenAPI specification documents. If specified, grpcServices and managedServiceConfigs must not be included."'),
    openapiDocuments: {
      '#document':: d.obj(help='"The OpenAPI Specification document file."'),
      document: {
        '#withContents':: d.fn(help='"Immutable. Base64 encoded content of the file."', args=[d.arg(name='contents', type=d.T.string)]),
        withContents(contents): { document+: { contents: contents } },
        '#withPath':: d.fn(help='"Immutable. The file path (full or relative path). This is typically the path of the file when it is uploaded."', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { document+: { path: path } },
      },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#withApi':: d.fn(help='"Immutable. The API to attach the config to."', args=[d.arg(name='api', type=d.T.string)]),
    withApi(api): { spec+: { api: api } },
    '#withApiConfigIdPrefix':: d.fn(help='"Immutable. Creates a unique name beginning with the specified prefix. If this and api_config_id are unspecified, a random value is chosen for the name."', args=[d.arg(name='apiConfigIdPrefix', type=d.T.string)]),
    withApiConfigIdPrefix(apiConfigIdPrefix): { spec+: { apiConfigIdPrefix: apiConfigIdPrefix } },
    '#withDisplayName':: d.fn(help='"A user-visible name for the API."', args=[d.arg(name='displayName', type=d.T.string)]),
    withDisplayName(displayName): { spec+: { displayName: displayName } },
    '#withGrpcServices':: d.fn(help='"gRPC service definition files. If specified, openapiDocuments must not be included."', args=[d.arg(name='grpcServices', type=d.T.array)]),
    withGrpcServices(grpcServices): { spec+: { grpcServices: if std.isArray(v=grpcServices) then grpcServices else [grpcServices] } },
    '#withGrpcServicesMixin':: d.fn(help='"gRPC service definition files. If specified, openapiDocuments must not be included."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='grpcServices', type=d.T.array)]),
    withGrpcServicesMixin(grpcServices): { spec+: { grpcServices+: if std.isArray(v=grpcServices) then grpcServices else [grpcServices] } },
    '#withManagedServiceConfigs':: d.fn(help='"Optional. Service Configuration files. At least one must be included when using gRPC service definitions. See https://cloud.google.com/endpoints/docs/grpc/grpc-service-config#service_configuration_overview for the expected file contents.\\nIf multiple files are specified, the files are merged with the following rules: * All singular scalar fields are merged using \\"last one wins\\" semantics in the order of the files uploaded. * Repeated fields are concatenated. * Singular embedded messages are merged using these rules for nested fields."', args=[d.arg(name='managedServiceConfigs', type=d.T.array)]),
    withManagedServiceConfigs(managedServiceConfigs): { spec+: { managedServiceConfigs: if std.isArray(v=managedServiceConfigs) then managedServiceConfigs else [managedServiceConfigs] } },
    '#withManagedServiceConfigsMixin':: d.fn(help='"Optional. Service Configuration files. At least one must be included when using gRPC service definitions. See https://cloud.google.com/endpoints/docs/grpc/grpc-service-config#service_configuration_overview for the expected file contents.\\nIf multiple files are specified, the files are merged with the following rules: * All singular scalar fields are merged using \\"last one wins\\" semantics in the order of the files uploaded. * Repeated fields are concatenated. * Singular embedded messages are merged using these rules for nested fields."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='managedServiceConfigs', type=d.T.array)]),
    withManagedServiceConfigsMixin(managedServiceConfigs): { spec+: { managedServiceConfigs+: if std.isArray(v=managedServiceConfigs) then managedServiceConfigs else [managedServiceConfigs] } },
    '#withOpenapiDocuments':: d.fn(help='"OpenAPI specification documents. If specified, grpcServices and managedServiceConfigs must not be included."', args=[d.arg(name='openapiDocuments', type=d.T.array)]),
    withOpenapiDocuments(openapiDocuments): { spec+: { openapiDocuments: if std.isArray(v=openapiDocuments) then openapiDocuments else [openapiDocuments] } },
    '#withOpenapiDocumentsMixin':: d.fn(help='"OpenAPI specification documents. If specified, grpcServices and managedServiceConfigs must not be included."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='openapiDocuments', type=d.T.array)]),
    withOpenapiDocumentsMixin(openapiDocuments): { spec+: { openapiDocuments+: if std.isArray(v=openapiDocuments) then openapiDocuments else [openapiDocuments] } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The apiConfigId of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
