{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='workstationCluster', url='', help='"WorkstationCluster is the Schema for the WorkstationCluster API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of WorkstationCluster', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'workstations.cnrm.cloud.google.com/v1beta1',
    kind: 'WorkstationCluster',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"WorkstationClusterSpec defines the desired state of WorkstationCluster"'),
  spec: {
    '#annotations':: d.obj(help='"Optional. Client-specified annotations."'),
    annotations: {
      '#withKey':: d.fn(help='"Key for the annotation."', args=[d.arg(name='key', type=d.T.string)]),
      withKey(key): { key: key },
      '#withValue':: d.fn(help='"Value for the annotation."', args=[d.arg(name='value', type=d.T.string)]),
      withValue(value): { value: value },
    },
    '#labels':: d.obj(help='"Optional. [Labels](https://cloud.google.com/workstations/docs/label-resources) that are applied to the workstation cluster and that are also propagated to the underlying Compute Engine resources."'),
    labels: {
      '#withKey':: d.fn(help='"Key for the annotation."', args=[d.arg(name='key', type=d.T.string)]),
      withKey(key): { key: key },
      '#withValue':: d.fn(help='"Value for the annotation."', args=[d.arg(name='value', type=d.T.string)]),
      withValue(value): { value: value },
    },
    '#networkRef':: d.obj(help='"Immutable. Reference to the Compute Engine network in which instances associated with this workstation cluster will be created."'),
    networkRef: {
      '#withExternal':: d.fn(help='"A reference to an externally managed Compute Network resource. Should be in the format `projects/<projectID>/global/networks/<network>`."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { networkRef+: { external: external } } },
      '#withName':: d.fn(help='"The `name` field of a `ComputeNetwork` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { networkRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeNetwork` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { networkRef+: { namespace: namespace } } },
    },
    '#privateClusterConfig':: d.obj(help='"Optional. Configuration for private workstation cluster."'),
    privateClusterConfig: {
      '#allowedProjects':: d.obj(help="\"Optional. Additional projects that are allowed to attach to the workstation cluster's service attachment. By default, the workstation cluster's project and the VPC host project (if different) are allowed.\""),
      allowedProjects: {
        '#withExternal':: d.fn(help='"The `projectID` field of a project, when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { external: external },
        '#withKind':: d.fn(help='"The kind of the Project resource; optional but must be `Project` if provided."', args=[d.arg(name='kind', type=d.T.string)]),
        withKind(kind): { kind: kind },
        '#withName':: d.fn(help='"The `name` field of a `Project` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `Project` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { namespace: namespace },
      },
      '#withAllowedProjects':: d.fn(help="\"Optional. Additional projects that are allowed to attach to the workstation cluster's service attachment. By default, the workstation cluster's project and the VPC host project (if different) are allowed.\"", args=[d.arg(name='allowedProjects', type=d.T.array)]),
      withAllowedProjects(allowedProjects): { spec+: { privateClusterConfig+: { allowedProjects: if std.isArray(v=allowedProjects) then allowedProjects else [allowedProjects] } } },
      '#withAllowedProjectsMixin':: d.fn(help="\"Optional. Additional projects that are allowed to attach to the workstation cluster's service attachment. By default, the workstation cluster's project and the VPC host project (if different) are allowed.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='allowedProjects', type=d.T.array)]),
      withAllowedProjectsMixin(allowedProjects): { spec+: { privateClusterConfig+: { allowedProjects+: if std.isArray(v=allowedProjects) then allowedProjects else [allowedProjects] } } },
      '#withEnablePrivateEndpoint':: d.fn(help='"Immutable. Whether Workstations endpoint is private."', args=[d.arg(name='enablePrivateEndpoint', type=d.T.boolean)]),
      withEnablePrivateEndpoint(enablePrivateEndpoint): { spec+: { privateClusterConfig+: { enablePrivateEndpoint: enablePrivateEndpoint } } },
    },
    '#projectRef':: d.obj(help='"Immutable. The Project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"The `projectID` field of a project, when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withKind':: d.fn(help='"The kind of the Project resource; optional but must be `Project` if provided."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { projectRef+: { kind: kind } } },
      '#withName':: d.fn(help='"The `name` field of a `Project` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `Project` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#subnetworkRef':: d.obj(help='"Immutable. Reference to the Compute Engine subnetwork in which instances associated with this workstation cluster will be created. Must be part of the subnetwork specified for this workstation cluster."'),
    subnetworkRef: {
      '#withExternal':: d.fn(help='"The ComputeSubnetwork selflink of form \\"projects/{{project}}/regions/{{region}}/subnetworks/{{name}}\\", when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { subnetworkRef+: { external: external } } },
      '#withName':: d.fn(help='"The `name` field of a `ComputeSubnetwork` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { subnetworkRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeSubnetwork` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { subnetworkRef+: { namespace: namespace } } },
    },
    '#withAnnotations':: d.fn(help='"Optional. Client-specified annotations."', args=[d.arg(name='annotations', type=d.T.array)]),
    withAnnotations(annotations): { spec+: { annotations: if std.isArray(v=annotations) then annotations else [annotations] } },
    '#withAnnotationsMixin':: d.fn(help='"Optional. Client-specified annotations."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.array)]),
    withAnnotationsMixin(annotations): { spec+: { annotations+: if std.isArray(v=annotations) then annotations else [annotations] } },
    '#withDisplayName':: d.fn(help='"Optional. Human-readable name for this workstation cluster."', args=[d.arg(name='displayName', type=d.T.string)]),
    withDisplayName(displayName): { spec+: { displayName: displayName } },
    '#withLabels':: d.fn(help='"Optional. [Labels](https://cloud.google.com/workstations/docs/label-resources) that are applied to the workstation cluster and that are also propagated to the underlying Compute Engine resources."', args=[d.arg(name='labels', type=d.T.array)]),
    withLabels(labels): { spec+: { labels: if std.isArray(v=labels) then labels else [labels] } },
    '#withLabelsMixin':: d.fn(help='"Optional. [Labels](https://cloud.google.com/workstations/docs/label-resources) that are applied to the workstation cluster and that are also propagated to the underlying Compute Engine resources."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.array)]),
    withLabelsMixin(labels): { spec+: { labels+: if std.isArray(v=labels) then labels else [labels] } },
    '#withLocation':: d.fn(help='"The location of the cluster."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withResourceID':: d.fn(help='"Immutable. The WorkstationCluster name. If not given, the metadata.name will be used."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
