{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='edgeContainerCluster', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of EdgeContainerCluster', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'edgecontainer.cnrm.cloud.google.com/v1beta1',
    kind: 'EdgeContainerCluster',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#authorization':: d.obj(help='"Immutable. RBAC policy that will be applied and managed by GEC."'),
    authorization: {
      '#adminUsers':: d.obj(help='"User that will be granted the cluster-admin role on the cluster, providing\\nfull access to the cluster. Currently, this is a singular field, but will\\nbe expanded to allow multiple admins in the future."'),
      adminUsers: {
        '#usernameRef':: d.obj(help=''),
        usernameRef: {
          '#withExternal':: d.fn(help='"Allowed value: The `email` field of an `IAMServiceAccount` resource."', args=[d.arg(name='external', type=d.T.string)]),
          withExternal(external): { spec+: { authorization+: { adminUsers+: { usernameRef+: { external: external } } } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { authorization+: { adminUsers+: { usernameRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { authorization+: { adminUsers+: { usernameRef+: { namespace: namespace } } } } },
        },
      },
    },
    '#controlPlane':: d.obj(help='"The configuration of the cluster control plane."'),
    controlPlane: {
      '#local':: d.obj(help='"Immutable. Local control plane configuration."'),
      'local': {
        '#withMachineFilter':: d.fn(help='"Only machines matching this filter will be allowed to host control\\nplane nodes. The filtering language accepts strings like \\"name=<name>\\",\\nand is documented here: [AIP-160](https://google.aip.dev/160)."', args=[d.arg(name='machineFilter', type=d.T.string)]),
        withMachineFilter(machineFilter): { spec+: { controlPlane+: { 'local'+: { machineFilter: machineFilter } } } },
        '#withNodeCount':: d.fn(help='"The number of nodes to serve as replicas of the Control Plane.\\nOnly 1 and 3 are supported."', args=[d.arg(name='nodeCount', type=d.T.integer)]),
        withNodeCount(nodeCount): { spec+: { controlPlane+: { 'local'+: { nodeCount: nodeCount } } } },
        '#withNodeLocation':: d.fn(help="\"Immutable. Name of the Google Distributed Cloud Edge zones where this node pool\\nwill be created. For example: 'us-central1-edge-customer-a'.\"", args=[d.arg(name='nodeLocation', type=d.T.string)]),
        withNodeLocation(nodeLocation): { spec+: { controlPlane+: { 'local'+: { nodeLocation: nodeLocation } } } },
        '#withSharedDeploymentPolicy':: d.fn(help='"Policy configuration about how user applications are deployed. Possible values: [\\"SHARED_DEPLOYMENT_POLICY_UNSPECIFIED\\", \\"ALLOWED\\", \\"DISALLOWED\\"]."', args=[d.arg(name='sharedDeploymentPolicy', type=d.T.string)]),
        withSharedDeploymentPolicy(sharedDeploymentPolicy): { spec+: { controlPlane+: { 'local'+: { sharedDeploymentPolicy: sharedDeploymentPolicy } } } },
      },
      '#remote':: d.obj(help='"Immutable. Remote control plane configuration."'),
      remote: {
        '#withNodeLocation':: d.fn(help="\"Immutable. Name of the Google Distributed Cloud Edge zones where this node pool\\nwill be created. For example: 'us-central1-edge-customer-a'.\"", args=[d.arg(name='nodeLocation', type=d.T.string)]),
        withNodeLocation(nodeLocation): { spec+: { controlPlane+: { remote+: { nodeLocation: nodeLocation } } } },
      },
    },
    '#controlPlaneEncryption':: d.obj(help='"Remote control plane disk encryption options. This field is only used when\\nenabling CMEK support."'),
    controlPlaneEncryption: {
      '#kmsKeyRef':: d.obj(help=''),
      kmsKeyRef: {
        '#withExternal':: d.fn(help='"Allowed value: The `selfLink` field of a `KMSCryptoKey` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { controlPlaneEncryption+: { kmsKeyRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { controlPlaneEncryption+: { kmsKeyRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { controlPlaneEncryption+: { kmsKeyRef+: { namespace: namespace } } } },
      },
      '#kmsStatus':: d.obj(help="\"Error status returned by Cloud KMS when using this key. This field may be\\npopulated only if 'kms_key_state' is not 'KMS_KEY_STATE_KEY_AVAILABLE'.\\nIf populated, this field contains the error status reported by Cloud KMS.\""),
      kmsStatus: {
        '#withCode':: d.fn(help='"The status code, which should be an enum value of google.rpc.Code."', args=[d.arg(name='code', type=d.T.integer)]),
        withCode(code): { code: code },
        '#withMessage':: d.fn(help='"A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client."', args=[d.arg(name='message', type=d.T.string)]),
        withMessage(message): { message: message },
      },
      '#withKmsKeyActiveVersion':: d.fn(help='"The Cloud KMS CryptoKeyVersion currently in use for protecting control\\nplane disks. Only applicable if kms_key is set."', args=[d.arg(name='kmsKeyActiveVersion', type=d.T.string)]),
      withKmsKeyActiveVersion(kmsKeyActiveVersion): { spec+: { controlPlaneEncryption+: { kmsKeyActiveVersion: kmsKeyActiveVersion } } },
      '#withKmsKeyState':: d.fn(help="\"Availability of the Cloud KMS CryptoKey. If not 'KEY_AVAILABLE', then\\nnodes may go offline as they cannot access their local data. This can be\\ncaused by a lack of permissions to use the key, or if the key is disabled\\nor deleted.\"", args=[d.arg(name='kmsKeyState', type=d.T.string)]),
      withKmsKeyState(kmsKeyState): { spec+: { controlPlaneEncryption+: { kmsKeyState: kmsKeyState } } },
      '#withKmsStatus':: d.fn(help="\"Error status returned by Cloud KMS when using this key. This field may be\\npopulated only if 'kms_key_state' is not 'KMS_KEY_STATE_KEY_AVAILABLE'.\\nIf populated, this field contains the error status reported by Cloud KMS.\"", args=[d.arg(name='kmsStatus', type=d.T.array)]),
      withKmsStatus(kmsStatus): { spec+: { controlPlaneEncryption+: { kmsStatus: if std.isArray(v=kmsStatus) then kmsStatus else [kmsStatus] } } },
      '#withKmsStatusMixin':: d.fn(help="\"Error status returned by Cloud KMS when using this key. This field may be\\npopulated only if 'kms_key_state' is not 'KMS_KEY_STATE_KEY_AVAILABLE'.\\nIf populated, this field contains the error status reported by Cloud KMS.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='kmsStatus', type=d.T.array)]),
      withKmsStatusMixin(kmsStatus): { spec+: { controlPlaneEncryption+: { kmsStatus+: if std.isArray(v=kmsStatus) then kmsStatus else [kmsStatus] } } },
    },
    '#fleet':: d.obj(help='"Immutable. Fleet related configuration.\\nFleets are a Google Cloud concept for logically organizing clusters,\\nletting you use and manage multi-cluster capabilities and apply\\nconsistent policies across your systems."'),
    fleet: {
      '#projectRef':: d.obj(help='"The number of the Fleet host project where this cluster will be registered."'),
      projectRef: {
        '#withExternal':: d.fn(help='"Allowed value: string of the format `projects/{{value}}`, where {{value}} is the `number` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { fleet+: { projectRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { fleet+: { projectRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { fleet+: { projectRef+: { namespace: namespace } } } },
      },
      '#withMembership':: d.fn(help="\"The name of the managed Hub Membership resource associated to this cluster.\\nMembership names are formatted as\\n'projects/\u003cproject-number\u003e/locations/global/membership/\u003ccluster-id\u003e'.\"", args=[d.arg(name='membership', type=d.T.string)]),
      withMembership(membership): { spec+: { fleet+: { membership: membership } } },
    },
    '#maintenancePolicy':: d.obj(help='"Cluster-wide maintenance policy configuration."'),
    maintenancePolicy: {
      '#window':: d.obj(help='"Specifies the maintenance window in which maintenance may be performed."'),
      window: {
        '#recurringWindow':: d.obj(help='"Represents an arbitrary window of time that recurs."'),
        recurringWindow: {
          '#window':: d.obj(help='"Represents an arbitrary window of time."'),
          window: {
            '#withEndTime':: d.fn(help='"The time that the window ends. The end time must take place after the\\nstart time."', args=[d.arg(name='endTime', type=d.T.string)]),
            withEndTime(endTime): { spec+: { maintenancePolicy+: { window+: { recurringWindow+: { window+: { endTime: endTime } } } } } },
            '#withStartTime':: d.fn(help='"The time that the window first starts."', args=[d.arg(name='startTime', type=d.T.string)]),
            withStartTime(startTime): { spec+: { maintenancePolicy+: { window+: { recurringWindow+: { window+: { startTime: startTime } } } } } },
          },
          '#withRecurrence':: d.fn(help='"An RRULE (https://tools.ietf.org/html/rfc5545#section-3.8.5.3) for how\\nthis window recurs. They go on for the span of time between the start and\\nend time."', args=[d.arg(name='recurrence', type=d.T.string)]),
          withRecurrence(recurrence): { spec+: { maintenancePolicy+: { window+: { recurringWindow+: { recurrence: recurrence } } } } },
        },
      },
    },
    '#networking':: d.obj(help='"Fleet related configuration.\\nFleets are a Google Cloud concept for logically organizing clusters,\\nletting you use and manage multi-cluster capabilities and apply\\nconsistent policies across your systems."'),
    networking: {
      '#withClusterIpv4CidrBlocks':: d.fn(help='"Immutable. All pods in the cluster are assigned an RFC1918 IPv4 address from these\\nblocks. Only a single block is supported. This field cannot be changed\\nafter creation."', args=[d.arg(name='clusterIpv4CidrBlocks', type=d.T.array)]),
      withClusterIpv4CidrBlocks(clusterIpv4CidrBlocks): { spec+: { networking+: { clusterIpv4CidrBlocks: if std.isArray(v=clusterIpv4CidrBlocks) then clusterIpv4CidrBlocks else [clusterIpv4CidrBlocks] } } },
      '#withClusterIpv4CidrBlocksMixin':: d.fn(help='"Immutable. All pods in the cluster are assigned an RFC1918 IPv4 address from these\\nblocks. Only a single block is supported. This field cannot be changed\\nafter creation."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='clusterIpv4CidrBlocks', type=d.T.array)]),
      withClusterIpv4CidrBlocksMixin(clusterIpv4CidrBlocks): { spec+: { networking+: { clusterIpv4CidrBlocks+: if std.isArray(v=clusterIpv4CidrBlocks) then clusterIpv4CidrBlocks else [clusterIpv4CidrBlocks] } } },
      '#withClusterIpv6CidrBlocks':: d.fn(help='"Immutable. If specified, dual stack mode is enabled and all pods in the cluster are\\nassigned an IPv6 address from these blocks alongside from an IPv4\\naddress. Only a single block is supported. This field cannot be changed\\nafter creation."', args=[d.arg(name='clusterIpv6CidrBlocks', type=d.T.array)]),
      withClusterIpv6CidrBlocks(clusterIpv6CidrBlocks): { spec+: { networking+: { clusterIpv6CidrBlocks: if std.isArray(v=clusterIpv6CidrBlocks) then clusterIpv6CidrBlocks else [clusterIpv6CidrBlocks] } } },
      '#withClusterIpv6CidrBlocksMixin':: d.fn(help='"Immutable. If specified, dual stack mode is enabled and all pods in the cluster are\\nassigned an IPv6 address from these blocks alongside from an IPv4\\naddress. Only a single block is supported. This field cannot be changed\\nafter creation."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='clusterIpv6CidrBlocks', type=d.T.array)]),
      withClusterIpv6CidrBlocksMixin(clusterIpv6CidrBlocks): { spec+: { networking+: { clusterIpv6CidrBlocks+: if std.isArray(v=clusterIpv6CidrBlocks) then clusterIpv6CidrBlocks else [clusterIpv6CidrBlocks] } } },
      '#withNetworkType':: d.fn(help='"IP addressing type of this cluster i.e. SINGLESTACK_V4 vs DUALSTACK_V4_V6."', args=[d.arg(name='networkType', type=d.T.string)]),
      withNetworkType(networkType): { spec+: { networking+: { networkType: networkType } } },
      '#withServicesIpv4CidrBlocks':: d.fn(help='"Immutable. All services in the cluster are assigned an RFC1918 IPv4 address from these\\nblocks. Only a single block is supported. This field cannot be changed\\nafter creation."', args=[d.arg(name='servicesIpv4CidrBlocks', type=d.T.array)]),
      withServicesIpv4CidrBlocks(servicesIpv4CidrBlocks): { spec+: { networking+: { servicesIpv4CidrBlocks: if std.isArray(v=servicesIpv4CidrBlocks) then servicesIpv4CidrBlocks else [servicesIpv4CidrBlocks] } } },
      '#withServicesIpv4CidrBlocksMixin':: d.fn(help='"Immutable. All services in the cluster are assigned an RFC1918 IPv4 address from these\\nblocks. Only a single block is supported. This field cannot be changed\\nafter creation."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='servicesIpv4CidrBlocks', type=d.T.array)]),
      withServicesIpv4CidrBlocksMixin(servicesIpv4CidrBlocks): { spec+: { networking+: { servicesIpv4CidrBlocks+: if std.isArray(v=servicesIpv4CidrBlocks) then servicesIpv4CidrBlocks else [servicesIpv4CidrBlocks] } } },
      '#withServicesIpv6CidrBlocks':: d.fn(help='"Immutable. If specified, dual stack mode is enabled and all services in the cluster are\\nassigned an IPv6 address from these blocks alongside from an IPv4\\naddress. Only a single block is supported. This field cannot be changed\\nafter creation."', args=[d.arg(name='servicesIpv6CidrBlocks', type=d.T.array)]),
      withServicesIpv6CidrBlocks(servicesIpv6CidrBlocks): { spec+: { networking+: { servicesIpv6CidrBlocks: if std.isArray(v=servicesIpv6CidrBlocks) then servicesIpv6CidrBlocks else [servicesIpv6CidrBlocks] } } },
      '#withServicesIpv6CidrBlocksMixin':: d.fn(help='"Immutable. If specified, dual stack mode is enabled and all services in the cluster are\\nassigned an IPv6 address from these blocks alongside from an IPv4\\naddress. Only a single block is supported. This field cannot be changed\\nafter creation."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='servicesIpv6CidrBlocks', type=d.T.array)]),
      withServicesIpv6CidrBlocksMixin(servicesIpv6CidrBlocks): { spec+: { networking+: { servicesIpv6CidrBlocks+: if std.isArray(v=servicesIpv6CidrBlocks) then servicesIpv6CidrBlocks else [servicesIpv6CidrBlocks] } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#systemAddonsConfig':: d.obj(help='"Config that customers are allowed to define for GDCE system add-ons."'),
    systemAddonsConfig: {
      '#ingress':: d.obj(help='"Config for the Ingress add-on which allows customers to create an Ingress\\nobject to manage external access to the servers in a cluster. The add-on\\nconsists of istiod and istio-ingress."'),
      ingress: {
        '#withDisabled':: d.fn(help='"Whether Ingress is disabled."', args=[d.arg(name='disabled', type=d.T.boolean)]),
        withDisabled(disabled): { spec+: { systemAddonsConfig+: { ingress+: { disabled: disabled } } } },
        '#withIpv4Vip':: d.fn(help='"Ingress VIP."', args=[d.arg(name='ipv4Vip', type=d.T.string)]),
        withIpv4Vip(ipv4Vip): { spec+: { systemAddonsConfig+: { ingress+: { ipv4Vip: ipv4Vip } } } },
      },
    },
    '#withDefaultMaxPodsPerNode':: d.fn(help='"The default maximum number of pods per node used if a maximum value is not\\nspecified explicitly for a node pool in this cluster. If unspecified, the\\nKubernetes default value will be used."', args=[d.arg(name='defaultMaxPodsPerNode', type=d.T.integer)]),
    withDefaultMaxPodsPerNode(defaultMaxPodsPerNode): { spec+: { defaultMaxPodsPerNode: defaultMaxPodsPerNode } },
    '#withExternalLoadBalancerIpv4AddressPools':: d.fn(help='"Address pools for cluster data plane external load balancing."', args=[d.arg(name='externalLoadBalancerIpv4AddressPools', type=d.T.array)]),
    withExternalLoadBalancerIpv4AddressPools(externalLoadBalancerIpv4AddressPools): { spec+: { externalLoadBalancerIpv4AddressPools: if std.isArray(v=externalLoadBalancerIpv4AddressPools) then externalLoadBalancerIpv4AddressPools else [externalLoadBalancerIpv4AddressPools] } },
    '#withExternalLoadBalancerIpv4AddressPoolsMixin':: d.fn(help='"Address pools for cluster data plane external load balancing."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='externalLoadBalancerIpv4AddressPools', type=d.T.array)]),
    withExternalLoadBalancerIpv4AddressPoolsMixin(externalLoadBalancerIpv4AddressPools): { spec+: { externalLoadBalancerIpv4AddressPools+: if std.isArray(v=externalLoadBalancerIpv4AddressPools) then externalLoadBalancerIpv4AddressPools else [externalLoadBalancerIpv4AddressPools] } },
    '#withLocation':: d.fn(help='"Immutable. The location of the resource."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withReleaseChannel':: d.fn(help='"The release channel a cluster is subscribed to. Possible values: [\\"RELEASE_CHANNEL_UNSPECIFIED\\", \\"NONE\\", \\"REGULAR\\"]."', args=[d.arg(name='releaseChannel', type=d.T.string)]),
    withReleaseChannel(releaseChannel): { spec+: { releaseChannel: releaseChannel } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withTargetVersion':: d.fn(help='"The target cluster version. For example: \\"1.5.0\\"."', args=[d.arg(name='targetVersion', type=d.T.string)]),
    withTargetVersion(targetVersion): { spec+: { targetVersion: targetVersion } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
