{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='datastreamConnectionProfile', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of DatastreamConnectionProfile', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'datastream.cnrm.cloud.google.com/v1alpha1',
    kind: 'DatastreamConnectionProfile',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#forwardSshConnectivity':: d.obj(help='"Forward SSH tunnel connectivity."'),
    forwardSshConnectivity: {
      '#password':: d.obj(help='"Immutable. SSH password."'),
      password: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { forwardSshConnectivity+: { password+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { forwardSshConnectivity+: { password+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { forwardSshConnectivity+: { password+: { value: value } } } },
      },
      '#privateKey':: d.obj(help='"Immutable. SSH private key."'),
      privateKey: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { forwardSshConnectivity+: { privateKey+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { forwardSshConnectivity+: { privateKey+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { forwardSshConnectivity+: { privateKey+: { value: value } } } },
      },
      '#withHostname':: d.fn(help='"Hostname for the SSH tunnel."', args=[d.arg(name='hostname', type=d.T.string)]),
      withHostname(hostname): { spec+: { forwardSshConnectivity+: { hostname: hostname } } },
      '#withPort':: d.fn(help='"Port for the SSH tunnel."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { forwardSshConnectivity+: { port: port } } },
      '#withUsername':: d.fn(help='"Username for the SSH tunnel."', args=[d.arg(name='username', type=d.T.string)]),
      withUsername(username): { spec+: { forwardSshConnectivity+: { username: username } } },
    },
    '#gcsProfile':: d.obj(help='"Cloud Storage bucket profile."'),
    gcsProfile: {
      '#withBucket':: d.fn(help='"The Cloud Storage bucket name."', args=[d.arg(name='bucket', type=d.T.string)]),
      withBucket(bucket): { spec+: { gcsProfile+: { bucket: bucket } } },
      '#withRootPath':: d.fn(help='"The root path inside the Cloud Storage bucket."', args=[d.arg(name='rootPath', type=d.T.string)]),
      withRootPath(rootPath): { spec+: { gcsProfile+: { rootPath: rootPath } } },
    },
    '#mysqlProfile':: d.obj(help='"MySQL database profile."'),
    mysqlProfile: {
      '#password':: d.obj(help='"Password for the MySQL connection."'),
      password: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { mysqlProfile+: { password+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { mysqlProfile+: { password+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { mysqlProfile+: { password+: { value: value } } } },
      },
      '#sslConfig':: d.obj(help='"SSL configuration for the MySQL connection."'),
      sslConfig: {
        '#caCertificate':: d.obj(help="\"Immutable. PEM-encoded certificate of the CA that signed the source database\\nserver's certificate.\""),
        caCertificate: {
          '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
          valueFrom: {
            '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
            secretKeyRef: {
              '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { spec+: { mysqlProfile+: { sslConfig+: { caCertificate+: { valueFrom+: { secretKeyRef+: { key: key } } } } } } },
              '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { spec+: { mysqlProfile+: { sslConfig+: { caCertificate+: { valueFrom+: { secretKeyRef+: { name: name } } } } } } },
            },
          },
          '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { spec+: { mysqlProfile+: { sslConfig+: { caCertificate+: { value: value } } } } },
        },
        '#clientCertificate':: d.obj(help="\"Immutable. PEM-encoded certificate that will be used by the replica to\\nauthenticate against the source database server. If this field\\nis used then the 'clientKey' and the 'caCertificate' fields are\\nmandatory.\""),
        clientCertificate: {
          '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
          valueFrom: {
            '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
            secretKeyRef: {
              '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { spec+: { mysqlProfile+: { sslConfig+: { clientCertificate+: { valueFrom+: { secretKeyRef+: { key: key } } } } } } },
              '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { spec+: { mysqlProfile+: { sslConfig+: { clientCertificate+: { valueFrom+: { secretKeyRef+: { name: name } } } } } } },
            },
          },
          '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { spec+: { mysqlProfile+: { sslConfig+: { clientCertificate+: { value: value } } } } },
        },
        '#clientKey':: d.obj(help="\"Immutable. PEM-encoded private key associated with the Client Certificate.\\nIf this field is used then the 'client_certificate' and the\\n'ca_certificate' fields are mandatory.\""),
        clientKey: {
          '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
          valueFrom: {
            '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
            secretKeyRef: {
              '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
              withKey(key): { spec+: { mysqlProfile+: { sslConfig+: { clientKey+: { valueFrom+: { secretKeyRef+: { key: key } } } } } } },
              '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
              withName(name): { spec+: { mysqlProfile+: { sslConfig+: { clientKey+: { valueFrom+: { secretKeyRef+: { name: name } } } } } } },
            },
          },
          '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
          withValue(value): { spec+: { mysqlProfile+: { sslConfig+: { clientKey+: { value: value } } } } },
        },
        '#withCaCertificateSet':: d.fn(help='"Indicates whether the clientKey field is set."', args=[d.arg(name='caCertificateSet', type=d.T.boolean)]),
        withCaCertificateSet(caCertificateSet): { spec+: { mysqlProfile+: { sslConfig+: { caCertificateSet: caCertificateSet } } } },
        '#withClientCertificateSet':: d.fn(help='"Indicates whether the clientCertificate field is set."', args=[d.arg(name='clientCertificateSet', type=d.T.boolean)]),
        withClientCertificateSet(clientCertificateSet): { spec+: { mysqlProfile+: { sslConfig+: { clientCertificateSet: clientCertificateSet } } } },
        '#withClientKeySet':: d.fn(help='"Indicates whether the clientKey field is set."', args=[d.arg(name='clientKeySet', type=d.T.boolean)]),
        withClientKeySet(clientKeySet): { spec+: { mysqlProfile+: { sslConfig+: { clientKeySet: clientKeySet } } } },
      },
      '#withHostname':: d.fn(help='"Hostname for the MySQL connection."', args=[d.arg(name='hostname', type=d.T.string)]),
      withHostname(hostname): { spec+: { mysqlProfile+: { hostname: hostname } } },
      '#withPort':: d.fn(help='"Port for the MySQL connection."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { mysqlProfile+: { port: port } } },
      '#withUsername':: d.fn(help='"Username for the MySQL connection."', args=[d.arg(name='username', type=d.T.string)]),
      withUsername(username): { spec+: { mysqlProfile+: { username: username } } },
    },
    '#oracleProfile':: d.obj(help='"Oracle database profile."'),
    oracleProfile: {
      '#password':: d.obj(help='"Password for the Oracle connection."'),
      password: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { oracleProfile+: { password+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { oracleProfile+: { password+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { oracleProfile+: { password+: { value: value } } } },
      },
      '#withConnectionAttributes':: d.fn(help='"Connection string attributes."', args=[d.arg(name='connectionAttributes', type=d.T.object)]),
      withConnectionAttributes(connectionAttributes): { spec+: { oracleProfile+: { connectionAttributes: connectionAttributes } } },
      '#withConnectionAttributesMixin':: d.fn(help='"Connection string attributes."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='connectionAttributes', type=d.T.object)]),
      withConnectionAttributesMixin(connectionAttributes): { spec+: { oracleProfile+: { connectionAttributes+: connectionAttributes } } },
      '#withDatabaseService':: d.fn(help='"Database for the Oracle connection."', args=[d.arg(name='databaseService', type=d.T.string)]),
      withDatabaseService(databaseService): { spec+: { oracleProfile+: { databaseService: databaseService } } },
      '#withHostname':: d.fn(help='"Hostname for the Oracle connection."', args=[d.arg(name='hostname', type=d.T.string)]),
      withHostname(hostname): { spec+: { oracleProfile+: { hostname: hostname } } },
      '#withPort':: d.fn(help='"Port for the Oracle connection."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { oracleProfile+: { port: port } } },
      '#withUsername':: d.fn(help='"Username for the Oracle connection."', args=[d.arg(name='username', type=d.T.string)]),
      withUsername(username): { spec+: { oracleProfile+: { username: username } } },
    },
    '#postgresqlProfile':: d.obj(help='"PostgreSQL database profile."'),
    postgresqlProfile: {
      '#password':: d.obj(help='"Password for the PostgreSQL connection."'),
      password: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { postgresqlProfile+: { password+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { postgresqlProfile+: { password+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { postgresqlProfile+: { password+: { value: value } } } },
      },
      '#withDatabase':: d.fn(help='"Database for the PostgreSQL connection."', args=[d.arg(name='database', type=d.T.string)]),
      withDatabase(database): { spec+: { postgresqlProfile+: { database: database } } },
      '#withHostname':: d.fn(help='"Hostname for the PostgreSQL connection."', args=[d.arg(name='hostname', type=d.T.string)]),
      withHostname(hostname): { spec+: { postgresqlProfile+: { hostname: hostname } } },
      '#withPort':: d.fn(help='"Port for the PostgreSQL connection."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { postgresqlProfile+: { port: port } } },
      '#withUsername':: d.fn(help='"Username for the PostgreSQL connection."', args=[d.arg(name='username', type=d.T.string)]),
      withUsername(username): { spec+: { postgresqlProfile+: { username: username } } },
    },
    '#privateConnectivity':: d.obj(help='"Private connectivity."'),
    privateConnectivity: {
      '#withPrivateConnection':: d.fn(help="\"A reference to a private connection resource. Format: 'projects/{project}/locations/{location}/privateConnections/{name}'.\"", args=[d.arg(name='privateConnection', type=d.T.string)]),
      withPrivateConnection(privateConnection): { spec+: { privateConnectivity+: { privateConnection: privateConnection } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#withBigqueryProfile':: d.fn(help='"BigQuery warehouse profile."', args=[d.arg(name='bigqueryProfile', type=d.T.object)]),
    withBigqueryProfile(bigqueryProfile): { spec+: { bigqueryProfile: bigqueryProfile } },
    '#withBigqueryProfileMixin':: d.fn(help='"BigQuery warehouse profile."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='bigqueryProfile', type=d.T.object)]),
    withBigqueryProfileMixin(bigqueryProfile): { spec+: { bigqueryProfile+: bigqueryProfile } },
    '#withDisplayName':: d.fn(help='"Display name."', args=[d.arg(name='displayName', type=d.T.string)]),
    withDisplayName(displayName): { spec+: { displayName: displayName } },
    '#withLocation':: d.fn(help='"Immutable. The name of the location this connection profile is located in."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The connectionProfileId of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
