{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='cloudTasksQueue', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of CloudTasksQueue', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'cloudtasks.cnrm.cloud.google.com/v1alpha1',
    kind: 'CloudTasksQueue',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#appEngineRoutingOverride':: d.obj(help='"Overrides for task-level appEngineRouting. These settings apply only\\nto App Engine tasks in this queue."'),
    appEngineRoutingOverride: {
      '#withHost':: d.fn(help='"The host that the task is sent to."', args=[d.arg(name='host', type=d.T.string)]),
      withHost(host): { spec+: { appEngineRoutingOverride+: { host: host } } },
      '#withInstance':: d.fn(help='"App instance.\\n\\nBy default, the task is sent to an instance which is available when the task is attempted."', args=[d.arg(name='instance', type=d.T.string)]),
      withInstance(instance): { spec+: { appEngineRoutingOverride+: { instance: instance } } },
      '#withService':: d.fn(help='"App service.\\n\\nBy default, the task is sent to the service which is the default service when the task is attempted."', args=[d.arg(name='service', type=d.T.string)]),
      withService(service): { spec+: { appEngineRoutingOverride+: { service: service } } },
      '#withVersion':: d.fn(help='"App version.\\n\\nBy default, the task is sent to the version which is the default version when the task is attempted."', args=[d.arg(name='version', type=d.T.string)]),
      withVersion(version): { spec+: { appEngineRoutingOverride+: { version: version } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#rateLimits':: d.obj(help="\"Rate limits for task dispatches.\\n\\nThe queue's actual dispatch rate is the result of:\\n\\n* Number of tasks in the queue\\n* User-specified throttling: rateLimits, retryConfig, and the queue's state.\\n* System throttling due to 429 (Too Many Requests) or 503 (Service\\n  Unavailable) responses from the worker, high error rates, or to\\n  smooth sudden large traffic spikes.\""),
    rateLimits: {
      '#withMaxBurstSize':: d.fn(help='"The max burst size.\\n\\nMax burst size limits how fast tasks in queue are processed when many tasks are\\nin the queue and the rate is high. This field allows the queue to have a high\\nrate so processing starts shortly after a task is enqueued, but still limits\\nresource usage when many tasks are enqueued in a short period of time."', args=[d.arg(name='maxBurstSize', type=d.T.integer)]),
      withMaxBurstSize(maxBurstSize): { spec+: { rateLimits+: { maxBurstSize: maxBurstSize } } },
      '#withMaxConcurrentDispatches':: d.fn(help='"The maximum number of concurrent tasks that Cloud Tasks allows to\\nbe dispatched for this queue. After this threshold has been\\nreached, Cloud Tasks stops dispatching tasks until the number of\\nconcurrent requests decreases."', args=[d.arg(name='maxConcurrentDispatches', type=d.T.integer)]),
      withMaxConcurrentDispatches(maxConcurrentDispatches): { spec+: { rateLimits+: { maxConcurrentDispatches: maxConcurrentDispatches } } },
      '#withMaxDispatchesPerSecond':: d.fn(help='"The maximum rate at which tasks are dispatched from this queue.\\n\\nIf unspecified when the queue is created, Cloud Tasks will pick the default."', args=[d.arg(name='maxDispatchesPerSecond', type=d.T.number)]),
      withMaxDispatchesPerSecond(maxDispatchesPerSecond): { spec+: { rateLimits+: { maxDispatchesPerSecond: maxDispatchesPerSecond } } },
    },
    '#retryConfig':: d.obj(help='"Settings that determine the retry behavior."'),
    retryConfig: {
      '#withMaxAttempts':: d.fn(help='"Number of attempts per task.\\n\\nCloud Tasks will attempt the task maxAttempts times (that is, if\\nthe first attempt fails, then there will be maxAttempts - 1\\nretries). Must be >= -1.\\n\\nIf unspecified when the queue is created, Cloud Tasks will pick\\nthe default.\\n\\n-1 indicates unlimited attempts."', args=[d.arg(name='maxAttempts', type=d.T.integer)]),
      withMaxAttempts(maxAttempts): { spec+: { retryConfig+: { maxAttempts: maxAttempts } } },
      '#withMaxBackoff':: d.fn(help="\"A task will be scheduled for retry between minBackoff and\\nmaxBackoff duration after it fails, if the queue's RetryConfig\\nspecifies that the task should be retried.\"", args=[d.arg(name='maxBackoff', type=d.T.string)]),
      withMaxBackoff(maxBackoff): { spec+: { retryConfig+: { maxBackoff: maxBackoff } } },
      '#withMaxDoublings':: d.fn(help="\"The time between retries will double maxDoublings times.\\n\\nA task's retry interval starts at minBackoff, then doubles maxDoublings times,\\nthen increases linearly, and finally retries retries at intervals of maxBackoff\\nup to maxAttempts times.\"", args=[d.arg(name='maxDoublings', type=d.T.integer)]),
      withMaxDoublings(maxDoublings): { spec+: { retryConfig+: { maxDoublings: maxDoublings } } },
      '#withMaxRetryDuration':: d.fn(help='"If positive, maxRetryDuration specifies the time limit for\\nretrying a failed task, measured from when the task was first\\nattempted. Once maxRetryDuration time has passed and the task has\\nbeen attempted maxAttempts times, no further attempts will be\\nmade and the task will be deleted.\\n\\nIf zero, then the task age is unlimited."', args=[d.arg(name='maxRetryDuration', type=d.T.string)]),
      withMaxRetryDuration(maxRetryDuration): { spec+: { retryConfig+: { maxRetryDuration: maxRetryDuration } } },
      '#withMinBackoff':: d.fn(help="\"A task will be scheduled for retry between minBackoff and\\nmaxBackoff duration after it fails, if the queue's RetryConfig\\nspecifies that the task should be retried.\"", args=[d.arg(name='minBackoff', type=d.T.string)]),
      withMinBackoff(minBackoff): { spec+: { retryConfig+: { minBackoff: minBackoff } } },
    },
    '#stackdriverLoggingConfig':: d.obj(help='"Configuration options for writing logs to Stackdriver Logging."'),
    stackdriverLoggingConfig: {
      '#withSamplingRatio':: d.fn(help='"Specifies the fraction of operations to write to Stackdriver Logging.\\nThis field may contain any value between 0.0 and 1.0, inclusive. 0.0 is the\\ndefault and means that no operations are logged."', args=[d.arg(name='samplingRatio', type=d.T.number)]),
      withSamplingRatio(samplingRatio): { spec+: { stackdriverLoggingConfig+: { samplingRatio: samplingRatio } } },
    },
    '#withLocation':: d.fn(help='"Immutable. The location of the queue."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
