{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='containerAttachedCluster', url='', help='"ContainerAttachedCluster is the Schema for the ContainerAttachedCluster API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of ContainerAttachedCluster', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'containerattached.cnrm.cloud.google.com/v1beta1',
    kind: 'ContainerAttachedCluster',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"ContainerAttachedClusterSpec defines the desired state of ContainerAttachedCluster"'),
  spec: {
    '#authorization':: d.obj(help='"Optional. Configuration related to the cluster RBAC settings."'),
    authorization: {
      '#withAdminUsers':: d.fn(help='"Optional. Users that can perform operations as a cluster admin. A managed\\n ClusterRoleBinding will be created to grant the `cluster-admin` ClusterRole\\n to the users. Up to ten admin users can be provided.\\n\\n For more info on RBAC, see\\n https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles"', args=[d.arg(name='adminUsers', type=d.T.array)]),
      withAdminUsers(adminUsers): { spec+: { authorization+: { adminUsers: if std.isArray(v=adminUsers) then adminUsers else [adminUsers] } } },
      '#withAdminUsersMixin':: d.fn(help='"Optional. Users that can perform operations as a cluster admin. A managed\\n ClusterRoleBinding will be created to grant the `cluster-admin` ClusterRole\\n to the users. Up to ten admin users can be provided.\\n\\n For more info on RBAC, see\\n https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='adminUsers', type=d.T.array)]),
      withAdminUsersMixin(adminUsers): { spec+: { authorization+: { adminUsers+: if std.isArray(v=adminUsers) then adminUsers else [adminUsers] } } },
    },
    '#binaryAuthorization':: d.obj(help='"Optional. Binary Authorization configuration for this cluster."'),
    binaryAuthorization: {
      '#withEvaluationMode':: d.fn(help='"Mode of operation for binauthz policy evaluation. If unspecified, defaults to DISABLED. Possible values: [\\"DISABLED\\", \\"PROJECT_SINGLETON_POLICY_ENFORCE\\"]."', args=[d.arg(name='evaluationMode', type=d.T.string)]),
      withEvaluationMode(evaluationMode): { spec+: { binaryAuthorization+: { evaluationMode: evaluationMode } } },
    },
    '#fleet':: d.obj(help='"Required. Fleet configuration."'),
    fleet: {
      '#projectRef':: d.obj(help='"The id of the Fleet host project where this cluster will be registered."'),
      projectRef: {
        '#withExternal':: d.fn(help='"The project of the fleet. Allowed value: The Google Cloud resource name of a `Project` resource (format: `projects/{{name}}`)."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { fleet+: { projectRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the project resource. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { fleet+: { projectRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the project resource. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { fleet+: { projectRef+: { namespace: namespace } } } },
      },
      '#withMembership':: d.fn(help='"Output only. The name of the managed Hub Membership resource associated to\\n this cluster.\\n\\n Membership names are formatted as\\n `projects/<project-number>/locations/global/membership/<cluster-id>`."', args=[d.arg(name='membership', type=d.T.string)]),
      withMembership(membership): { spec+: { fleet+: { membership: membership } } },
    },
    '#loggingConfig':: d.obj(help='"Optional. Logging configuration for this cluster."'),
    loggingConfig: {
      '#componentConfig':: d.obj(help='"The configuration of the logging components;"'),
      componentConfig: {
        '#withEnableComponents':: d.fn(help='"The components to be enabled. Possible values: [\\"SYSTEM_COMPONENTS\\", \\"WORKLOADS\\"]."', args=[d.arg(name='enableComponents', type=d.T.array)]),
        withEnableComponents(enableComponents): { spec+: { loggingConfig+: { componentConfig+: { enableComponents: if std.isArray(v=enableComponents) then enableComponents else [enableComponents] } } } },
        '#withEnableComponentsMixin':: d.fn(help='"The components to be enabled. Possible values: [\\"SYSTEM_COMPONENTS\\", \\"WORKLOADS\\"]."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='enableComponents', type=d.T.array)]),
        withEnableComponentsMixin(enableComponents): { spec+: { loggingConfig+: { componentConfig+: { enableComponents+: if std.isArray(v=enableComponents) then enableComponents else [enableComponents] } } } },
      },
    },
    '#monitoringConfig':: d.obj(help='"Optional. Monitoring configuration for this cluster."'),
    monitoringConfig: {
      '#managedPrometheusConfig':: d.obj(help='"Enable Google Cloud Managed Service for Prometheus in the cluster."'),
      managedPrometheusConfig: {
        '#withEnabled':: d.fn(help='"Enable Managed Collection."', args=[d.arg(name='enabled', type=d.T.boolean)]),
        withEnabled(enabled): { spec+: { monitoringConfig+: { managedPrometheusConfig+: { enabled: enabled } } } },
      },
    },
    '#oidcConfig':: d.obj(help="\"Required. OpenID Connect (OIDC) discovery information of the target cluster.\\n\\nKubernetes Service Account (KSA) tokens are JWT tokens signed by the cluster\\nAPI server. This field indicates how GCP services\\tvalidate KSA tokens in order\\nto allow system workloads (such as GKE Connect and telemetry agents) to\\nauthenticate back to GCP.\\n\\nBoth clusters with public and private issuer URLs are supported.\\nClusters with public issuers only need to specify the 'issuerUrl' field\\nwhile clusters with private issuers need to provide both 'issuerUrl' and 'jwks'.\""),
    oidcConfig: {
      '#withIssuerUrl':: d.fn(help='"Immutable. A JSON Web Token (JWT) issuer URI. `issuer` must start with `https://`."', args=[d.arg(name='issuerUrl', type=d.T.string)]),
      withIssuerUrl(issuerUrl): { spec+: { oidcConfig+: { issuerUrl: issuerUrl } } },
      '#withJwks':: d.fn(help="\"Immutable, Optional. OIDC verification keys in JWKS format (RFC 7517).\\n It contains a list of OIDC verification keys that can be used to verify\\n OIDC JWTs.\\n\\n This field is required for cluster that doesn't have a publicly available\\n discovery endpoint. When provided, it will be directly used\\n to verify the OIDC JWT asserted by the IDP.\"", args=[d.arg(name='jwks', type=d.T.string)]),
      withJwks(jwks): { spec+: { oidcConfig+: { jwks: jwks } } },
    },
    '#projectRef':: d.obj(help='"The ID of the project in which the resource belongs."'),
    projectRef: {
      '#withExternal':: d.fn(help='"The `projectID` field of a project, when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withKind':: d.fn(help='"The kind of the Project resource; optional but must be `Project` if provided."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { projectRef+: { kind: kind } } },
      '#withName':: d.fn(help='"The `name` field of a `Project` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `Project` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#withAnnotations':: d.fn(help='"Optional. Annotations on the cluster.\\n\\n This field has the same restrictions as Kubernetes annotations.\\n The total size of all keys and values combined is limited to 256k.\\n Key can have 2 segments: prefix (optional) and name (required),\\n separated by a slash (/).\\n Prefix must be a DNS subdomain.\\n Name must be 63 characters or less, begin and end with alphanumerics,\\n with dashes (-), underscores (_), dots (.), and alphanumerics between."', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { spec+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Optional. Annotations on the cluster.\\n\\n This field has the same restrictions as Kubernetes annotations.\\n The total size of all keys and values combined is limited to 256k.\\n Key can have 2 segments: prefix (optional) and name (required),\\n separated by a slash (/).\\n Prefix must be a DNS subdomain.\\n Name must be 63 characters or less, begin and end with alphanumerics,\\n with dashes (-), underscores (_), dots (.), and alphanumerics between."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { spec+: { annotations+: annotations } },
    '#withDeletionPolicy':: d.fn(help='"Optional. Policy to determine what flags to send on delete."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withDescription':: d.fn(help='"Optional. A human readable description of this Attached cluster. Cannot be longer than 255 UTF-8 encoded bytes."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withDistribution':: d.fn(help='"Immutable. The Kubernetes distribution of the underlying attached cluster.\\n\\n Supported values: [\\"eks\\", \\"aks\\", \\"generic\\"]."', args=[d.arg(name='distribution', type=d.T.string)]),
    withDistribution(distribution): { spec+: { distribution: distribution } },
    '#withLocation':: d.fn(help='"Immutable. The location for the resource."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withPlatformVersion':: d.fn(help='"Required. The platform version for the cluster (e.g. `1.30.0-gke.1`)."', args=[d.arg(name='platformVersion', type=d.T.string)]),
    withPlatformVersion(platformVersion): { spec+: { platformVersion: platformVersion } },
    '#withResourceID':: d.fn(help='"Immutable, Optional. The ContainerAttachedCluster name. If not given, the metadata.name will be used."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
