{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='bigQueryDataset', url='', help='"BigQueryDataset is the Schema for the BigQueryDataset API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of BigQueryDataset', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'bigquery.cnrm.cloud.google.com/v1beta1',
    kind: 'BigQueryDataset',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"BigQueryDatasetSpec defines the desired state of BigQueryDataset"'),
  spec: {
    '#access':: d.obj(help='"An array of objects that define dataset access for one or more entities."'),
    access: {
      '#dataset':: d.obj(help='"[Pick one] A grant authorizing all resources of a particular type in a particular dataset access to this dataset. Only views are supported for now. The role field is not required when this field is set. If that dataset is deleted and re-created, its access needs to be granted again via an update operation."'),
      dataset: {
        '#dataset':: d.obj(help='"The dataset this entry applies to."'),
        dataset: {
          '#withDatasetId':: d.fn(help='"A unique Id for this dataset, without the project name. The Id must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_). The maximum length is 1,024 characters."', args=[d.arg(name='datasetId', type=d.T.string)]),
          withDatasetId(datasetId): { dataset+: { dataset+: { datasetId: datasetId } } },
          '#withProjectId':: d.fn(help='"The ID of the project containing this dataset."', args=[d.arg(name='projectId', type=d.T.string)]),
          withProjectId(projectId): { dataset+: { dataset+: { projectId: projectId } } },
        },
        '#withTargetTypes':: d.fn(help='"Which resources in the dataset this entry applies to. Currently, only views are supported, but additional target types may be added in the future."', args=[d.arg(name='targetTypes', type=d.T.array)]),
        withTargetTypes(targetTypes): { dataset+: { targetTypes: if std.isArray(v=targetTypes) then targetTypes else [targetTypes] } },
        '#withTargetTypesMixin':: d.fn(help='"Which resources in the dataset this entry applies to. Currently, only views are supported, but additional target types may be added in the future."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetTypes', type=d.T.array)]),
        withTargetTypesMixin(targetTypes): { dataset+: { targetTypes+: if std.isArray(v=targetTypes) then targetTypes else [targetTypes] } },
      },
      '#routine':: d.obj(help='"[Pick one] A routine from a different dataset to grant access to. Queries executed against that routine will have read access to views/tables/routines in this dataset. Only UDF is supported for now. The role field is not required when this field is set. If that routine is updated by any user, access to the routine needs to be granted again via an update operation."'),
      routine: {
        '#withDatasetId':: d.fn(help='"The ID of the dataset containing this routine."', args=[d.arg(name='datasetId', type=d.T.string)]),
        withDatasetId(datasetId): { routine+: { datasetId: datasetId } },
        '#withProjectId':: d.fn(help='"The ID of the project containing this routine."', args=[d.arg(name='projectId', type=d.T.string)]),
        withProjectId(projectId): { routine+: { projectId: projectId } },
        '#withRoutineId':: d.fn(help='"The Id of the routine. The Id must contain only letters (a-z, A-Z), numbers (0-9), or underscores (_). The maximum length is 256 characters."', args=[d.arg(name='routineId', type=d.T.string)]),
        withRoutineId(routineId): { routine+: { routineId: routineId } },
      },
      '#view':: d.obj(help='"[Pick one] A view from a different dataset to grant access to. Queries executed against that view will have read access to views/tables/routines in this dataset. The role field is not required when this field is set. If that view is updated by any user, access to the view needs to be granted again via an update operation."'),
      view: {
        '#withDatasetId':: d.fn(help='"The ID of the dataset containing this table."', args=[d.arg(name='datasetId', type=d.T.string)]),
        withDatasetId(datasetId): { view+: { datasetId: datasetId } },
        '#withProjectId':: d.fn(help='"The ID of the project containing this table."', args=[d.arg(name='projectId', type=d.T.string)]),
        withProjectId(projectId): { view+: { projectId: projectId } },
        '#withTableId':: d.fn(help='"The Id of the table. The Id can contain Unicode characters in category L (letter), M (mark), N (number), Pc (connector, including underscore), Pd (dash), and Zs (space). For more information, see [General Category](https://wikipedia.org/wiki/Unicode_character_property#General_Category). The maximum length is 1,024 characters.  Certain operations allow suffixing of the table Id with a partition decorator, such as `sample_table$20190123`."', args=[d.arg(name='tableId', type=d.T.string)]),
        withTableId(tableId): { view+: { tableId: tableId } },
      },
      '#withDomain':: d.fn(help='"[Pick one] A domain to grant access to. Any users signed in with the domain specified will be granted the specified access. Example: \\"example.com\\". Maps to IAM policy member \\"domain:DOMAIN\\"."', args=[d.arg(name='domain', type=d.T.string)]),
      withDomain(domain): { domain: domain },
      '#withGroupByEmail':: d.fn(help='"[Pick one] An email address of a Google Group to grant access to. Maps to IAM policy member \\"group:GROUP\\"."', args=[d.arg(name='groupByEmail', type=d.T.string)]),
      withGroupByEmail(groupByEmail): { groupByEmail: groupByEmail },
      '#withIamMember':: d.fn(help="\"[Pick one] Some other type of member that appears in the IAM Policy but isn't a user, group, domain, or special group.\"", args=[d.arg(name='iamMember', type=d.T.string)]),
      withIamMember(iamMember): { iamMember: iamMember },
      '#withRole':: d.fn(help='"An IAM role ID that should be granted to the user, group,\\n or domain specified in this access entry.\\n The following legacy mappings will be applied:\\n\\n * `OWNER`: `roles/bigquery.dataOwner`\\n * `WRITER`: `roles/bigquery.dataEditor`\\n * `READER`: `roles/bigquery.dataViewer`\\n\\n This field will accept any of the above formats, but will return only\\n the legacy format. For example, if you set this field to\\n \\"roles/bigquery.dataOwner\\", it will be returned back as \\"OWNER\\"."', args=[d.arg(name='role', type=d.T.string)]),
      withRole(role): { role: role },
      '#withSpecialGroup':: d.fn(help='"[Pick one] A special group to grant access to. Possible values include:\\n\\n   * projectOwners: Owners of the enclosing project.\\n   * projectReaders: Readers of the enclosing project.\\n   * projectWriters: Writers of the enclosing project.\\n   * allAuthenticatedUsers: All authenticated BigQuery users.\\n\\n Maps to similarly-named IAM members."', args=[d.arg(name='specialGroup', type=d.T.string)]),
      withSpecialGroup(specialGroup): { specialGroup: specialGroup },
      '#withUserByEmail':: d.fn(help='"[Pick one] An email address of a user to grant access to. For example: fred@example.com. Maps to IAM policy member \\"user:EMAIL\\" or \\"serviceAccount:EMAIL\\"."', args=[d.arg(name='userByEmail', type=d.T.string)]),
      withUserByEmail(userByEmail): { userByEmail: userByEmail },
    },
    '#defaultEncryptionConfiguration':: d.obj(help='"The default encryption key for all tables in the dataset. After this property is set, the encryption key of all newly-created tables in the dataset is set to this value unless the table creation request or query explicitly overrides the key."'),
    defaultEncryptionConfiguration: {
      '#kmsKeyRef':: d.obj(help='"Optional. Describes the Cloud KMS encryption key that will be used to protect destination BigQuery table. The BigQuery Service Account associated with your project requires access to this encryption key."'),
      kmsKeyRef: {
        '#withExternal':: d.fn(help='"A reference to an externally managed KMSCryptoKey. Should be in the format `projects/[kms_project_id]/locations/[region]/keyRings/[key_ring_id]/cryptoKeys/[key]`."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { defaultEncryptionConfiguration+: { kmsKeyRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` of a `KMSCryptoKey` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { defaultEncryptionConfiguration+: { kmsKeyRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` of a `KMSCryptoKey` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { defaultEncryptionConfiguration+: { kmsKeyRef+: { namespace: namespace } } } },
      },
    },
    '#projectRef':: d.obj(help='" Optional. The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"The `projectID` field of a project, when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withKind':: d.fn(help='"The kind of the Project resource; optional but must be `Project` if provided."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { projectRef+: { kind: kind } } },
      '#withName':: d.fn(help='"The `name` field of a `Project` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `Project` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#withAccess':: d.fn(help='"An array of objects that define dataset access for one or more entities."', args=[d.arg(name='access', type=d.T.array)]),
    withAccess(access): { spec+: { access: if std.isArray(v=access) then access else [access] } },
    '#withAccessMixin':: d.fn(help='"An array of objects that define dataset access for one or more entities."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='access', type=d.T.array)]),
    withAccessMixin(access): { spec+: { access+: if std.isArray(v=access) then access else [access] } },
    '#withDefaultCollation':: d.fn(help="\"Optional. Defines the default collation specification of future tables\\n created in the dataset. If a table is created in this dataset without\\n table-level default collation, then the table inherits the dataset default\\n collation, which is applied to the string fields that do not have explicit\\n collation specified. A change to this field affects only tables created\\n afterwards, and does not alter the existing tables.\\n The following values are supported:\\n\\n * 'und:ci': undetermined locale, case insensitive.\\n * '': empty string. Default to case-sensitive behavior.\"", args=[d.arg(name='defaultCollation', type=d.T.string)]),
    withDefaultCollation(defaultCollation): { spec+: { defaultCollation: defaultCollation } },
    '#withDefaultPartitionExpirationMs':: d.fn(help='"This default partition expiration, expressed in milliseconds.\\n\\n When new time-partitioned tables are created in a dataset where this\\n property is set, the table will inherit this value, propagated as the\\n `TimePartitioning.expirationMs` property on the new table.  If you set\\n `TimePartitioning.expirationMs` explicitly when creating a table,\\n the `defaultPartitionExpirationMs` of the containing dataset is ignored.\\n\\n When creating a partitioned table, if `defaultPartitionExpirationMs`\\n is set, the `defaultTableExpirationMs` value is ignored and the table\\n will not be inherit a table expiration deadline."', args=[d.arg(name='defaultPartitionExpirationMs', type=d.T.integer)]),
    withDefaultPartitionExpirationMs(defaultPartitionExpirationMs): { spec+: { defaultPartitionExpirationMs: defaultPartitionExpirationMs } },
    '#withDefaultTableExpirationMs':: d.fn(help="\"Optional. The default lifetime of all tables in the dataset, in milliseconds. The minimum lifetime value is 3600000 milliseconds (one hour). To clear an existing default expiration with a PATCH request, set to 0. Once this property is set, all newly-created tables in the dataset will have an expirationTime property set to the creation time plus the value in this property, and changing the value will only affect new tables, not existing ones. When the expirationTime for a given table is reached, that table will be deleted automatically. If a table's expirationTime is modified or removed before the table expires, or if you provide an explicit expirationTime when creating a table, that value takes precedence over the default expiration time indicated by this property.\"", args=[d.arg(name='defaultTableExpirationMs', type=d.T.integer)]),
    withDefaultTableExpirationMs(defaultTableExpirationMs): { spec+: { defaultTableExpirationMs: defaultTableExpirationMs } },
    '#withDescription':: d.fn(help='"Optional. A user-friendly description of the dataset."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withFriendlyName':: d.fn(help='"Optional. A descriptive name for the dataset."', args=[d.arg(name='friendlyName', type=d.T.string)]),
    withFriendlyName(friendlyName): { spec+: { friendlyName: friendlyName } },
    '#withIsCaseInsensitive':: d.fn(help='"Optional. TRUE if the dataset and its table names are case-insensitive, otherwise FALSE. By default, this is FALSE, which means the dataset and its table names are case-sensitive. This field does not affect routine references."', args=[d.arg(name='isCaseInsensitive', type=d.T.boolean)]),
    withIsCaseInsensitive(isCaseInsensitive): { spec+: { isCaseInsensitive: isCaseInsensitive } },
    '#withLocation':: d.fn(help='"Optional. The geographic location where the dataset should reside. See https://cloud.google.com/bigquery/docs/locations for supported locations."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withMaxTimeTravelHours':: d.fn(help='"Optional. Defines the time travel window in hours. The value can be from 48 to 168 hours (2 to 7 days). The default value is 168 hours if this is not set."', args=[d.arg(name='maxTimeTravelHours', type=d.T.string)]),
    withMaxTimeTravelHours(maxTimeTravelHours): { spec+: { maxTimeTravelHours: maxTimeTravelHours } },
    '#withResourceID':: d.fn(help='"The BigQueryDataset name. If not given, the metadata.name will be used."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withStorageBillingModel':: d.fn(help='"Optional. Updates storage_billing_model for the dataset."', args=[d.arg(name='storageBillingModel', type=d.T.string)]),
    withStorageBillingModel(storageBillingModel): { spec+: { storageBillingModel: storageBillingModel } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
