{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='alloyDBInstance', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of AlloyDBInstance', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'alloydb.cnrm.cloud.google.com/v1alpha1',
    kind: 'AlloyDBInstance',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#clusterRef':: d.obj(help=''),
    clusterRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of an `AlloyDBCluster` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { clusterRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { clusterRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { clusterRef+: { namespace: namespace } } },
    },
    '#instanceTypeRef':: d.obj(help='"The type of instance.\\nPossible values: [\\"PRIMARY\\", \\"READ_POOL\\", \\"SECONDARY\\"]\\nFor PRIMARY and SECONDARY instances, set the value to refer to the name of the associated cluster.\\nThis is recommended because the instance type of primary and secondary instances is tied to the cluster type of the associated cluster.\\nIf the secondary cluster is promoted to primary cluster, then the associated secondary instance also becomes primary instance.\\nExample:\\ninstanceTypeRef:\\n  name: clusterName\\nFor instances of type READ_POOL, set the value using external keyword.\\nExample:\\ninstanceTypeRef:\\n  external: READ_POOL\\nIf the instance type is SECONDARY, the delete instance operation does not delete the secondary instance but abandons it instead.\\nUse deletionPolicy = \\"FORCE\\" in the associated secondary cluster and delete the cluster forcefully to delete the secondary cluster as well its associated secondary instance."'),
    instanceTypeRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `clusterType` field of an `AlloyDBCluster` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { instanceTypeRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { instanceTypeRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { instanceTypeRef+: { namespace: namespace } } },
    },
    '#machineConfig':: d.obj(help='"Configurations for the machines that host the underlying database engine."'),
    machineConfig: {
      '#withCpuCount':: d.fn(help="\"The number of CPU's in the VM instance.\"", args=[d.arg(name='cpuCount', type=d.T.integer)]),
      withCpuCount(cpuCount): { spec+: { machineConfig+: { cpuCount: cpuCount } } },
    },
    '#networkConfig':: d.obj(help='"Instance level network configuration."'),
    networkConfig: {
      '#authorizedExternalNetworks':: d.obj(help="\"A list of external networks authorized to access this instance. This field is only allowed to be set when 'enable_public_ip' is set to true.\""),
      authorizedExternalNetworks: {
        '#withCidrRange':: d.fn(help='"CIDR range for one authorized network of the instance."', args=[d.arg(name='cidrRange', type=d.T.string)]),
        withCidrRange(cidrRange): { cidrRange: cidrRange },
      },
      '#withAuthorizedExternalNetworks':: d.fn(help="\"A list of external networks authorized to access this instance. This field is only allowed to be set when 'enable_public_ip' is set to true.\"", args=[d.arg(name='authorizedExternalNetworks', type=d.T.array)]),
      withAuthorizedExternalNetworks(authorizedExternalNetworks): { spec+: { networkConfig+: { authorizedExternalNetworks: if std.isArray(v=authorizedExternalNetworks) then authorizedExternalNetworks else [authorizedExternalNetworks] } } },
      '#withAuthorizedExternalNetworksMixin':: d.fn(help="\"A list of external networks authorized to access this instance. This field is only allowed to be set when 'enable_public_ip' is set to true.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='authorizedExternalNetworks', type=d.T.array)]),
      withAuthorizedExternalNetworksMixin(authorizedExternalNetworks): { spec+: { networkConfig+: { authorizedExternalNetworks+: if std.isArray(v=authorizedExternalNetworks) then authorizedExternalNetworks else [authorizedExternalNetworks] } } },
      '#withEnableOutboundPublicIp':: d.fn(help='"Enabling outbound public ip for the instance."', args=[d.arg(name='enableOutboundPublicIp', type=d.T.boolean)]),
      withEnableOutboundPublicIp(enableOutboundPublicIp): { spec+: { networkConfig+: { enableOutboundPublicIp: enableOutboundPublicIp } } },
      '#withEnablePublicIp':: d.fn(help='"Enabling public ip for the instance. If a user wishes to disable this, please also clear the list of the authorized external networks set on the same instance."', args=[d.arg(name='enablePublicIp', type=d.T.boolean)]),
      withEnablePublicIp(enablePublicIp): { spec+: { networkConfig+: { enablePublicIp: enablePublicIp } } },
    },
    '#readPoolConfig':: d.obj(help='"Read pool specific config. If the instance type is READ_POOL, this configuration must be provided."'),
    readPoolConfig: {
      '#withNodeCount':: d.fn(help='"Read capacity, i.e. number of nodes in a read pool instance."', args=[d.arg(name='nodeCount', type=d.T.integer)]),
      withNodeCount(nodeCount): { spec+: { readPoolConfig+: { nodeCount: nodeCount } } },
    },
    '#withAnnotations':: d.fn(help='"Annotations to allow client tools to store small amount of arbitrary data. This is distinct from labels."', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { spec+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations to allow client tools to store small amount of arbitrary data. This is distinct from labels."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { spec+: { annotations+: annotations } },
    '#withAvailabilityType':: d.fn(help="\"'Availability type of an Instance. Defaults to REGIONAL for both primary and read instances.\\nNote that primary and read instances can have different availability types.\\nOnly READ_POOL instance supports ZONAL type. Users can't specify the zone for READ_POOL instance.\\nZone is automatically chosen from the list of zones in the region specified.\\nRead pool of size 1 can only have zonal availability. Read pools with node count of 2 or more\\ncan have regional availability (nodes are present in 2 or more zones in a region).' Possible values: [\\\"AVAILABILITY_TYPE_UNSPECIFIED\\\", \\\"ZONAL\\\", \\\"REGIONAL\\\"].\"", args=[d.arg(name='availabilityType', type=d.T.string)]),
    withAvailabilityType(availabilityType): { spec+: { availabilityType: availabilityType } },
    '#withDatabaseFlags':: d.fn(help='"Database flags. Set at instance level. * They are copied from primary instance on read instance creation. * Read instances can set new or override existing flags that are relevant for reads, e.g. for enabling columnar cache on a read instance. Flags set on read instance may or may not be present on primary."', args=[d.arg(name='databaseFlags', type=d.T.object)]),
    withDatabaseFlags(databaseFlags): { spec+: { databaseFlags: databaseFlags } },
    '#withDatabaseFlagsMixin':: d.fn(help='"Database flags. Set at instance level. * They are copied from primary instance on read instance creation. * Read instances can set new or override existing flags that are relevant for reads, e.g. for enabling columnar cache on a read instance. Flags set on read instance may or may not be present on primary."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='databaseFlags', type=d.T.object)]),
    withDatabaseFlagsMixin(databaseFlags): { spec+: { databaseFlags+: databaseFlags } },
    '#withDisplayName':: d.fn(help='"User-settable and human-readable display name for the Instance."', args=[d.arg(name='displayName', type=d.T.string)]),
    withDisplayName(displayName): { spec+: { displayName: displayName } },
    '#withGceZone':: d.fn(help='"The Compute Engine zone that the instance should serve from, per https://cloud.google.com/compute/docs/regions-zones This can ONLY be specified for ZONAL instances. If present for a REGIONAL instance, an error will be thrown. If this is absent for a ZONAL instance, instance is created in a random zone with available capacity."', args=[d.arg(name='gceZone', type=d.T.string)]),
    withGceZone(gceZone): { spec+: { gceZone: gceZone } },
    '#withInstanceType':: d.fn(help='"We recommend that you use `instanceTypeRef` instead.\\nThe type of the instance. Possible values: [PRIMARY, READ_POOL, SECONDARY]"', args=[d.arg(name='instanceType', type=d.T.string)]),
    withInstanceType(instanceType): { spec+: { instanceType: instanceType } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The instanceId of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
