{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='vertexAIIndex', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of VertexAIIndex', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'vertexai.cnrm.cloud.google.com/v1beta1',
    kind: 'VertexAIIndex',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#metadata':: d.obj(help='"An additional information about the Index."'),
    metadata: {
      '#config':: d.obj(help='"Immutable. The configuration of the Matching Engine Index."'),
      config: {
        '#algorithmConfig':: d.obj(help='"The configuration with regard to the algorithms used for efficient search."'),
        algorithmConfig: {
          '#treeAhConfig':: d.obj(help='"Configuration options for using the tree-AH algorithm (Shallow tree + Asymmetric Hashing).\\nPlease refer to this paper for more details: https://arxiv.org/abs/1908.10396."'),
          treeAhConfig: {
            '#withLeafNodeEmbeddingCount':: d.fn(help='"Number of embeddings on each leaf node. The default value is 1000 if not set."', args=[d.arg(name='leafNodeEmbeddingCount', type=d.T.integer)]),
            withLeafNodeEmbeddingCount(leafNodeEmbeddingCount): { spec+: { metadata+: { config+: { algorithmConfig+: { treeAhConfig+: { leafNodeEmbeddingCount: leafNodeEmbeddingCount } } } } } },
            '#withLeafNodesToSearchPercent':: d.fn(help='"The default percentage of leaf nodes that any query may be searched. Must be in\\nrange 1-100, inclusive. The default value is 10 (means 10%) if not set."', args=[d.arg(name='leafNodesToSearchPercent', type=d.T.integer)]),
            withLeafNodesToSearchPercent(leafNodesToSearchPercent): { spec+: { metadata+: { config+: { algorithmConfig+: { treeAhConfig+: { leafNodesToSearchPercent: leafNodesToSearchPercent } } } } } },
          },
          '#withBruteForceConfig':: d.fn(help='"Configuration options for using brute force search, which simply implements the\\nstandard linear search in the database for each query."', args=[d.arg(name='bruteForceConfig', type=d.T.object)]),
          withBruteForceConfig(bruteForceConfig): { spec+: { metadata+: { config+: { algorithmConfig+: { bruteForceConfig: bruteForceConfig } } } } },
          '#withBruteForceConfigMixin':: d.fn(help='"Configuration options for using brute force search, which simply implements the\\nstandard linear search in the database for each query."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='bruteForceConfig', type=d.T.object)]),
          withBruteForceConfigMixin(bruteForceConfig): { spec+: { metadata+: { config+: { algorithmConfig+: { bruteForceConfig+: bruteForceConfig } } } } },
        },
        '#withApproximateNeighborsCount':: d.fn(help='"The default number of neighbors to find via approximate search before exact reordering is\\nperformed. Exact reordering is a procedure where results returned by an\\napproximate search algorithm are reordered via a more expensive distance computation.\\nRequired if tree-AH algorithm is used."', args=[d.arg(name='approximateNeighborsCount', type=d.T.integer)]),
        withApproximateNeighborsCount(approximateNeighborsCount): { spec+: { metadata+: { config+: { approximateNeighborsCount: approximateNeighborsCount } } } },
        '#withDimensions':: d.fn(help='"The number of dimensions of the input vectors."', args=[d.arg(name='dimensions', type=d.T.integer)]),
        withDimensions(dimensions): { spec+: { metadata+: { config+: { dimensions: dimensions } } } },
        '#withDistanceMeasureType':: d.fn(help='"The distance measure used in nearest neighbor search. The value must be one of the followings:\\n* SQUARED_L2_DISTANCE: Euclidean (L_2) Distance\\n* L1_DISTANCE: Manhattan (L_1) Distance\\n* COSINE_DISTANCE: Cosine Distance. Defined as 1 - cosine similarity.\\n* DOT_PRODUCT_DISTANCE: Dot Product Distance. Defined as a negative of the dot product."', args=[d.arg(name='distanceMeasureType', type=d.T.string)]),
        withDistanceMeasureType(distanceMeasureType): { spec+: { metadata+: { config+: { distanceMeasureType: distanceMeasureType } } } },
        '#withFeatureNormType':: d.fn(help='"Type of normalization to be carried out on each vector. The value must be one of the followings:\\n* UNIT_L2_NORM: Unit L2 normalization type\\n* NONE: No normalization type is specified."', args=[d.arg(name='featureNormType', type=d.T.string)]),
        withFeatureNormType(featureNormType): { spec+: { metadata+: { config+: { featureNormType: featureNormType } } } },
        '#withShardSize':: d.fn(help='"Immutable. Index data is split into equal parts to be processed. These are called \\"shards\\".\\nThe shard size must be specified when creating an index. The value must be one of the followings:\\n* SHARD_SIZE_SMALL: Small (2GB)\\n* SHARD_SIZE_MEDIUM: Medium (20GB)\\n* SHARD_SIZE_LARGE: Large (50GB)."', args=[d.arg(name='shardSize', type=d.T.string)]),
        withShardSize(shardSize): { spec+: { metadata+: { config+: { shardSize: shardSize } } } },
      },
      '#withContentsDeltaUri':: d.fn(help='"Allows creating or replacing the contents of the Matching Engine Index.\\nWhen being updated, the existing content of the Index will be replaced by the data\\nfrom the latest contentsDeltaUri.\\nThe string must be a valid Cloud Storage directory path. If this\\nfield is set when calling IndexService.UpdateIndex, then no other\\nIndex field can be also updated as part of the same call.\\nThe expected structure and format of the files this URI points to is\\ndescribed at https://cloud.google.com/vertex-ai/docs/matching-engine/using-matching-engine#input-data-format."', args=[d.arg(name='contentsDeltaUri', type=d.T.string)]),
      withContentsDeltaUri(contentsDeltaUri): { spec+: { metadata+: { contentsDeltaUri: contentsDeltaUri } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#withDescription':: d.fn(help='"The description of the Index."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withDisplayName':: d.fn(help='"The display name of the Index. The name can be up to 128 characters long and can consist of any UTF-8 characters."', args=[d.arg(name='displayName', type=d.T.string)]),
    withDisplayName(displayName): { spec+: { displayName: displayName } },
    '#withIndexUpdateMethod':: d.fn(help='"Immutable. The update method to use with this Index. The value must be the followings. If not set, BATCH_UPDATE will be used by default.\\n* BATCH_UPDATE: user can call indexes.patch with files on Cloud Storage of datapoints to update.\\n* STREAM_UPDATE: user can call indexes.upsertDatapoints/DeleteDatapoints to update the Index and the updates will be applied in corresponding DeployedIndexes in nearly real-time."', args=[d.arg(name='indexUpdateMethod', type=d.T.string)]),
    withIndexUpdateMethod(indexUpdateMethod): { spec+: { indexUpdateMethod: indexUpdateMethod } },
    '#withRegion':: d.fn(help='"Immutable. The region of the index. eg us-central1."', args=[d.arg(name='region', type=d.T.string)]),
    withRegion(region): { spec+: { region: region } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The service-generated name of the resource. Used for acquisition only. Leave unset to create a new resource."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
