{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='alloyDBCluster', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of AlloyDBCluster', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'alloydb.cnrm.cloud.google.com/v1beta1',
    kind: 'AlloyDBCluster',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#automatedBackupPolicy':: d.obj(help='"The automated backup policy for this cluster. AutomatedBackupPolicy is disabled by default."'),
    automatedBackupPolicy: {
      '#encryptionConfig':: d.obj(help='"EncryptionConfig describes the encryption config of a cluster or a backup that is encrypted with a CMEK (customer-managed encryption key)."'),
      encryptionConfig: {
        '#kmsKeyNameRef':: d.obj(help='"(Optional) The fully-qualified resource name of the KMS key. Each Cloud KMS key is regionalized and has the following format: projects/[PROJECT]/locations/[REGION]/keyRings/[RING]/cryptoKeys/[KEY_NAME]."'),
        kmsKeyNameRef: {
          '#withExternal':: d.fn(help='"Allowed value: The `selfLink` field of a `KMSCryptoKey` resource."', args=[d.arg(name='external', type=d.T.string)]),
          withExternal(external): { spec+: { automatedBackupPolicy+: { encryptionConfig+: { kmsKeyNameRef+: { external: external } } } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { automatedBackupPolicy+: { encryptionConfig+: { kmsKeyNameRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { automatedBackupPolicy+: { encryptionConfig+: { kmsKeyNameRef+: { namespace: namespace } } } } },
        },
      },
      '#quantityBasedRetention':: d.obj(help="\"Quantity-based Backup retention policy to retain recent backups. Conflicts with 'time_based_retention', both can't be set together.\""),
      quantityBasedRetention: {
        '#withCount':: d.fn(help='"The number of backups to retain."', args=[d.arg(name='count', type=d.T.integer)]),
        withCount(count): { spec+: { automatedBackupPolicy+: { quantityBasedRetention+: { count: count } } } },
      },
      '#timeBasedRetention':: d.obj(help="\"Time-based Backup retention policy. Conflicts with 'quantity_based_retention', both can't be set together.\""),
      timeBasedRetention: {
        '#withRetentionPeriod':: d.fn(help="\"The retention period.\\nA duration in seconds with up to nine fractional digits, terminated by 's'. Example: \\\"3.5s\\\".\"", args=[d.arg(name='retentionPeriod', type=d.T.string)]),
        withRetentionPeriod(retentionPeriod): { spec+: { automatedBackupPolicy+: { timeBasedRetention+: { retentionPeriod: retentionPeriod } } } },
      },
      '#weeklySchedule':: d.obj(help='"Weekly schedule for the Backup."'),
      weeklySchedule: {
        '#startTimes':: d.obj(help='"The times during the day to start a backup. At least one start time must be provided. The start times are assumed to be in UTC and to be an exact hour (e.g., 04:00:00)."'),
        startTimes: {
          '#withHours':: d.fn(help='"Hours of day in 24 hour format. Should be from 0 to 23. An API may choose to allow the value \\"24:00:00\\" for scenarios like business closing time."', args=[d.arg(name='hours', type=d.T.integer)]),
          withHours(hours): { hours: hours },
          '#withMinutes':: d.fn(help='"Minutes of hour of day. Currently, only the value 0 is supported."', args=[d.arg(name='minutes', type=d.T.integer)]),
          withMinutes(minutes): { minutes: minutes },
          '#withNanos':: d.fn(help='"Fractions of seconds in nanoseconds. Currently, only the value 0 is supported."', args=[d.arg(name='nanos', type=d.T.integer)]),
          withNanos(nanos): { nanos: nanos },
          '#withSeconds':: d.fn(help='"Seconds of minutes of the time. Currently, only the value 0 is supported."', args=[d.arg(name='seconds', type=d.T.integer)]),
          withSeconds(seconds): { seconds: seconds },
        },
        '#withDaysOfWeek':: d.fn(help='"The days of the week to perform a backup. At least one day of the week must be provided. Possible values: [\\"MONDAY\\", \\"TUESDAY\\", \\"WEDNESDAY\\", \\"THURSDAY\\", \\"FRIDAY\\", \\"SATURDAY\\", \\"SUNDAY\\"]."', args=[d.arg(name='daysOfWeek', type=d.T.array)]),
        withDaysOfWeek(daysOfWeek): { spec+: { automatedBackupPolicy+: { weeklySchedule+: { daysOfWeek: if std.isArray(v=daysOfWeek) then daysOfWeek else [daysOfWeek] } } } },
        '#withDaysOfWeekMixin':: d.fn(help='"The days of the week to perform a backup. At least one day of the week must be provided. Possible values: [\\"MONDAY\\", \\"TUESDAY\\", \\"WEDNESDAY\\", \\"THURSDAY\\", \\"FRIDAY\\", \\"SATURDAY\\", \\"SUNDAY\\"]."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='daysOfWeek', type=d.T.array)]),
        withDaysOfWeekMixin(daysOfWeek): { spec+: { automatedBackupPolicy+: { weeklySchedule+: { daysOfWeek+: if std.isArray(v=daysOfWeek) then daysOfWeek else [daysOfWeek] } } } },
        '#withStartTimes':: d.fn(help='"The times during the day to start a backup. At least one start time must be provided. The start times are assumed to be in UTC and to be an exact hour (e.g., 04:00:00)."', args=[d.arg(name='startTimes', type=d.T.array)]),
        withStartTimes(startTimes): { spec+: { automatedBackupPolicy+: { weeklySchedule+: { startTimes: if std.isArray(v=startTimes) then startTimes else [startTimes] } } } },
        '#withStartTimesMixin':: d.fn(help='"The times during the day to start a backup. At least one start time must be provided. The start times are assumed to be in UTC and to be an exact hour (e.g., 04:00:00)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='startTimes', type=d.T.array)]),
        withStartTimesMixin(startTimes): { spec+: { automatedBackupPolicy+: { weeklySchedule+: { startTimes+: if std.isArray(v=startTimes) then startTimes else [startTimes] } } } },
      },
      '#withBackupWindow':: d.fn(help="\"The length of the time window during which a backup can be taken. If a backup does not succeed within this time window, it will be canceled and considered failed.\\n\\nThe backup window must be at least 5 minutes long. There is no upper bound on the window. If not set, it will default to 1 hour.\\n\\nA duration in seconds with up to nine fractional digits, terminated by 's'. Example: \\\"3.5s\\\".\"", args=[d.arg(name='backupWindow', type=d.T.string)]),
      withBackupWindow(backupWindow): { spec+: { automatedBackupPolicy+: { backupWindow: backupWindow } } },
      '#withEnabled':: d.fn(help='"Whether automated backups are enabled."', args=[d.arg(name='enabled', type=d.T.boolean)]),
      withEnabled(enabled): { spec+: { automatedBackupPolicy+: { enabled: enabled } } },
      '#withLabels':: d.fn(help='"Labels to apply to backups created using this configuration."', args=[d.arg(name='labels', type=d.T.object)]),
      withLabels(labels): { spec+: { automatedBackupPolicy+: { labels: labels } } },
      '#withLabelsMixin':: d.fn(help='"Labels to apply to backups created using this configuration."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
      withLabelsMixin(labels): { spec+: { automatedBackupPolicy+: { labels+: labels } } },
      '#withLocation':: d.fn(help='"The location where the backup will be stored. Currently, the only supported option is to store the backup in the same region as the cluster."', args=[d.arg(name='location', type=d.T.string)]),
      withLocation(location): { spec+: { automatedBackupPolicy+: { location: location } } },
    },
    '#continuousBackupConfig':: d.obj(help='"The continuous backup config for this cluster.\\n\\nIf no policy is provided then the default policy will be used. The default policy takes one backup a day and retains backups for 14 days."'),
    continuousBackupConfig: {
      '#encryptionConfig':: d.obj(help='"EncryptionConfig describes the encryption config of a cluster or a backup that is encrypted with a CMEK (customer-managed encryption key)."'),
      encryptionConfig: {
        '#kmsKeyNameRef':: d.obj(help='"(Optional) The fully-qualified resource name of the KMS key. Each Cloud KMS key is regionalized and has the following format: projects/[PROJECT]/locations/[REGION]/keyRings/[RING]/cryptoKeys/[KEY_NAME]."'),
        kmsKeyNameRef: {
          '#withExternal':: d.fn(help='"Allowed value: The `selfLink` field of a `KMSCryptoKey` resource."', args=[d.arg(name='external', type=d.T.string)]),
          withExternal(external): { spec+: { continuousBackupConfig+: { encryptionConfig+: { kmsKeyNameRef+: { external: external } } } } },
          '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
          withName(name): { spec+: { continuousBackupConfig+: { encryptionConfig+: { kmsKeyNameRef+: { name: name } } } } },
          '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
          withNamespace(namespace): { spec+: { continuousBackupConfig+: { encryptionConfig+: { kmsKeyNameRef+: { namespace: namespace } } } } },
        },
      },
      '#withEnabled':: d.fn(help='"Whether continuous backup recovery is enabled. If not set, defaults to true."', args=[d.arg(name='enabled', type=d.T.boolean)]),
      withEnabled(enabled): { spec+: { continuousBackupConfig+: { enabled: enabled } } },
      '#withRecoveryWindowDays':: d.fn(help='"The numbers of days that are eligible to restore from using PITR. To support the entire recovery window, backups and logs are retained for one day more than the recovery window.\\n\\nIf not set, defaults to 14 days."', args=[d.arg(name='recoveryWindowDays', type=d.T.integer)]),
      withRecoveryWindowDays(recoveryWindowDays): { spec+: { continuousBackupConfig+: { recoveryWindowDays: recoveryWindowDays } } },
    },
    '#encryptionConfig':: d.obj(help='"EncryptionConfig describes the encryption config of a cluster or a backup that is encrypted with a CMEK (customer-managed encryption key)."'),
    encryptionConfig: {
      '#kmsKeyNameRef':: d.obj(help='"(Optional) The fully-qualified resource name of the KMS key. Each Cloud KMS key is regionalized and has the following format: projects/[PROJECT]/locations/[REGION]/keyRings/[RING]/cryptoKeys/[KEY_NAME]."'),
      kmsKeyNameRef: {
        '#withExternal':: d.fn(help='"Allowed value: The `selfLink` field of a `KMSCryptoKey` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { encryptionConfig+: { kmsKeyNameRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { encryptionConfig+: { kmsKeyNameRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { encryptionConfig+: { kmsKeyNameRef+: { namespace: namespace } } } },
      },
    },
    '#initialUser':: d.obj(help='"Initial user to setup during cluster creation."'),
    initialUser: {
      '#password':: d.obj(help='"The initial password for the user."'),
      password: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { initialUser+: { password+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { initialUser+: { password+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { initialUser+: { password+: { value: value } } } },
      },
      '#withUser':: d.fn(help='"The database username."', args=[d.arg(name='user', type=d.T.string)]),
      withUser(user): { spec+: { initialUser+: { user: user } } },
    },
    '#maintenanceUpdatePolicy':: d.obj(help='"MaintenanceUpdatePolicy defines the policy for system updates."'),
    maintenanceUpdatePolicy: {
      '#maintenanceWindows':: d.obj(help='"Preferred windows to perform maintenance. Currently limited to 1."'),
      maintenanceWindows: {
        '#startTime':: d.obj(help='"Preferred time to start the maintenance operation on the specified day. Maintenance will start within 1 hour of this time."'),
        startTime: {
          '#withHours':: d.fn(help='"Hours of day in 24 hour format. Should be from 0 to 23."', args=[d.arg(name='hours', type=d.T.integer)]),
          withHours(hours): { startTime+: { hours: hours } },
          '#withMinutes':: d.fn(help='"Minutes of hour of day. Currently, only the value 0 is supported."', args=[d.arg(name='minutes', type=d.T.integer)]),
          withMinutes(minutes): { startTime+: { minutes: minutes } },
          '#withNanos':: d.fn(help='"Fractions of seconds in nanoseconds. Currently, only the value 0 is supported."', args=[d.arg(name='nanos', type=d.T.integer)]),
          withNanos(nanos): { startTime+: { nanos: nanos } },
          '#withSeconds':: d.fn(help='"Seconds of minutes of the time. Currently, only the value 0 is supported."', args=[d.arg(name='seconds', type=d.T.integer)]),
          withSeconds(seconds): { startTime+: { seconds: seconds } },
        },
        '#withDay':: d.fn(help='"Preferred day of the week for maintenance, e.g. MONDAY, TUESDAY, etc. Possible values: [\\"MONDAY\\", \\"TUESDAY\\", \\"WEDNESDAY\\", \\"THURSDAY\\", \\"FRIDAY\\", \\"SATURDAY\\", \\"SUNDAY\\"]."', args=[d.arg(name='day', type=d.T.string)]),
        withDay(day): { day: day },
      },
      '#withMaintenanceWindows':: d.fn(help='"Preferred windows to perform maintenance. Currently limited to 1."', args=[d.arg(name='maintenanceWindows', type=d.T.array)]),
      withMaintenanceWindows(maintenanceWindows): { spec+: { maintenanceUpdatePolicy+: { maintenanceWindows: if std.isArray(v=maintenanceWindows) then maintenanceWindows else [maintenanceWindows] } } },
      '#withMaintenanceWindowsMixin':: d.fn(help='"Preferred windows to perform maintenance. Currently limited to 1."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='maintenanceWindows', type=d.T.array)]),
      withMaintenanceWindowsMixin(maintenanceWindows): { spec+: { maintenanceUpdatePolicy+: { maintenanceWindows+: if std.isArray(v=maintenanceWindows) then maintenanceWindows else [maintenanceWindows] } } },
    },
    '#networkConfig':: d.obj(help='"Metadata related to network configuration."'),
    networkConfig: {
      '#networkRef':: d.obj(help='"(Required) The relative resource name of the VPC network on which\\nthe instance can be accessed. It is specified in the following form:\\nprojects/{project}/global/networks/{network_id}."'),
      networkRef: {
        '#withExternal':: d.fn(help='"Allowed value: string of the format `projects/{{project}}/global/networks/{{value}}`, where {{value}} is the `name` field of a `ComputeNetwork` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { networkConfig+: { networkRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { networkConfig+: { networkRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { networkConfig+: { networkRef+: { namespace: namespace } } } },
      },
      '#withAllocatedIpRange':: d.fn(help='"The name of the allocated IP range for the private IP AlloyDB cluster. For example: \\"google-managed-services-default\\".\\nIf set, the instance IPs for this cluster will be created in the allocated range."', args=[d.arg(name='allocatedIpRange', type=d.T.string)]),
      withAllocatedIpRange(allocatedIpRange): { spec+: { networkConfig+: { allocatedIpRange: allocatedIpRange } } },
    },
    '#networkRef':: d.obj(help='"(Required) The relative resource name of the VPC network on which\\nthe instance can be accessed. It is specified in the following form:\\nprojects/{project}/global/networks/{network_id}."'),
    networkRef: {
      '#withExternal':: d.fn(help='"Allowed value: string of the format `projects/{{project}}/global/networks/{{value}}`, where {{value}} is the `name` field of a `ComputeNetwork` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { networkRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { networkRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { networkRef+: { namespace: namespace } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#restoreBackupSource':: d.obj(help="\"Immutable. The source when restoring from a backup. Conflicts with 'restore_continuous_backup_source', both can't be set together.\""),
    restoreBackupSource: {
      '#backupNameRef':: d.obj(help='"(Required) The name of the backup that this cluster is restored from."'),
      backupNameRef: {
        '#withExternal':: d.fn(help='"Allowed value: The `name` field of an `AlloyDBBackup` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { restoreBackupSource+: { backupNameRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { restoreBackupSource+: { backupNameRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { restoreBackupSource+: { backupNameRef+: { namespace: namespace } } } },
      },
    },
    '#restoreContinuousBackupSource':: d.obj(help="\"Immutable. The source when restoring via point in time recovery (PITR). Conflicts with 'restore_backup_source', both can't be set together.\""),
    restoreContinuousBackupSource: {
      '#clusterRef':: d.obj(help='"(Required) The name of the source cluster that this cluster is restored from."'),
      clusterRef: {
        '#withExternal':: d.fn(help='"Allowed value: The `name` field of an `AlloyDBCluster` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { restoreContinuousBackupSource+: { clusterRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { restoreContinuousBackupSource+: { clusterRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { restoreContinuousBackupSource+: { clusterRef+: { namespace: namespace } } } },
      },
      '#withPointInTime':: d.fn(help='"Immutable. The point in time that this cluster is restored to, in RFC 3339 format."', args=[d.arg(name='pointInTime', type=d.T.string)]),
      withPointInTime(pointInTime): { spec+: { restoreContinuousBackupSource+: { pointInTime: pointInTime } } },
    },
    '#secondaryConfig':: d.obj(help='"Configuration of the secondary cluster for Cross Region Replication. This should be set if and only if the cluster is of type SECONDARY."'),
    secondaryConfig: {
      '#primaryClusterNameRef':: d.obj(help="\"Name of the primary cluster must be in the format\\n'projects/{project}/locations/{location}/clusters/{cluster_id}'\""),
      primaryClusterNameRef: {
        '#withExternal':: d.fn(help='"Allowed value: The `name` field of an `AlloyDBCluster` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { secondaryConfig+: { primaryClusterNameRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { secondaryConfig+: { primaryClusterNameRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { secondaryConfig+: { primaryClusterNameRef+: { namespace: namespace } } } },
      },
    },
    '#withClusterType':: d.fn(help='"The type of cluster. If not set, defaults to PRIMARY. Default value: \\"PRIMARY\\" Possible values: [\\"PRIMARY\\", \\"SECONDARY\\"]."', args=[d.arg(name='clusterType', type=d.T.string)]),
    withClusterType(clusterType): { spec+: { clusterType: clusterType } },
    '#withDeletionPolicy':: d.fn(help='"Policy to determine if the cluster should be deleted forcefully.\\nDeleting a cluster forcefully, deletes the cluster and all its associated instances within the cluster.\\nDeleting a Secondary cluster with a secondary instance REQUIRES setting deletion_policy = \\"FORCE\\" otherwise an error is returned. This is needed as there is no support to delete just the secondary instance, and the only way to delete secondary instance is to delete the associated secondary cluster forcefully which also deletes the secondary instance."', args=[d.arg(name='deletionPolicy', type=d.T.string)]),
    withDeletionPolicy(deletionPolicy): { spec+: { deletionPolicy: deletionPolicy } },
    '#withDisplayName':: d.fn(help='"User-settable and human-readable display name for the Cluster."', args=[d.arg(name='displayName', type=d.T.string)]),
    withDisplayName(displayName): { spec+: { displayName: displayName } },
    '#withLocation':: d.fn(help='"Immutable. The location where the alloydb cluster should reside."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The clusterId of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
