{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='osConfigPatchDeployment', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of OSConfigPatchDeployment', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'osconfig.cnrm.cloud.google.com/v1alpha1',
    kind: 'OSConfigPatchDeployment',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#instanceFilter':: d.obj(help='"Immutable. VM instances to patch."'),
    instanceFilter: {
      '#groupLabels':: d.obj(help='"Immutable. Targets VM instances matching ANY of these GroupLabels. This allows targeting of disparate groups of VM instances."'),
      groupLabels: {
        '#withLabels':: d.fn(help='"Immutable. Compute Engine instance labels that must be present for a VM instance to be targeted by this filter."', args=[d.arg(name='labels', type=d.T.object)]),
        withLabels(labels): { labels: labels },
        '#withLabelsMixin':: d.fn(help='"Immutable. Compute Engine instance labels that must be present for a VM instance to be targeted by this filter."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
        withLabelsMixin(labels): { labels+: labels },
      },
      '#withAll':: d.fn(help='"Immutable. Target all VM instances in the project. If true, no other criteria is permitted."', args=[d.arg(name='all', type=d.T.boolean)]),
      withAll(all): { spec+: { instanceFilter+: { all: all } } },
      '#withGroupLabels':: d.fn(help='"Immutable. Targets VM instances matching ANY of these GroupLabels. This allows targeting of disparate groups of VM instances."', args=[d.arg(name='groupLabels', type=d.T.array)]),
      withGroupLabels(groupLabels): { spec+: { instanceFilter+: { groupLabels: if std.isArray(v=groupLabels) then groupLabels else [groupLabels] } } },
      '#withGroupLabelsMixin':: d.fn(help='"Immutable. Targets VM instances matching ANY of these GroupLabels. This allows targeting of disparate groups of VM instances."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='groupLabels', type=d.T.array)]),
      withGroupLabelsMixin(groupLabels): { spec+: { instanceFilter+: { groupLabels+: if std.isArray(v=groupLabels) then groupLabels else [groupLabels] } } },
      '#withInstanceNamePrefixes':: d.fn(help='"Immutable. Targets VMs whose name starts with one of these prefixes. Similar to labels, this is another way to group\\nVMs when targeting configs, for example prefix=\\"prod-\\"."', args=[d.arg(name='instanceNamePrefixes', type=d.T.array)]),
      withInstanceNamePrefixes(instanceNamePrefixes): { spec+: { instanceFilter+: { instanceNamePrefixes: if std.isArray(v=instanceNamePrefixes) then instanceNamePrefixes else [instanceNamePrefixes] } } },
      '#withInstanceNamePrefixesMixin':: d.fn(help='"Immutable. Targets VMs whose name starts with one of these prefixes. Similar to labels, this is another way to group\\nVMs when targeting configs, for example prefix=\\"prod-\\"."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='instanceNamePrefixes', type=d.T.array)]),
      withInstanceNamePrefixesMixin(instanceNamePrefixes): { spec+: { instanceFilter+: { instanceNamePrefixes+: if std.isArray(v=instanceNamePrefixes) then instanceNamePrefixes else [instanceNamePrefixes] } } },
      '#withInstances':: d.fn(help="\"Immutable. Targets any of the VM instances specified. Instances are specified by their URI in the 'form zones/{{zone}}/instances/{{instance_name}}',\\n'projects/{{project_id}}/zones/{{zone}}/instances/{{instance_name}}', or\\n'https://www.googleapis.com/compute/v1/projects/{{project_id}}/zones/{{zone}}/instances/{{instance_name}}'.\"", args=[d.arg(name='instances', type=d.T.array)]),
      withInstances(instances): { spec+: { instanceFilter+: { instances: if std.isArray(v=instances) then instances else [instances] } } },
      '#withInstancesMixin':: d.fn(help="\"Immutable. Targets any of the VM instances specified. Instances are specified by their URI in the 'form zones/{{zone}}/instances/{{instance_name}}',\\n'projects/{{project_id}}/zones/{{zone}}/instances/{{instance_name}}', or\\n'https://www.googleapis.com/compute/v1/projects/{{project_id}}/zones/{{zone}}/instances/{{instance_name}}'.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='instances', type=d.T.array)]),
      withInstancesMixin(instances): { spec+: { instanceFilter+: { instances+: if std.isArray(v=instances) then instances else [instances] } } },
      '#withZones':: d.fn(help='"Immutable. Targets VM instances in ANY of these zones. Leave empty to target VM instances in any zone."', args=[d.arg(name='zones', type=d.T.array)]),
      withZones(zones): { spec+: { instanceFilter+: { zones: if std.isArray(v=zones) then zones else [zones] } } },
      '#withZonesMixin':: d.fn(help='"Immutable. Targets VM instances in ANY of these zones. Leave empty to target VM instances in any zone."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='zones', type=d.T.array)]),
      withZonesMixin(zones): { spec+: { instanceFilter+: { zones+: if std.isArray(v=zones) then zones else [zones] } } },
    },
    '#oneTimeSchedule':: d.obj(help='"Immutable. Schedule a one-time execution."'),
    oneTimeSchedule: {
      '#withExecuteTime':: d.fn(help='"Immutable. The desired patch job execution time. A timestamp in RFC3339 UTC \\"Zulu\\" format,\\naccurate to nanoseconds. Example: \\"2014-10-02T15:01:23.045123456Z\\"."', args=[d.arg(name='executeTime', type=d.T.string)]),
      withExecuteTime(executeTime): { spec+: { oneTimeSchedule+: { executeTime: executeTime } } },
    },
    '#patchConfig':: d.obj(help='"Immutable. Patch configuration that is applied."'),
    patchConfig: {
      '#apt':: d.obj(help='"Immutable. Apt update settings. Use this setting to override the default apt patch rules."'),
      apt: {
        '#withExcludes':: d.fn(help='"Immutable. List of packages to exclude from update. These packages will be excluded."', args=[d.arg(name='excludes', type=d.T.array)]),
        withExcludes(excludes): { spec+: { patchConfig+: { apt+: { excludes: if std.isArray(v=excludes) then excludes else [excludes] } } } },
        '#withExcludesMixin':: d.fn(help='"Immutable. List of packages to exclude from update. These packages will be excluded."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludes', type=d.T.array)]),
        withExcludesMixin(excludes): { spec+: { patchConfig+: { apt+: { excludes+: if std.isArray(v=excludes) then excludes else [excludes] } } } },
        '#withExclusivePackages':: d.fn(help='"Immutable. An exclusive list of packages to be updated. These are the only packages that will be updated.\\nIf these packages are not installed, they will be ignored. This field cannot be specified with\\nany other patch configuration fields."', args=[d.arg(name='exclusivePackages', type=d.T.array)]),
        withExclusivePackages(exclusivePackages): { spec+: { patchConfig+: { apt+: { exclusivePackages: if std.isArray(v=exclusivePackages) then exclusivePackages else [exclusivePackages] } } } },
        '#withExclusivePackagesMixin':: d.fn(help='"Immutable. An exclusive list of packages to be updated. These are the only packages that will be updated.\\nIf these packages are not installed, they will be ignored. This field cannot be specified with\\nany other patch configuration fields."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='exclusivePackages', type=d.T.array)]),
        withExclusivePackagesMixin(exclusivePackages): { spec+: { patchConfig+: { apt+: { exclusivePackages+: if std.isArray(v=exclusivePackages) then exclusivePackages else [exclusivePackages] } } } },
        '#withType':: d.fn(help='"Immutable. By changing the type to DIST, the patching is performed using apt-get dist-upgrade instead. Possible values: [\\"DIST\\", \\"UPGRADE\\"]."', args=[d.arg(name='type', type=d.T.string)]),
        withType(type): { spec+: { patchConfig+: { apt+: { type: type } } } },
      },
      '#goo':: d.obj(help='"Immutable. goo update settings. Use this setting to override the default goo patch rules."'),
      goo: {
        '#withEnabled':: d.fn(help='"Immutable. goo update settings. Use this setting to override the default goo patch rules."', args=[d.arg(name='enabled', type=d.T.boolean)]),
        withEnabled(enabled): { spec+: { patchConfig+: { goo+: { enabled: enabled } } } },
      },
      '#postStep':: d.obj(help='"Immutable. The ExecStep to run after the patch update."'),
      postStep: {
        '#linuxExecStepConfig':: d.obj(help='"Immutable. The ExecStepConfig for all Linux VMs targeted by the PatchJob."'),
        linuxExecStepConfig: {
          '#gcsObject':: d.obj(help='"Immutable. A Cloud Storage object containing the executable."'),
          gcsObject: {
            '#withBucket':: d.fn(help='"Immutable. Bucket of the Cloud Storage object."', args=[d.arg(name='bucket', type=d.T.string)]),
            withBucket(bucket): { spec+: { patchConfig+: { postStep+: { linuxExecStepConfig+: { gcsObject+: { bucket: bucket } } } } } },
            '#withGenerationNumber':: d.fn(help='"Immutable. Generation number of the Cloud Storage object. This is used to ensure that the ExecStep specified by this PatchJob does not change."', args=[d.arg(name='generationNumber', type=d.T.string)]),
            withGenerationNumber(generationNumber): { spec+: { patchConfig+: { postStep+: { linuxExecStepConfig+: { gcsObject+: { generationNumber: generationNumber } } } } } },
            '#withObject':: d.fn(help='"Immutable. Name of the Cloud Storage object."', args=[d.arg(name='object', type=d.T.string)]),
            withObject(object): { spec+: { patchConfig+: { postStep+: { linuxExecStepConfig+: { gcsObject+: { object: object } } } } } },
          },
          '#withAllowedSuccessCodes':: d.fn(help='"Immutable. Defaults to [0]. A list of possible return values that the execution can return to indicate a success."', args=[d.arg(name='allowedSuccessCodes', type=d.T.array)]),
          withAllowedSuccessCodes(allowedSuccessCodes): { spec+: { patchConfig+: { postStep+: { linuxExecStepConfig+: { allowedSuccessCodes: if std.isArray(v=allowedSuccessCodes) then allowedSuccessCodes else [allowedSuccessCodes] } } } } },
          '#withAllowedSuccessCodesMixin':: d.fn(help='"Immutable. Defaults to [0]. A list of possible return values that the execution can return to indicate a success."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedSuccessCodes', type=d.T.array)]),
          withAllowedSuccessCodesMixin(allowedSuccessCodes): { spec+: { patchConfig+: { postStep+: { linuxExecStepConfig+: { allowedSuccessCodes+: if std.isArray(v=allowedSuccessCodes) then allowedSuccessCodes else [allowedSuccessCodes] } } } } },
          '#withInterpreter':: d.fn(help='"Immutable. The script interpreter to use to run the script. If no interpreter is specified the script will\\nbe executed directly, which will likely only succeed for scripts with shebang lines. Possible values: [\\"SHELL\\", \\"POWERSHELL\\"]."', args=[d.arg(name='interpreter', type=d.T.string)]),
          withInterpreter(interpreter): { spec+: { patchConfig+: { postStep+: { linuxExecStepConfig+: { interpreter: interpreter } } } } },
          '#withLocalPath':: d.fn(help='"Immutable. An absolute path to the executable on the VM."', args=[d.arg(name='localPath', type=d.T.string)]),
          withLocalPath(localPath): { spec+: { patchConfig+: { postStep+: { linuxExecStepConfig+: { localPath: localPath } } } } },
        },
        '#windowsExecStepConfig':: d.obj(help='"Immutable. The ExecStepConfig for all Windows VMs targeted by the PatchJob."'),
        windowsExecStepConfig: {
          '#gcsObject':: d.obj(help='"Immutable. A Cloud Storage object containing the executable."'),
          gcsObject: {
            '#withBucket':: d.fn(help='"Immutable. Bucket of the Cloud Storage object."', args=[d.arg(name='bucket', type=d.T.string)]),
            withBucket(bucket): { spec+: { patchConfig+: { postStep+: { windowsExecStepConfig+: { gcsObject+: { bucket: bucket } } } } } },
            '#withGenerationNumber':: d.fn(help='"Immutable. Generation number of the Cloud Storage object. This is used to ensure that the ExecStep specified by this PatchJob does not change."', args=[d.arg(name='generationNumber', type=d.T.string)]),
            withGenerationNumber(generationNumber): { spec+: { patchConfig+: { postStep+: { windowsExecStepConfig+: { gcsObject+: { generationNumber: generationNumber } } } } } },
            '#withObject':: d.fn(help='"Immutable. Name of the Cloud Storage object."', args=[d.arg(name='object', type=d.T.string)]),
            withObject(object): { spec+: { patchConfig+: { postStep+: { windowsExecStepConfig+: { gcsObject+: { object: object } } } } } },
          },
          '#withAllowedSuccessCodes':: d.fn(help='"Immutable. Defaults to [0]. A list of possible return values that the execution can return to indicate a success."', args=[d.arg(name='allowedSuccessCodes', type=d.T.array)]),
          withAllowedSuccessCodes(allowedSuccessCodes): { spec+: { patchConfig+: { postStep+: { windowsExecStepConfig+: { allowedSuccessCodes: if std.isArray(v=allowedSuccessCodes) then allowedSuccessCodes else [allowedSuccessCodes] } } } } },
          '#withAllowedSuccessCodesMixin':: d.fn(help='"Immutable. Defaults to [0]. A list of possible return values that the execution can return to indicate a success."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedSuccessCodes', type=d.T.array)]),
          withAllowedSuccessCodesMixin(allowedSuccessCodes): { spec+: { patchConfig+: { postStep+: { windowsExecStepConfig+: { allowedSuccessCodes+: if std.isArray(v=allowedSuccessCodes) then allowedSuccessCodes else [allowedSuccessCodes] } } } } },
          '#withInterpreter':: d.fn(help='"Immutable. The script interpreter to use to run the script. If no interpreter is specified the script will\\nbe executed directly, which will likely only succeed for scripts with shebang lines. Possible values: [\\"SHELL\\", \\"POWERSHELL\\"]."', args=[d.arg(name='interpreter', type=d.T.string)]),
          withInterpreter(interpreter): { spec+: { patchConfig+: { postStep+: { windowsExecStepConfig+: { interpreter: interpreter } } } } },
          '#withLocalPath':: d.fn(help='"Immutable. An absolute path to the executable on the VM."', args=[d.arg(name='localPath', type=d.T.string)]),
          withLocalPath(localPath): { spec+: { patchConfig+: { postStep+: { windowsExecStepConfig+: { localPath: localPath } } } } },
        },
      },
      '#preStep':: d.obj(help='"Immutable. The ExecStep to run before the patch update."'),
      preStep: {
        '#linuxExecStepConfig':: d.obj(help='"Immutable. The ExecStepConfig for all Linux VMs targeted by the PatchJob."'),
        linuxExecStepConfig: {
          '#gcsObject':: d.obj(help='"Immutable. A Cloud Storage object containing the executable."'),
          gcsObject: {
            '#withBucket':: d.fn(help='"Immutable. Bucket of the Cloud Storage object."', args=[d.arg(name='bucket', type=d.T.string)]),
            withBucket(bucket): { spec+: { patchConfig+: { preStep+: { linuxExecStepConfig+: { gcsObject+: { bucket: bucket } } } } } },
            '#withGenerationNumber':: d.fn(help='"Immutable. Generation number of the Cloud Storage object. This is used to ensure that the ExecStep specified by this PatchJob does not change."', args=[d.arg(name='generationNumber', type=d.T.string)]),
            withGenerationNumber(generationNumber): { spec+: { patchConfig+: { preStep+: { linuxExecStepConfig+: { gcsObject+: { generationNumber: generationNumber } } } } } },
            '#withObject':: d.fn(help='"Immutable. Name of the Cloud Storage object."', args=[d.arg(name='object', type=d.T.string)]),
            withObject(object): { spec+: { patchConfig+: { preStep+: { linuxExecStepConfig+: { gcsObject+: { object: object } } } } } },
          },
          '#withAllowedSuccessCodes':: d.fn(help='"Immutable. Defaults to [0]. A list of possible return values that the execution can return to indicate a success."', args=[d.arg(name='allowedSuccessCodes', type=d.T.array)]),
          withAllowedSuccessCodes(allowedSuccessCodes): { spec+: { patchConfig+: { preStep+: { linuxExecStepConfig+: { allowedSuccessCodes: if std.isArray(v=allowedSuccessCodes) then allowedSuccessCodes else [allowedSuccessCodes] } } } } },
          '#withAllowedSuccessCodesMixin':: d.fn(help='"Immutable. Defaults to [0]. A list of possible return values that the execution can return to indicate a success."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedSuccessCodes', type=d.T.array)]),
          withAllowedSuccessCodesMixin(allowedSuccessCodes): { spec+: { patchConfig+: { preStep+: { linuxExecStepConfig+: { allowedSuccessCodes+: if std.isArray(v=allowedSuccessCodes) then allowedSuccessCodes else [allowedSuccessCodes] } } } } },
          '#withInterpreter':: d.fn(help='"Immutable. The script interpreter to use to run the script. If no interpreter is specified the script will\\nbe executed directly, which will likely only succeed for scripts with shebang lines. Possible values: [\\"SHELL\\", \\"POWERSHELL\\"]."', args=[d.arg(name='interpreter', type=d.T.string)]),
          withInterpreter(interpreter): { spec+: { patchConfig+: { preStep+: { linuxExecStepConfig+: { interpreter: interpreter } } } } },
          '#withLocalPath':: d.fn(help='"Immutable. An absolute path to the executable on the VM."', args=[d.arg(name='localPath', type=d.T.string)]),
          withLocalPath(localPath): { spec+: { patchConfig+: { preStep+: { linuxExecStepConfig+: { localPath: localPath } } } } },
        },
        '#windowsExecStepConfig':: d.obj(help='"Immutable. The ExecStepConfig for all Windows VMs targeted by the PatchJob."'),
        windowsExecStepConfig: {
          '#gcsObject':: d.obj(help='"Immutable. A Cloud Storage object containing the executable."'),
          gcsObject: {
            '#withBucket':: d.fn(help='"Immutable. Bucket of the Cloud Storage object."', args=[d.arg(name='bucket', type=d.T.string)]),
            withBucket(bucket): { spec+: { patchConfig+: { preStep+: { windowsExecStepConfig+: { gcsObject+: { bucket: bucket } } } } } },
            '#withGenerationNumber':: d.fn(help='"Immutable. Generation number of the Cloud Storage object. This is used to ensure that the ExecStep specified by this PatchJob does not change."', args=[d.arg(name='generationNumber', type=d.T.string)]),
            withGenerationNumber(generationNumber): { spec+: { patchConfig+: { preStep+: { windowsExecStepConfig+: { gcsObject+: { generationNumber: generationNumber } } } } } },
            '#withObject':: d.fn(help='"Immutable. Name of the Cloud Storage object."', args=[d.arg(name='object', type=d.T.string)]),
            withObject(object): { spec+: { patchConfig+: { preStep+: { windowsExecStepConfig+: { gcsObject+: { object: object } } } } } },
          },
          '#withAllowedSuccessCodes':: d.fn(help='"Immutable. Defaults to [0]. A list of possible return values that the execution can return to indicate a success."', args=[d.arg(name='allowedSuccessCodes', type=d.T.array)]),
          withAllowedSuccessCodes(allowedSuccessCodes): { spec+: { patchConfig+: { preStep+: { windowsExecStepConfig+: { allowedSuccessCodes: if std.isArray(v=allowedSuccessCodes) then allowedSuccessCodes else [allowedSuccessCodes] } } } } },
          '#withAllowedSuccessCodesMixin':: d.fn(help='"Immutable. Defaults to [0]. A list of possible return values that the execution can return to indicate a success."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowedSuccessCodes', type=d.T.array)]),
          withAllowedSuccessCodesMixin(allowedSuccessCodes): { spec+: { patchConfig+: { preStep+: { windowsExecStepConfig+: { allowedSuccessCodes+: if std.isArray(v=allowedSuccessCodes) then allowedSuccessCodes else [allowedSuccessCodes] } } } } },
          '#withInterpreter':: d.fn(help='"Immutable. The script interpreter to use to run the script. If no interpreter is specified the script will\\nbe executed directly, which will likely only succeed for scripts with shebang lines. Possible values: [\\"SHELL\\", \\"POWERSHELL\\"]."', args=[d.arg(name='interpreter', type=d.T.string)]),
          withInterpreter(interpreter): { spec+: { patchConfig+: { preStep+: { windowsExecStepConfig+: { interpreter: interpreter } } } } },
          '#withLocalPath':: d.fn(help='"Immutable. An absolute path to the executable on the VM."', args=[d.arg(name='localPath', type=d.T.string)]),
          withLocalPath(localPath): { spec+: { patchConfig+: { preStep+: { windowsExecStepConfig+: { localPath: localPath } } } } },
        },
      },
      '#windowsUpdate':: d.obj(help='"Immutable. Windows update settings. Use this setting to override the default Windows patch rules."'),
      windowsUpdate: {
        '#withClassifications':: d.fn(help='"Immutable. Only apply updates of these windows update classifications. If empty, all updates are applied. Possible values: [\\"CRITICAL\\", \\"SECURITY\\", \\"DEFINITION\\", \\"DRIVER\\", \\"FEATURE_PACK\\", \\"SERVICE_PACK\\", \\"TOOL\\", \\"UPDATE_ROLLUP\\", \\"UPDATE\\"]."', args=[d.arg(name='classifications', type=d.T.array)]),
        withClassifications(classifications): { spec+: { patchConfig+: { windowsUpdate+: { classifications: if std.isArray(v=classifications) then classifications else [classifications] } } } },
        '#withClassificationsMixin':: d.fn(help='"Immutable. Only apply updates of these windows update classifications. If empty, all updates are applied. Possible values: [\\"CRITICAL\\", \\"SECURITY\\", \\"DEFINITION\\", \\"DRIVER\\", \\"FEATURE_PACK\\", \\"SERVICE_PACK\\", \\"TOOL\\", \\"UPDATE_ROLLUP\\", \\"UPDATE\\"]."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='classifications', type=d.T.array)]),
        withClassificationsMixin(classifications): { spec+: { patchConfig+: { windowsUpdate+: { classifications+: if std.isArray(v=classifications) then classifications else [classifications] } } } },
        '#withExcludes':: d.fn(help='"Immutable. List of KBs to exclude from update."', args=[d.arg(name='excludes', type=d.T.array)]),
        withExcludes(excludes): { spec+: { patchConfig+: { windowsUpdate+: { excludes: if std.isArray(v=excludes) then excludes else [excludes] } } } },
        '#withExcludesMixin':: d.fn(help='"Immutable. List of KBs to exclude from update."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludes', type=d.T.array)]),
        withExcludesMixin(excludes): { spec+: { patchConfig+: { windowsUpdate+: { excludes+: if std.isArray(v=excludes) then excludes else [excludes] } } } },
        '#withExclusivePatches':: d.fn(help='"Immutable. An exclusive list of kbs to be updated. These are the only patches that will be updated.\\nThis field must not be used with other patch configurations."', args=[d.arg(name='exclusivePatches', type=d.T.array)]),
        withExclusivePatches(exclusivePatches): { spec+: { patchConfig+: { windowsUpdate+: { exclusivePatches: if std.isArray(v=exclusivePatches) then exclusivePatches else [exclusivePatches] } } } },
        '#withExclusivePatchesMixin':: d.fn(help='"Immutable. An exclusive list of kbs to be updated. These are the only patches that will be updated.\\nThis field must not be used with other patch configurations."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='exclusivePatches', type=d.T.array)]),
        withExclusivePatchesMixin(exclusivePatches): { spec+: { patchConfig+: { windowsUpdate+: { exclusivePatches+: if std.isArray(v=exclusivePatches) then exclusivePatches else [exclusivePatches] } } } },
      },
      '#withMigInstancesAllowed':: d.fn(help='"Immutable. Allows the patch job to run on Managed instance groups (MIGs)."', args=[d.arg(name='migInstancesAllowed', type=d.T.boolean)]),
      withMigInstancesAllowed(migInstancesAllowed): { spec+: { patchConfig+: { migInstancesAllowed: migInstancesAllowed } } },
      '#withRebootConfig':: d.fn(help='"Immutable. Post-patch reboot settings. Possible values: [\\"DEFAULT\\", \\"ALWAYS\\", \\"NEVER\\"]."', args=[d.arg(name='rebootConfig', type=d.T.string)]),
      withRebootConfig(rebootConfig): { spec+: { patchConfig+: { rebootConfig: rebootConfig } } },
      '#yum':: d.obj(help='"Immutable. Yum update settings. Use this setting to override the default yum patch rules."'),
      yum: {
        '#withExcludes':: d.fn(help='"Immutable. List of packages to exclude from update. These packages will be excluded."', args=[d.arg(name='excludes', type=d.T.array)]),
        withExcludes(excludes): { spec+: { patchConfig+: { yum+: { excludes: if std.isArray(v=excludes) then excludes else [excludes] } } } },
        '#withExcludesMixin':: d.fn(help='"Immutable. List of packages to exclude from update. These packages will be excluded."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludes', type=d.T.array)]),
        withExcludesMixin(excludes): { spec+: { patchConfig+: { yum+: { excludes+: if std.isArray(v=excludes) then excludes else [excludes] } } } },
        '#withExclusivePackages':: d.fn(help='"Immutable. An exclusive list of packages to be updated. These are the only packages that will be updated.\\nIf these packages are not installed, they will be ignored. This field cannot be specified with\\nany other patch configuration fields."', args=[d.arg(name='exclusivePackages', type=d.T.array)]),
        withExclusivePackages(exclusivePackages): { spec+: { patchConfig+: { yum+: { exclusivePackages: if std.isArray(v=exclusivePackages) then exclusivePackages else [exclusivePackages] } } } },
        '#withExclusivePackagesMixin':: d.fn(help='"Immutable. An exclusive list of packages to be updated. These are the only packages that will be updated.\\nIf these packages are not installed, they will be ignored. This field cannot be specified with\\nany other patch configuration fields."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='exclusivePackages', type=d.T.array)]),
        withExclusivePackagesMixin(exclusivePackages): { spec+: { patchConfig+: { yum+: { exclusivePackages+: if std.isArray(v=exclusivePackages) then exclusivePackages else [exclusivePackages] } } } },
        '#withMinimal':: d.fn(help='"Immutable. Will cause patch to run yum update-minimal instead."', args=[d.arg(name='minimal', type=d.T.boolean)]),
        withMinimal(minimal): { spec+: { patchConfig+: { yum+: { minimal: minimal } } } },
        '#withSecurity':: d.fn(help='"Immutable. Adds the --security flag to yum update. Not supported on all platforms."', args=[d.arg(name='security', type=d.T.boolean)]),
        withSecurity(security): { spec+: { patchConfig+: { yum+: { security: security } } } },
      },
      '#zypper':: d.obj(help='"Immutable. zypper update settings. Use this setting to override the default zypper patch rules."'),
      zypper: {
        '#withCategories':: d.fn(help='"Immutable. Install only patches with these categories. Common categories include security, recommended, and feature."', args=[d.arg(name='categories', type=d.T.array)]),
        withCategories(categories): { spec+: { patchConfig+: { zypper+: { categories: if std.isArray(v=categories) then categories else [categories] } } } },
        '#withCategoriesMixin':: d.fn(help='"Immutable. Install only patches with these categories. Common categories include security, recommended, and feature."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='categories', type=d.T.array)]),
        withCategoriesMixin(categories): { spec+: { patchConfig+: { zypper+: { categories+: if std.isArray(v=categories) then categories else [categories] } } } },
        '#withExcludes':: d.fn(help='"Immutable. List of packages to exclude from update."', args=[d.arg(name='excludes', type=d.T.array)]),
        withExcludes(excludes): { spec+: { patchConfig+: { zypper+: { excludes: if std.isArray(v=excludes) then excludes else [excludes] } } } },
        '#withExcludesMixin':: d.fn(help='"Immutable. List of packages to exclude from update."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='excludes', type=d.T.array)]),
        withExcludesMixin(excludes): { spec+: { patchConfig+: { zypper+: { excludes+: if std.isArray(v=excludes) then excludes else [excludes] } } } },
        '#withExclusivePatches':: d.fn(help="\"Immutable. An exclusive list of patches to be updated. These are the only patches that will be installed using 'zypper patch patch:' command.\\nThis field must not be used with any other patch configuration fields.\"", args=[d.arg(name='exclusivePatches', type=d.T.array)]),
        withExclusivePatches(exclusivePatches): { spec+: { patchConfig+: { zypper+: { exclusivePatches: if std.isArray(v=exclusivePatches) then exclusivePatches else [exclusivePatches] } } } },
        '#withExclusivePatchesMixin':: d.fn(help="\"Immutable. An exclusive list of patches to be updated. These are the only patches that will be installed using 'zypper patch patch:' command.\\nThis field must not be used with any other patch configuration fields.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='exclusivePatches', type=d.T.array)]),
        withExclusivePatchesMixin(exclusivePatches): { spec+: { patchConfig+: { zypper+: { exclusivePatches+: if std.isArray(v=exclusivePatches) then exclusivePatches else [exclusivePatches] } } } },
        '#withSeverities':: d.fn(help='"Immutable. Install only patches with these severities. Common severities include critical, important, moderate, and low."', args=[d.arg(name='severities', type=d.T.array)]),
        withSeverities(severities): { spec+: { patchConfig+: { zypper+: { severities: if std.isArray(v=severities) then severities else [severities] } } } },
        '#withSeveritiesMixin':: d.fn(help='"Immutable. Install only patches with these severities. Common severities include critical, important, moderate, and low."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='severities', type=d.T.array)]),
        withSeveritiesMixin(severities): { spec+: { patchConfig+: { zypper+: { severities+: if std.isArray(v=severities) then severities else [severities] } } } },
        '#withWithOptional':: d.fn(help='"Immutable. Adds the --with-optional flag to zypper patch."', args=[d.arg(name='withOptional', type=d.T.boolean)]),
        withWithOptional(withOptional): { spec+: { patchConfig+: { zypper+: { withOptional: withOptional } } } },
        '#withWithUpdate':: d.fn(help='"Immutable. Adds the --with-update flag, to zypper patch."', args=[d.arg(name='withUpdate', type=d.T.boolean)]),
        withWithUpdate(withUpdate): { spec+: { patchConfig+: { zypper+: { withUpdate: withUpdate } } } },
      },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#recurringSchedule':: d.obj(help='"Immutable. Schedule recurring executions."'),
    recurringSchedule: {
      '#monthly':: d.obj(help='"Immutable. Schedule with monthly executions."'),
      monthly: {
        '#weekDayOfMonth':: d.obj(help='"Immutable. Week day in a month."'),
        weekDayOfMonth: {
          '#withDayOfWeek':: d.fn(help='"Immutable. A day of the week. Possible values: [\\"MONDAY\\", \\"TUESDAY\\", \\"WEDNESDAY\\", \\"THURSDAY\\", \\"FRIDAY\\", \\"SATURDAY\\", \\"SUNDAY\\"]."', args=[d.arg(name='dayOfWeek', type=d.T.string)]),
          withDayOfWeek(dayOfWeek): { spec+: { recurringSchedule+: { monthly+: { weekDayOfMonth+: { dayOfWeek: dayOfWeek } } } } },
          '#withWeekOrdinal':: d.fn(help='"Immutable. Week number in a month. 1-4 indicates the 1st to 4th week of the month. -1 indicates the last week of the month."', args=[d.arg(name='weekOrdinal', type=d.T.integer)]),
          withWeekOrdinal(weekOrdinal): { spec+: { recurringSchedule+: { monthly+: { weekDayOfMonth+: { weekOrdinal: weekOrdinal } } } } },
        },
        '#withMonthDay':: d.fn(help='"Immutable. One day of the month. 1-31 indicates the 1st to the 31st day. -1 indicates the last day of the month.\\nMonths without the target day will be skipped. For example, a schedule to run \\"every month on the 31st\\"\\nwill not run in February, April, June, etc."', args=[d.arg(name='monthDay', type=d.T.integer)]),
        withMonthDay(monthDay): { spec+: { recurringSchedule+: { monthly+: { monthDay: monthDay } } } },
      },
      '#timeOfDay':: d.obj(help='"Immutable. Time of the day to run a recurring deployment."'),
      timeOfDay: {
        '#withHours':: d.fn(help='"Immutable. Hours of day in 24 hour format. Should be from 0 to 23.\\nAn API may choose to allow the value \\"24:00:00\\" for scenarios like business closing time."', args=[d.arg(name='hours', type=d.T.integer)]),
        withHours(hours): { spec+: { recurringSchedule+: { timeOfDay+: { hours: hours } } } },
        '#withMinutes':: d.fn(help='"Immutable. Minutes of hour of day. Must be from 0 to 59."', args=[d.arg(name='minutes', type=d.T.integer)]),
        withMinutes(minutes): { spec+: { recurringSchedule+: { timeOfDay+: { minutes: minutes } } } },
        '#withNanos':: d.fn(help='"Immutable. Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999."', args=[d.arg(name='nanos', type=d.T.integer)]),
        withNanos(nanos): { spec+: { recurringSchedule+: { timeOfDay+: { nanos: nanos } } } },
        '#withSeconds':: d.fn(help='"Immutable. Seconds of minutes of the time. Must normally be from 0 to 59. An API may allow the value 60 if it allows leap-seconds."', args=[d.arg(name='seconds', type=d.T.integer)]),
        withSeconds(seconds): { spec+: { recurringSchedule+: { timeOfDay+: { seconds: seconds } } } },
      },
      '#timeZone':: d.obj(help='"Immutable. Defines the time zone that timeOfDay is relative to. The rules for daylight saving time are\\ndetermined by the chosen time zone."'),
      timeZone: {
        '#withId':: d.fn(help='"Immutable. IANA Time Zone Database time zone, e.g. \\"America/New_York\\"."', args=[d.arg(name='id', type=d.T.string)]),
        withId(id): { spec+: { recurringSchedule+: { timeZone+: { id: id } } } },
        '#withVersion':: d.fn(help='"Immutable. IANA Time Zone Database version number, e.g. \\"2019a\\"."', args=[d.arg(name='version', type=d.T.string)]),
        withVersion(version): { spec+: { recurringSchedule+: { timeZone+: { version: version } } } },
      },
      '#weekly':: d.obj(help='"Immutable. Schedule with weekly executions."'),
      weekly: {
        '#withDayOfWeek':: d.fn(help='"Immutable. IANA Time Zone Database time zone, e.g. \\"America/New_York\\". Possible values: [\\"MONDAY\\", \\"TUESDAY\\", \\"WEDNESDAY\\", \\"THURSDAY\\", \\"FRIDAY\\", \\"SATURDAY\\", \\"SUNDAY\\"]."', args=[d.arg(name='dayOfWeek', type=d.T.string)]),
        withDayOfWeek(dayOfWeek): { spec+: { recurringSchedule+: { weekly+: { dayOfWeek: dayOfWeek } } } },
      },
      '#withEndTime':: d.fn(help='"Immutable. The end time at which a recurring patch deployment schedule is no longer active.\\nA timestamp in RFC3339 UTC \\"Zulu\\" format, accurate to nanoseconds. Example: \\"2014-10-02T15:01:23.045123456Z\\"."', args=[d.arg(name='endTime', type=d.T.string)]),
      withEndTime(endTime): { spec+: { recurringSchedule+: { endTime: endTime } } },
      '#withLastExecuteTime':: d.fn(help='"The time the last patch job ran successfully.\\nA timestamp in RFC3339 UTC \\"Zulu\\" format, accurate to nanoseconds. Example: \\"2014-10-02T15:01:23.045123456Z\\"."', args=[d.arg(name='lastExecuteTime', type=d.T.string)]),
      withLastExecuteTime(lastExecuteTime): { spec+: { recurringSchedule+: { lastExecuteTime: lastExecuteTime } } },
      '#withNextExecuteTime':: d.fn(help='"The time the next patch job is scheduled to run.\\nA timestamp in RFC3339 UTC \\"Zulu\\" format, accurate to nanoseconds. Example: \\"2014-10-02T15:01:23.045123456Z\\"."', args=[d.arg(name='nextExecuteTime', type=d.T.string)]),
      withNextExecuteTime(nextExecuteTime): { spec+: { recurringSchedule+: { nextExecuteTime: nextExecuteTime } } },
      '#withStartTime':: d.fn(help='"Immutable. The time that the recurring schedule becomes effective. Defaults to createTime of the patch deployment.\\nA timestamp in RFC3339 UTC \\"Zulu\\" format, accurate to nanoseconds. Example: \\"2014-10-02T15:01:23.045123456Z\\"."', args=[d.arg(name='startTime', type=d.T.string)]),
      withStartTime(startTime): { spec+: { recurringSchedule+: { startTime: startTime } } },
    },
    '#rollout':: d.obj(help='"Immutable. Rollout strategy of the patch job."'),
    rollout: {
      '#disruptionBudget':: d.obj(help='"Immutable. The maximum number (or percentage) of VMs per zone to disrupt at any given moment. The number of VMs calculated from multiplying the percentage by the total number of VMs in a zone is rounded up.\\nDuring patching, a VM is considered disrupted from the time the agent is notified to begin until patching has completed. This disruption time includes the time to complete reboot and any post-patch steps.\\nA VM contributes to the disruption budget if its patching operation fails either when applying the patches, running pre or post patch steps, or if it fails to respond with a success notification before timing out. VMs that are not running or do not have an active agent do not count toward this disruption budget.\\nFor zone-by-zone rollouts, if the disruption budget in a zone is exceeded, the patch job stops, because continuing to the next zone requires completion of the patch process in the previous zone.\\nFor example, if the disruption budget has a fixed value of 10, and 8 VMs fail to patch in the current zone, the patch job continues to patch 2 VMs at a time until the zone is completed. When that zone is completed successfully, patching begins with 10 VMs at a time in the next zone. If 10 VMs in the next zone fail to patch, the patch job stops."'),
      disruptionBudget: {
        '#withFixed':: d.fn(help='"Immutable. Specifies a fixed value."', args=[d.arg(name='fixed', type=d.T.integer)]),
        withFixed(fixed): { spec+: { rollout+: { disruptionBudget+: { fixed: fixed } } } },
        '#withPercentage':: d.fn(help='"Immutable. Specifies the relative value defined as a percentage, which will be multiplied by a reference value."', args=[d.arg(name='percentage', type=d.T.integer)]),
        withPercentage(percentage): { spec+: { rollout+: { disruptionBudget+: { percentage: percentage } } } },
      },
      '#withMode':: d.fn(help='"Immutable. Mode of the patch rollout. Possible values: [\\"ZONE_BY_ZONE\\", \\"CONCURRENT_ZONES\\"]."', args=[d.arg(name='mode', type=d.T.string)]),
      withMode(mode): { spec+: { rollout+: { mode: mode } } },
    },
    '#withDescription':: d.fn(help='"Immutable. Description of the patch deployment. Length of the description is limited to 1024 characters."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withDuration':: d.fn(help="\"Immutable. Duration of the patch. After the duration ends, the patch times out.\\nA duration in seconds with up to nine fractional digits, terminated by 's'. Example: \\\"3.5s\\\".\"", args=[d.arg(name='duration', type=d.T.string)]),
    withDuration(duration): { spec+: { duration: duration } },
    '#withPatchDeploymentId':: d.fn(help='"Immutable. A name for the patch deployment in the project. When creating a name the following rules apply:\\n* Must contain only lowercase letters, numbers, and hyphens.\\n* Must start with a letter.\\n* Must be between 1-63 characters.\\n* Must end with a number or a letter.\\n* Must be unique within the project."', args=[d.arg(name='patchDeploymentId', type=d.T.string)]),
    withPatchDeploymentId(patchDeploymentId): { spec+: { patchDeploymentId: patchDeploymentId } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The service-generated name of the resource. Used for acquisition only. Leave unset to create a new resource."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
