{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='networkManagementConnectivityTest', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of NetworkManagementConnectivityTest', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'networkmanagement.cnrm.cloud.google.com/v1alpha1',
    kind: 'NetworkManagementConnectivityTest',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#destination':: d.obj(help="\"Required. Destination specification of the Connectivity Test.\\n\\nYou can use a combination of destination IP address, Compute\\nEngine VM instance, or VPC network to uniquely identify the\\ndestination location.\\n\\nEven if the destination IP address is not unique, the source IP\\nlocation is unique. Usually, the analysis can infer the destination\\nendpoint from route information.\\n\\nIf the destination you specify is a VM instance and the instance has\\nmultiple network interfaces, then you must also specify either a\\ndestination IP address or VPC network to identify the destination\\ninterface.\\n\\nA reachability analysis proceeds even if the destination location\\nis ambiguous. However, the result can include endpoints that you\\ndon't intend to test.\""),
    destination: {
      '#withInstance':: d.fn(help='"A Compute Engine instance URI."', args=[d.arg(name='instance', type=d.T.string)]),
      withInstance(instance): { spec+: { destination+: { instance: instance } } },
      '#withIpAddress':: d.fn(help="\"The IP address of the endpoint, which can be an external or\\ninternal IP. An IPv6 address is only allowed when the test's\\ndestination is a global load balancer VIP.\"", args=[d.arg(name='ipAddress', type=d.T.string)]),
      withIpAddress(ipAddress): { spec+: { destination+: { ipAddress: ipAddress } } },
      '#withNetwork':: d.fn(help='"A Compute Engine network URI."', args=[d.arg(name='network', type=d.T.string)]),
      withNetwork(network): { spec+: { destination+: { network: network } } },
      '#withPort':: d.fn(help='"The IP protocol port of the endpoint. Only applicable when\\nprotocol is TCP or UDP."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { destination+: { port: port } } },
      '#withProjectId':: d.fn(help='"Project ID where the endpoint is located. The Project ID can be\\nderived from the URI if you provide a VM instance or network URI.\\nThe following are two cases where you must provide the project ID:\\n1. Only the IP address is specified, and the IP address is within\\na GCP project. 2. When you are using Shared VPC and the IP address\\nthat you provide is from the service project. In this case, the\\nnetwork that the IP address resides in is defined in the host\\nproject."', args=[d.arg(name='projectId', type=d.T.string)]),
      withProjectId(projectId): { spec+: { destination+: { projectId: projectId } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#source':: d.obj(help="\"Required. Source specification of the Connectivity Test.\\n\\nYou can use a combination of source IP address, virtual machine\\n(VM) instance, or Compute Engine network to uniquely identify the\\nsource location.\\n\\nExamples: If the source IP address is an internal IP address within\\na Google Cloud Virtual Private Cloud (VPC) network, then you must\\nalso specify the VPC network. Otherwise, specify the VM instance,\\nwhich already contains its internal IP address and VPC network\\ninformation.\\n\\nIf the source of the test is within an on-premises network, then\\nyou must provide the destination VPC network.\\n\\nIf the source endpoint is a Compute Engine VM instance with multiple\\nnetwork interfaces, the instance itself is not sufficient to\\nidentify the endpoint. So, you must also specify the source IP\\naddress or VPC network.\\n\\nA reachability analysis proceeds even if the source location is\\nambiguous. However, the test result may include endpoints that\\nyou don't intend to test.\""),
    source: {
      '#withInstance':: d.fn(help='"A Compute Engine instance URI."', args=[d.arg(name='instance', type=d.T.string)]),
      withInstance(instance): { spec+: { source+: { instance: instance } } },
      '#withIpAddress':: d.fn(help="\"The IP address of the endpoint, which can be an external or\\ninternal IP. An IPv6 address is only allowed when the test's\\ndestination is a global load balancer VIP.\"", args=[d.arg(name='ipAddress', type=d.T.string)]),
      withIpAddress(ipAddress): { spec+: { source+: { ipAddress: ipAddress } } },
      '#withNetwork':: d.fn(help='"A Compute Engine network URI."', args=[d.arg(name='network', type=d.T.string)]),
      withNetwork(network): { spec+: { source+: { network: network } } },
      '#withNetworkType':: d.fn(help='"Type of the network where the endpoint is located. Possible values: [\\"GCP_NETWORK\\", \\"NON_GCP_NETWORK\\"]."', args=[d.arg(name='networkType', type=d.T.string)]),
      withNetworkType(networkType): { spec+: { source+: { networkType: networkType } } },
      '#withPort':: d.fn(help='"The IP protocol port of the endpoint. Only applicable when\\nprotocol is TCP or UDP."', args=[d.arg(name='port', type=d.T.integer)]),
      withPort(port): { spec+: { source+: { port: port } } },
      '#withProjectId':: d.fn(help='"Project ID where the endpoint is located. The Project ID can be\\nderived from the URI if you provide a VM instance or network URI.\\nThe following are two cases where you must provide the project ID:\\n\\n1. Only the IP address is specified, and the IP address is\\n   within a GCP project.\\n2. When you are using Shared VPC and the IP address\\n   that you provide is from the service project. In this case,\\n   the network that the IP address resides in is defined in the\\n   host project."', args=[d.arg(name='projectId', type=d.T.string)]),
      withProjectId(projectId): { spec+: { source+: { projectId: projectId } } },
    },
    '#withDescription':: d.fn(help='"The user-supplied description of the Connectivity Test.\\nMaximum of 512 characters."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withProtocol':: d.fn(help='"IP Protocol of the test. When not provided, \\"TCP\\" is assumed."', args=[d.arg(name='protocol', type=d.T.string)]),
    withProtocol(protocol): { spec+: { protocol: protocol } },
    '#withRelatedProjects':: d.fn(help='"Other projects that may be relevant for reachability analysis.\\nThis is applicable to scenarios where a test can cross project\\nboundaries."', args=[d.arg(name='relatedProjects', type=d.T.array)]),
    withRelatedProjects(relatedProjects): { spec+: { relatedProjects: if std.isArray(v=relatedProjects) then relatedProjects else [relatedProjects] } },
    '#withRelatedProjectsMixin':: d.fn(help='"Other projects that may be relevant for reachability analysis.\\nThis is applicable to scenarios where a test can cross project\\nboundaries."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='relatedProjects', type=d.T.array)]),
    withRelatedProjectsMixin(relatedProjects): { spec+: { relatedProjects+: if std.isArray(v=relatedProjects) then relatedProjects else [relatedProjects] } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
