{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='privilegedAccessManagerEntitlement', url='', help='"PrivilegedAccessManagerEntitlement is the Schema for the PrivilegedAccessManagerEntitlement API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of PrivilegedAccessManagerEntitlement', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'privilegedaccessmanager.cnrm.cloud.google.com/v1alpha1',
    kind: 'PrivilegedAccessManagerEntitlement',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"PrivilegedAccessManagerEntitlementSpec defines the desired state of PrivilegedAccessManagerEntitlement."'),
  spec: {
    '#additionalNotificationTargets':: d.obj(help='"Optional. Additional email addresses to be notified based on actions taken."'),
    additionalNotificationTargets: {
      '#withAdminEmailRecipients':: d.fn(help='"Optional. Additional email addresses to be notified when a principal (requester) is granted access."', args=[d.arg(name='adminEmailRecipients', type=d.T.array)]),
      withAdminEmailRecipients(adminEmailRecipients): { spec+: { additionalNotificationTargets+: { adminEmailRecipients: if std.isArray(v=adminEmailRecipients) then adminEmailRecipients else [adminEmailRecipients] } } },
      '#withAdminEmailRecipientsMixin':: d.fn(help='"Optional. Additional email addresses to be notified when a principal (requester) is granted access."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='adminEmailRecipients', type=d.T.array)]),
      withAdminEmailRecipientsMixin(adminEmailRecipients): { spec+: { additionalNotificationTargets+: { adminEmailRecipients+: if std.isArray(v=adminEmailRecipients) then adminEmailRecipients else [adminEmailRecipients] } } },
      '#withRequesterEmailRecipients':: d.fn(help='"Optional. Additional email address to be notified about an eligible entitlement."', args=[d.arg(name='requesterEmailRecipients', type=d.T.array)]),
      withRequesterEmailRecipients(requesterEmailRecipients): { spec+: { additionalNotificationTargets+: { requesterEmailRecipients: if std.isArray(v=requesterEmailRecipients) then requesterEmailRecipients else [requesterEmailRecipients] } } },
      '#withRequesterEmailRecipientsMixin':: d.fn(help='"Optional. Additional email address to be notified about an eligible entitlement."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='requesterEmailRecipients', type=d.T.array)]),
      withRequesterEmailRecipientsMixin(requesterEmailRecipients): { spec+: { additionalNotificationTargets+: { requesterEmailRecipients+: if std.isArray(v=requesterEmailRecipients) then requesterEmailRecipients else [requesterEmailRecipients] } } },
    },
    '#approvalWorkflow':: d.obj(help='"Optional. The approvals needed before access are granted to a requester. No approvals are needed if this field is null."'),
    approvalWorkflow: {
      '#manualApprovals':: d.obj(help='"An approval workflow where users designated as approvers review and act on the grants."'),
      manualApprovals: {
        '#steps':: d.obj(help='"Optional. List of approval steps in this workflow. These steps are followed in the specified order sequentially. Only 1 step is supported."'),
        steps: {
          '#approvers':: d.obj(help='"Optional. The potential set of approvers in this step. This list must contain at most one entry."'),
          approvers: {
            '#withPrincipals':: d.fn(help='"Optional. Users who are allowed for the operation. Each entry should be a valid v1 IAM principal identifier. The format for these is documented at: https://cloud.google.com/iam/docs/principal-identifiers#v1"', args=[d.arg(name='principals', type=d.T.array)]),
            withPrincipals(principals): { principals: if std.isArray(v=principals) then principals else [principals] },
            '#withPrincipalsMixin':: d.fn(help='"Optional. Users who are allowed for the operation. Each entry should be a valid v1 IAM principal identifier. The format for these is documented at: https://cloud.google.com/iam/docs/principal-identifiers#v1"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='principals', type=d.T.array)]),
            withPrincipalsMixin(principals): { principals+: if std.isArray(v=principals) then principals else [principals] },
          },
          '#withApprovalsNeeded':: d.fn(help="\"Required. How many users from the above list need to approve. If there aren't enough distinct users in the list, then the workflow indefinitely blocks. Should always be greater than 0. 1 is the only supported value.\"", args=[d.arg(name='approvalsNeeded', type=d.T.integer)]),
          withApprovalsNeeded(approvalsNeeded): { approvalsNeeded: approvalsNeeded },
          '#withApproverEmailRecipients':: d.fn(help='"Optional. Additional email addresses to be notified when a grant is pending approval."', args=[d.arg(name='approverEmailRecipients', type=d.T.array)]),
          withApproverEmailRecipients(approverEmailRecipients): { approverEmailRecipients: if std.isArray(v=approverEmailRecipients) then approverEmailRecipients else [approverEmailRecipients] },
          '#withApproverEmailRecipientsMixin':: d.fn(help='"Optional. Additional email addresses to be notified when a grant is pending approval."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='approverEmailRecipients', type=d.T.array)]),
          withApproverEmailRecipientsMixin(approverEmailRecipients): { approverEmailRecipients+: if std.isArray(v=approverEmailRecipients) then approverEmailRecipients else [approverEmailRecipients] },
          '#withApprovers':: d.fn(help='"Optional. The potential set of approvers in this step. This list must contain at most one entry."', args=[d.arg(name='approvers', type=d.T.array)]),
          withApprovers(approvers): { approvers: if std.isArray(v=approvers) then approvers else [approvers] },
          '#withApproversMixin':: d.fn(help='"Optional. The potential set of approvers in this step. This list must contain at most one entry."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='approvers', type=d.T.array)]),
          withApproversMixin(approvers): { approvers+: if std.isArray(v=approvers) then approvers else [approvers] },
        },
        '#withRequireApproverJustification':: d.fn(help='"Optional. Whether the approvers need to provide a justification for their actions."', args=[d.arg(name='requireApproverJustification', type=d.T.boolean)]),
        withRequireApproverJustification(requireApproverJustification): { spec+: { approvalWorkflow+: { manualApprovals+: { requireApproverJustification: requireApproverJustification } } } },
        '#withSteps':: d.fn(help='"Optional. List of approval steps in this workflow. These steps are followed in the specified order sequentially. Only 1 step is supported."', args=[d.arg(name='steps', type=d.T.array)]),
        withSteps(steps): { spec+: { approvalWorkflow+: { manualApprovals+: { steps: if std.isArray(v=steps) then steps else [steps] } } } },
        '#withStepsMixin':: d.fn(help='"Optional. List of approval steps in this workflow. These steps are followed in the specified order sequentially. Only 1 step is supported."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='steps', type=d.T.array)]),
        withStepsMixin(steps): { spec+: { approvalWorkflow+: { manualApprovals+: { steps+: if std.isArray(v=steps) then steps else [steps] } } } },
      },
    },
    '#eligibleUsers':: d.obj(help='"Who can create grants using this entitlement. This list should contain at most one entry."'),
    eligibleUsers: {
      '#withPrincipals':: d.fn(help='"Optional. Users who are allowed for the operation. Each entry should be a valid v1 IAM principal identifier. The format for these is documented at: https://cloud.google.com/iam/docs/principal-identifiers#v1"', args=[d.arg(name='principals', type=d.T.array)]),
      withPrincipals(principals): { principals: if std.isArray(v=principals) then principals else [principals] },
      '#withPrincipalsMixin':: d.fn(help='"Optional. Users who are allowed for the operation. Each entry should be a valid v1 IAM principal identifier. The format for these is documented at: https://cloud.google.com/iam/docs/principal-identifiers#v1"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='principals', type=d.T.array)]),
      withPrincipalsMixin(principals): { principals+: if std.isArray(v=principals) then principals else [principals] },
    },
    '#folderRef':: d.obj(help="\"Immutable. The Folder that this resource belongs to. One and only one of 'projectRef', 'folderRef', or 'organizationRef' must be set.\""),
    folderRef: {
      '#withExternal':: d.fn(help="\"The 'name' field of a folder, when not managed by Config Connector. This field must be set when 'name' field is not set.\"", args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { folderRef+: { external: external } } },
      '#withName':: d.fn(help="\"The 'name' field of a 'Folder' resource. This field must be set when 'external' field is not set.\"", args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { folderRef+: { name: name } } },
      '#withNamespace':: d.fn(help="\"The 'namespace' field of a 'Folder' resource. If unset, the namespace is defaulted to the namespace of the referencer resource.\"", args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { folderRef+: { namespace: namespace } } },
    },
    '#organizationRef':: d.obj(help="\"Immutable. The Organization that this resource belongs to. One and only one of 'projectRef', 'folderRef', or 'organizationRef' must be set.\""),
    organizationRef: {
      '#withExternal':: d.fn(help="\"The 'name' field of an organization, when not managed by Config Connector.\"", args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { organizationRef+: { external: external } } },
    },
    '#privilegedAccess':: d.obj(help='"The access granted to a requester on successful approval."'),
    privilegedAccess: {
      '#gcpIAMAccess':: d.obj(help='"Access to a Google Cloud resource through IAM."'),
      gcpIAMAccess: {
        '#roleBindings':: d.obj(help='"Required. Role bindings that are created on successful grant."'),
        roleBindings: {
          '#withConditionExpression':: d.fn(help='"Optional. The expression field of the IAM condition to be associated\\nwith the role. If specified, a user with an active grant for this\\nentitlement is able to access the resource only if this condition\\nevaluates to true for their request.\\n\\nThis field uses the same CEL format as IAM and supports all attributes\\nthat IAM supports, except tags. More details can be found at\\nhttps://cloud.google.com/iam/docs/conditions-overview#attributes."', args=[d.arg(name='conditionExpression', type=d.T.string)]),
          withConditionExpression(conditionExpression): { conditionExpression: conditionExpression },
          '#withRole':: d.fn(help='"Required. IAM role to be granted. More details can be found at https://cloud.google.com/iam/docs/roles-overview."', args=[d.arg(name='role', type=d.T.string)]),
          withRole(role): { role: role },
        },
        '#withRoleBindings':: d.fn(help='"Required. Role bindings that are created on successful grant."', args=[d.arg(name='roleBindings', type=d.T.array)]),
        withRoleBindings(roleBindings): { spec+: { privilegedAccess+: { gcpIAMAccess+: { roleBindings: if std.isArray(v=roleBindings) then roleBindings else [roleBindings] } } } },
        '#withRoleBindingsMixin':: d.fn(help='"Required. Role bindings that are created on successful grant."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='roleBindings', type=d.T.array)]),
        withRoleBindingsMixin(roleBindings): { spec+: { privilegedAccess+: { gcpIAMAccess+: { roleBindings+: if std.isArray(v=roleBindings) then roleBindings else [roleBindings] } } } },
      },
    },
    '#projectRef':: d.obj(help="\"Immutable. The Project that this resource belongs to. One and only one of 'projectRef', 'folderRef', or 'organizationRef' must be set.\""),
    projectRef: {
      '#withExternal':: d.fn(help='"The `projectID` field of a project, when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withKind':: d.fn(help='"The kind of the Project resource; optional but must be `Project` if provided."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { projectRef+: { kind: kind } } },
      '#withName':: d.fn(help='"The `name` field of a `Project` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `Project` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#requesterJustificationConfig':: d.obj(help='"Required. The manner in which the requester should provide a justification for requesting access."'),
    requesterJustificationConfig: {
      '#withNotMandatory':: d.fn(help="\"NotMandatory justification type means the justification isn't required and can be provided in any of the supported formats. The user must explicitly opt out using this field if a justification from the requester isn't mandatory. The only accepted value is `{}` (empty struct). Either 'notMandatory' or 'unstructured' field must be set.\"", args=[d.arg(name='notMandatory', type=d.T.object)]),
      withNotMandatory(notMandatory): { spec+: { requesterJustificationConfig+: { notMandatory: notMandatory } } },
      '#withNotMandatoryMixin':: d.fn(help="\"NotMandatory justification type means the justification isn't required and can be provided in any of the supported formats. The user must explicitly opt out using this field if a justification from the requester isn't mandatory. The only accepted value is `{}` (empty struct). Either 'notMandatory' or 'unstructured' field must be set.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='notMandatory', type=d.T.object)]),
      withNotMandatoryMixin(notMandatory): { spec+: { requesterJustificationConfig+: { notMandatory+: notMandatory } } },
      '#withUnstructured':: d.fn(help="\"Unstructured justification type means the justification is in the format of a string. If this is set, the server allows the requester to provide a justification but doesn't validate it. The only accepted value is `{}` (empty struct). Either 'notMandatory' or 'unstructured' field must be set.\"", args=[d.arg(name='unstructured', type=d.T.object)]),
      withUnstructured(unstructured): { spec+: { requesterJustificationConfig+: { unstructured: unstructured } } },
      '#withUnstructuredMixin':: d.fn(help="\"Unstructured justification type means the justification is in the format of a string. If this is set, the server allows the requester to provide a justification but doesn't validate it. The only accepted value is `{}` (empty struct). Either 'notMandatory' or 'unstructured' field must be set.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='unstructured', type=d.T.object)]),
      withUnstructuredMixin(unstructured): { spec+: { requesterJustificationConfig+: { unstructured+: unstructured } } },
    },
    '#withEligibleUsers':: d.fn(help='"Who can create grants using this entitlement. This list should contain at most one entry."', args=[d.arg(name='eligibleUsers', type=d.T.array)]),
    withEligibleUsers(eligibleUsers): { spec+: { eligibleUsers: if std.isArray(v=eligibleUsers) then eligibleUsers else [eligibleUsers] } },
    '#withEligibleUsersMixin':: d.fn(help='"Who can create grants using this entitlement. This list should contain at most one entry."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='eligibleUsers', type=d.T.array)]),
    withEligibleUsersMixin(eligibleUsers): { spec+: { eligibleUsers+: if std.isArray(v=eligibleUsers) then eligibleUsers else [eligibleUsers] } },
    '#withLocation':: d.fn(help='"Immutable. Location of the resource."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withMaxRequestDuration':: d.fn(help='"Required. The maximum amount of time that access is granted for a request. A requester can ask for a duration less than this, but never more."', args=[d.arg(name='maxRequestDuration', type=d.T.string)]),
    withMaxRequestDuration(maxRequestDuration): { spec+: { maxRequestDuration: maxRequestDuration } },
    '#withResourceID':: d.fn(help="\"Immutable. The PrivilegedAccessManagerEntitlement name. If not given, the 'metadata.name' will be used.\"", args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
