{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='redisCluster', url='', help='"RedisCluster is the Schema for the RedisCluster API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of RedisCluster', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'redis.cnrm.cloud.google.com/v1beta1',
    kind: 'RedisCluster',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"RedisClusterSpec defines the desired state of RedisCluster"'),
  spec: {
    '#persistenceConfig':: d.obj(help='"Optional. Persistence config (RDB, AOF) for the cluster."'),
    persistenceConfig: {
      '#aofConfig':: d.obj(help='"Optional. AOF configuration. This field will be ignored if mode is not AOF."'),
      aofConfig: {
        '#withAppendFsync':: d.fn(help='"Optional. fsync configuration."', args=[d.arg(name='appendFsync', type=d.T.string)]),
        withAppendFsync(appendFsync): { spec+: { persistenceConfig+: { aofConfig+: { appendFsync: appendFsync } } } },
      },
      '#rdbConfig':: d.obj(help='"Optional. RDB configuration. This field will be ignored if mode is not RDB."'),
      rdbConfig: {
        '#withRdbSnapshotPeriod':: d.fn(help='"Optional. Period between RDB snapshots."', args=[d.arg(name='rdbSnapshotPeriod', type=d.T.string)]),
        withRdbSnapshotPeriod(rdbSnapshotPeriod): { spec+: { persistenceConfig+: { rdbConfig+: { rdbSnapshotPeriod: rdbSnapshotPeriod } } } },
        '#withRdbSnapshotStartTime':: d.fn(help='"Optional. The time that the first snapshot was/will be attempted, and to which future snapshots will be aligned. If not provided, the current time will be used."', args=[d.arg(name='rdbSnapshotStartTime', type=d.T.string)]),
        withRdbSnapshotStartTime(rdbSnapshotStartTime): { spec+: { persistenceConfig+: { rdbConfig+: { rdbSnapshotStartTime: rdbSnapshotStartTime } } } },
      },
      '#withMode':: d.fn(help='"Optional. The mode of persistence."', args=[d.arg(name='mode', type=d.T.string)]),
      withMode(mode): { spec+: { persistenceConfig+: { mode: mode } } },
    },
    '#projectRef':: d.obj(help='"Immutable. The Project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"The `projectID` field of a project, when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withKind':: d.fn(help='"The kind of the Project resource; optional but must be `Project` if provided."', args=[d.arg(name='kind', type=d.T.string)]),
      withKind(kind): { spec+: { projectRef+: { kind: kind } } },
      '#withName':: d.fn(help='"The `name` field of a `Project` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `Project` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#pscConfigs':: d.obj(help='"Required. Each PscConfig configures the consumer network where IPs will be designated to the cluster for client access through Private Service Connect Automation. Currently, only one PscConfig is supported."'),
    pscConfigs: {
      '#networkRef':: d.obj(help='"Required. The network where the IP address of the discovery endpoint will be reserved, in the form of projects/{network_project}/global/networks/{network_id}."'),
      networkRef: {
        '#withExternal':: d.fn(help='"A reference to an externally managed Compute Network resource. Should be in the format `projects/<projectID>/global/networks/<network>`."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { networkRef+: { external: external } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeNetwork` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { networkRef+: { name: name } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeNetwork` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { networkRef+: { namespace: namespace } },
      },
    },
    '#withAuthorizationMode':: d.fn(help='"Optional. The authorization mode of the Redis cluster. If not provided, auth feature is disabled for the cluster."', args=[d.arg(name='authorizationMode', type=d.T.string)]),
    withAuthorizationMode(authorizationMode): { spec+: { authorizationMode: authorizationMode } },
    '#withDeletionProtectionEnabled':: d.fn(help='"Optional. The delete operation will fail when the value is set to true."', args=[d.arg(name='deletionProtectionEnabled', type=d.T.boolean)]),
    withDeletionProtectionEnabled(deletionProtectionEnabled): { spec+: { deletionProtectionEnabled: deletionProtectionEnabled } },
    '#withLocation':: d.fn(help='"Immutable. Location of the resource."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withNodeType':: d.fn(help='"Optional. The type of a redis node in the cluster. NodeType determines the underlying machine-type of a redis node."', args=[d.arg(name='nodeType', type=d.T.string)]),
    withNodeType(nodeType): { spec+: { nodeType: nodeType } },
    '#withPscConfigs':: d.fn(help='"Required. Each PscConfig configures the consumer network where IPs will be designated to the cluster for client access through Private Service Connect Automation. Currently, only one PscConfig is supported."', args=[d.arg(name='pscConfigs', type=d.T.array)]),
    withPscConfigs(pscConfigs): { spec+: { pscConfigs: if std.isArray(v=pscConfigs) then pscConfigs else [pscConfigs] } },
    '#withPscConfigsMixin':: d.fn(help='"Required. Each PscConfig configures the consumer network where IPs will be designated to the cluster for client access through Private Service Connect Automation. Currently, only one PscConfig is supported."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='pscConfigs', type=d.T.array)]),
    withPscConfigsMixin(pscConfigs): { spec+: { pscConfigs+: if std.isArray(v=pscConfigs) then pscConfigs else [pscConfigs] } },
    '#withRedisConfigs':: d.fn(help='"Optional. Key/Value pairs of customer overrides for mutable Redis Configs"', args=[d.arg(name='redisConfigs', type=d.T.object)]),
    withRedisConfigs(redisConfigs): { spec+: { redisConfigs: redisConfigs } },
    '#withRedisConfigsMixin':: d.fn(help='"Optional. Key/Value pairs of customer overrides for mutable Redis Configs"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='redisConfigs', type=d.T.object)]),
    withRedisConfigsMixin(redisConfigs): { spec+: { redisConfigs+: redisConfigs } },
    '#withReplicaCount':: d.fn(help='"Optional. The number of replica nodes per shard."', args=[d.arg(name='replicaCount', type=d.T.integer)]),
    withReplicaCount(replicaCount): { spec+: { replicaCount: replicaCount } },
    '#withResourceID':: d.fn(help='"The RedisCluster name. If not given, the metadata.name will be used."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withShardCount':: d.fn(help='"Required. Number of shards for the Redis cluster."', args=[d.arg(name='shardCount', type=d.T.integer)]),
    withShardCount(shardCount): { spec+: { shardCount: shardCount } },
    '#withTransitEncryptionMode':: d.fn(help='"Optional. The in-transit encryption for the Redis cluster. If not provided, encryption  is disabled for the cluster."', args=[d.arg(name='transitEncryptionMode', type=d.T.string)]),
    withTransitEncryptionMode(transitEncryptionMode): { spec+: { transitEncryptionMode: transitEncryptionMode } },
    '#zoneDistributionConfig':: d.obj(help='"Optional. This config will be used to determine how the customer wants us to distribute cluster resources within the region."'),
    zoneDistributionConfig: {
      '#withMode':: d.fn(help='"Optional. The mode of zone distribution. Defaults to MULTI_ZONE, when not specified."', args=[d.arg(name='mode', type=d.T.string)]),
      withMode(mode): { spec+: { zoneDistributionConfig+: { mode: mode } } },
      '#withZone':: d.fn(help='"Optional. When SINGLE ZONE distribution is selected, zone field would be used to allocate all resources in that zone. This is not applicable to MULTI_ZONE, and would be ignored for MULTI_ZONE clusters."', args=[d.arg(name='zone', type=d.T.string)]),
      withZone(zone): { spec+: { zoneDistributionConfig+: { zone: zone } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
