{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='certificateManagerCertificate', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of CertificateManagerCertificate', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'certificatemanager.cnrm.cloud.google.com/v1beta1',
    kind: 'CertificateManagerCertificate',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#managed':: d.obj(help="\"Immutable. Configuration and state of a Managed Certificate.\\nCertificate Manager provisions and renews Managed Certificates\\nautomatically, for as long as it's authorized to do so.\""),
    managed: {
      '#authorizationAttemptInfo':: d.obj(help='"Detailed state of the latest authorization attempt for each domain\\nspecified for this Managed Certificate."'),
      authorizationAttemptInfo: {
        '#withDetails':: d.fn(help="\"Human readable explanation for reaching the state. Provided to help\\naddress the configuration issues.\\nNot guaranteed to be stable. For programmatic access use 'failure_reason' field.\"", args=[d.arg(name='details', type=d.T.string)]),
        withDetails(details): { details: details },
        '#withDomain':: d.fn(help='"Domain name of the authorization attempt."', args=[d.arg(name='domain', type=d.T.string)]),
        withDomain(domain): { domain: domain },
        '#withFailureReason':: d.fn(help='"Reason for failure of the authorization attempt for the domain."', args=[d.arg(name='failureReason', type=d.T.string)]),
        withFailureReason(failureReason): { failureReason: failureReason },
        '#withState':: d.fn(help='"State of the domain for managed certificate issuance."', args=[d.arg(name='state', type=d.T.string)]),
        withState(state): { state: state },
      },
      '#dnsAuthorizationsRefs':: d.obj(help=''),
      dnsAuthorizationsRefs: {
        '#withExternal':: d.fn(help='"Allowed value: string of the format `projects/{{project}}/locations/global/dnsAuthorizations/{{value}}`, where {{value}} is the `name` field of a `CertificateManagerDNSAuthorization` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { external: external },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { namespace: namespace },
      },
      '#issuanceConfigRef':: d.obj(help='"Only the `external` field is supported to configure the reference.\\n\\nImmutable. The resource name for a CertificateIssuanceConfig used to configure private PKI certificates in the format projects/*/locations/*/certificateIssuanceConfigs/*.\\nIf this field is not set, the certificates will instead be publicly signed as documented at https://cloud.google.com/load-balancing/docs/ssl-certificates/google-managed-certs#caa.\\nEither issuanceConfig or dnsAuthorizations should be specified, but not both."'),
      issuanceConfigRef: {
        '#withExternal':: d.fn(help='"Allowed value: string of the format `projects/{{project}}/locations/{{location}}/certificateIssuanceConfigs/{{name}}`, where {{value}} is the `name` field of a `CertificateManagerCertificateIssuanceConfig` resource."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { managed+: { issuanceConfigRef+: { external: external } } } },
        '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { managed+: { issuanceConfigRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { managed+: { issuanceConfigRef+: { namespace: namespace } } } },
      },
      '#provisioningIssue':: d.obj(help='"Information about issues with provisioning this Managed Certificate."'),
      provisioningIssue: {
        '#withDetails':: d.fn(help="\"Human readable explanation about the issue. Provided to help address\\nthe configuration issues.\\nNot guaranteed to be stable. For programmatic access use 'reason' field.\"", args=[d.arg(name='details', type=d.T.string)]),
        withDetails(details): { details: details },
        '#withReason':: d.fn(help='"Reason for provisioning failures."', args=[d.arg(name='reason', type=d.T.string)]),
        withReason(reason): { reason: reason },
      },
      '#withAuthorizationAttemptInfo':: d.fn(help='"Detailed state of the latest authorization attempt for each domain\\nspecified for this Managed Certificate."', args=[d.arg(name='authorizationAttemptInfo', type=d.T.array)]),
      withAuthorizationAttemptInfo(authorizationAttemptInfo): { spec+: { managed+: { authorizationAttemptInfo: if std.isArray(v=authorizationAttemptInfo) then authorizationAttemptInfo else [authorizationAttemptInfo] } } },
      '#withAuthorizationAttemptInfoMixin':: d.fn(help='"Detailed state of the latest authorization attempt for each domain\\nspecified for this Managed Certificate."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='authorizationAttemptInfo', type=d.T.array)]),
      withAuthorizationAttemptInfoMixin(authorizationAttemptInfo): { spec+: { managed+: { authorizationAttemptInfo+: if std.isArray(v=authorizationAttemptInfo) then authorizationAttemptInfo else [authorizationAttemptInfo] } } },
      '#withDnsAuthorizationsRefs':: d.fn(help='', args=[d.arg(name='dnsAuthorizationsRefs', type=d.T.array)]),
      withDnsAuthorizationsRefs(dnsAuthorizationsRefs): { spec+: { managed+: { dnsAuthorizationsRefs: if std.isArray(v=dnsAuthorizationsRefs) then dnsAuthorizationsRefs else [dnsAuthorizationsRefs] } } },
      '#withDnsAuthorizationsRefsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='dnsAuthorizationsRefs', type=d.T.array)]),
      withDnsAuthorizationsRefsMixin(dnsAuthorizationsRefs): { spec+: { managed+: { dnsAuthorizationsRefs+: if std.isArray(v=dnsAuthorizationsRefs) then dnsAuthorizationsRefs else [dnsAuthorizationsRefs] } } },
      '#withDomains':: d.fn(help='"Immutable. The domains for which a managed SSL certificate will be generated.\\nWildcard domains are only supported with DNS challenge resolution."', args=[d.arg(name='domains', type=d.T.array)]),
      withDomains(domains): { spec+: { managed+: { domains: if std.isArray(v=domains) then domains else [domains] } } },
      '#withDomainsMixin':: d.fn(help='"Immutable. The domains for which a managed SSL certificate will be generated.\\nWildcard domains are only supported with DNS challenge resolution."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='domains', type=d.T.array)]),
      withDomainsMixin(domains): { spec+: { managed+: { domains+: if std.isArray(v=domains) then domains else [domains] } } },
      '#withProvisioningIssue':: d.fn(help='"Information about issues with provisioning this Managed Certificate."', args=[d.arg(name='provisioningIssue', type=d.T.array)]),
      withProvisioningIssue(provisioningIssue): { spec+: { managed+: { provisioningIssue: if std.isArray(v=provisioningIssue) then provisioningIssue else [provisioningIssue] } } },
      '#withProvisioningIssueMixin':: d.fn(help='"Information about issues with provisioning this Managed Certificate."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='provisioningIssue', type=d.T.array)]),
      withProvisioningIssueMixin(provisioningIssue): { spec+: { managed+: { provisioningIssue+: if std.isArray(v=provisioningIssue) then provisioningIssue else [provisioningIssue] } } },
      '#withState':: d.fn(help='"A state of this Managed Certificate."', args=[d.arg(name='state', type=d.T.string)]),
      withState(state): { spec+: { managed+: { state: state } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#selfManaged':: d.obj(help="\"Immutable. Certificate data for a SelfManaged Certificate.\\nSelfManaged Certificates are uploaded by the user. Updating such\\ncertificates before they expire remains the user's responsibility.\""),
    selfManaged: {
      '#certificatePem':: d.obj(help='"DEPRECATED. `certificate_pem` is deprecated. Use `pem_certificate` instead. Immutable. The certificate chain in PEM-encoded form.\\n\\nLeaf certificate comes first, followed by intermediate ones if any."'),
      certificatePem: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { selfManaged+: { certificatePem+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { selfManaged+: { certificatePem+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { selfManaged+: { certificatePem+: { value: value } } } },
      },
      '#pemPrivateKey':: d.obj(help='"Immutable. The private key of the leaf certificate in PEM-encoded form."'),
      pemPrivateKey: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { selfManaged+: { pemPrivateKey+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { selfManaged+: { pemPrivateKey+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { selfManaged+: { pemPrivateKey+: { value: value } } } },
      },
      '#privateKeyPem':: d.obj(help='"DEPRECATED. `private_key_pem` is deprecated. Use `pem_private_key` instead. Immutable. The private key of the leaf certificate in PEM-encoded form."'),
      privateKeyPem: {
        '#valueFrom':: d.obj(help="\"Source for the field's value. Cannot be used if 'value' is specified.\""),
        valueFrom: {
          '#secretKeyRef':: d.obj(help="\"Reference to a value with the given key in the given Secret in the resource's namespace.\""),
          secretKeyRef: {
            '#withKey':: d.fn(help='"Key that identifies the value to be extracted."', args=[d.arg(name='key', type=d.T.string)]),
            withKey(key): { spec+: { selfManaged+: { privateKeyPem+: { valueFrom+: { secretKeyRef+: { key: key } } } } } },
            '#withName':: d.fn(help='"Name of the Secret to extract a value from."', args=[d.arg(name='name', type=d.T.string)]),
            withName(name): { spec+: { selfManaged+: { privateKeyPem+: { valueFrom+: { secretKeyRef+: { name: name } } } } } },
          },
        },
        '#withValue':: d.fn(help="\"Value of the field. Cannot be used if 'valueFrom' is specified.\"", args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { spec+: { selfManaged+: { privateKeyPem+: { value: value } } } },
      },
      '#withPemCertificate':: d.fn(help='"Immutable. The certificate chain in PEM-encoded form.\\n\\nLeaf certificate comes first, followed by intermediate ones if any."', args=[d.arg(name='pemCertificate', type=d.T.string)]),
      withPemCertificate(pemCertificate): { spec+: { selfManaged+: { pemCertificate: pemCertificate } } },
    },
    '#withDescription':: d.fn(help='"A human-readable description of the resource."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withLocation':: d.fn(help='"Immutable. The Certificate Manager location. If not specified, \\"global\\" is used."', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withScope':: d.fn(help='"Immutable. The scope of the certificate.\\n\\nDEFAULT: Certificates with default scope are served from core Google data centers.\\nIf unsure, choose this option.\\n\\nEDGE_CACHE: Certificates with scope EDGE_CACHE are special-purposed certificates,\\nserved from non-core Google data centers.\\n\\nALL_REGIONS: Certificates with ALL_REGIONS scope are served from all GCP regions (You can only use ALL_REGIONS with global certs).\\nsee https://cloud.google.com/compute/docs/regions-zones."', args=[d.arg(name='scope', type=d.T.string)]),
    withScope(scope): { spec+: { scope: scope } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
