{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='bigQueryDatasetAccess', url='', help=''),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of BigQueryDatasetAccess', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'bigquery.cnrm.cloud.google.com/v1alpha1',
    kind: 'BigQueryDatasetAccess',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#dataset':: d.obj(help='"Immutable. Grants all resources of particular types in a particular dataset read access to the current dataset."'),
    dataset: {
      '#dataset':: d.obj(help='"Immutable. The dataset this entry applies to."'),
      dataset: {
        '#withDatasetId':: d.fn(help='"Immutable. The ID of the dataset containing this table."', args=[d.arg(name='datasetId', type=d.T.string)]),
        withDatasetId(datasetId): { spec+: { dataset+: { dataset+: { datasetId: datasetId } } } },
        '#withProjectId':: d.fn(help='"Immutable. The ID of the project containing this table."', args=[d.arg(name='projectId', type=d.T.string)]),
        withProjectId(projectId): { spec+: { dataset+: { dataset+: { projectId: projectId } } } },
      },
      '#withTargetTypes':: d.fn(help='"Immutable. Which resources in the dataset this entry applies to. Currently, only views are supported,\\nbut additional target types may be added in the future. Possible values: VIEWS."', args=[d.arg(name='targetTypes', type=d.T.array)]),
      withTargetTypes(targetTypes): { spec+: { dataset+: { targetTypes: if std.isArray(v=targetTypes) then targetTypes else [targetTypes] } } },
      '#withTargetTypesMixin':: d.fn(help='"Immutable. Which resources in the dataset this entry applies to. Currently, only views are supported,\\nbut additional target types may be added in the future. Possible values: VIEWS."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='targetTypes', type=d.T.array)]),
      withTargetTypesMixin(targetTypes): { spec+: { dataset+: { targetTypes+: if std.isArray(v=targetTypes) then targetTypes else [targetTypes] } } },
    },
    '#projectRef':: d.obj(help='"The project that this resource belongs to."'),
    projectRef: {
      '#withExternal':: d.fn(help='"Allowed value: The `name` field of a `Project` resource."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { projectRef+: { external: external } } },
      '#withName':: d.fn(help='"Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { projectRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"Namespace of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { projectRef+: { namespace: namespace } } },
    },
    '#view':: d.obj(help='"Immutable. A view from a different dataset to grant access to. Queries\\nexecuted against that view will have read access to tables in\\nthis dataset. The role field is not required when this field is\\nset. If that view is updated by any user, access to the view\\nneeds to be granted again via an update operation."'),
    view: {
      '#withDatasetId':: d.fn(help='"Immutable. The ID of the dataset containing this table."', args=[d.arg(name='datasetId', type=d.T.string)]),
      withDatasetId(datasetId): { spec+: { view+: { datasetId: datasetId } } },
      '#withProjectId':: d.fn(help='"Immutable. The ID of the project containing this table."', args=[d.arg(name='projectId', type=d.T.string)]),
      withProjectId(projectId): { spec+: { view+: { projectId: projectId } } },
      '#withTableId':: d.fn(help='"Immutable. The ID of the table. The ID must contain only letters (a-z,\\nA-Z), numbers (0-9), or underscores (_). The maximum length\\nis 1,024 characters."', args=[d.arg(name='tableId', type=d.T.string)]),
      withTableId(tableId): { spec+: { view+: { tableId: tableId } } },
    },
    '#withDatasetId':: d.fn(help='"Immutable. A unique ID for this dataset, without the project name. The ID\\nmust contain only letters (a-z, A-Z), numbers (0-9), or\\nunderscores (_). The maximum length is 1,024 characters."', args=[d.arg(name='datasetId', type=d.T.string)]),
    withDatasetId(datasetId): { spec+: { datasetId: datasetId } },
    '#withDomain':: d.fn(help='"Immutable. A domain to grant access to. Any users signed in with the\\ndomain specified will be granted the specified access."', args=[d.arg(name='domain', type=d.T.string)]),
    withDomain(domain): { spec+: { domain: domain } },
    '#withGroupByEmail':: d.fn(help='"Immutable. An email address of a Google Group to grant access to."', args=[d.arg(name='groupByEmail', type=d.T.string)]),
    withGroupByEmail(groupByEmail): { spec+: { groupByEmail: groupByEmail } },
    '#withIamMember':: d.fn(help="\"Immutable. Some other type of member that appears in the IAM Policy but isn't a user,\\ngroup, domain, or special group. For example: 'allUsers'.\"", args=[d.arg(name='iamMember', type=d.T.string)]),
    withIamMember(iamMember): { spec+: { iamMember: iamMember } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The routine of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withRole':: d.fn(help='"Immutable. Describes the rights granted to the user specified by the other\\nmember of the access object. Basic, predefined, and custom roles are\\nsupported. Predefined roles that have equivalent basic roles are\\nswapped by the API to their basic counterparts, and will show a diff\\npost-create. See\\n[official docs](https://cloud.google.com/bigquery/docs/access-control)."', args=[d.arg(name='role', type=d.T.string)]),
    withRole(role): { spec+: { role: role } },
    '#withSpecialGroup':: d.fn(help="\"Immutable. A special group to grant access to. Possible values include:\\n\\n\\n* 'projectOwners': Owners of the enclosing project.\\n\\n\\n* 'projectReaders': Readers of the enclosing project.\\n\\n\\n* 'projectWriters': Writers of the enclosing project.\\n\\n\\n* 'allAuthenticatedUsers': All authenticated BigQuery users.\"", args=[d.arg(name='specialGroup', type=d.T.string)]),
    withSpecialGroup(specialGroup): { spec+: { specialGroup: specialGroup } },
    '#withUserByEmail':: d.fn(help='"Immutable. An email address of a user to grant access to. For example:\\nfred@example.com."', args=[d.arg(name='userByEmail', type=d.T.string)]),
    withUserByEmail(userByEmail): { spec+: { userByEmail: userByEmail } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
