{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='computeForwardingRule', url='', help='"ComputeForwardingRule is the Schema for the compute API"'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of ComputeForwardingRule', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'compute.cnrm.cloud.google.com/v1beta1',
    kind: 'ComputeForwardingRule',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help=''),
  spec: {
    '#backendServiceRef':: d.obj(help='"A ComputeBackendService to receive the matched traffic. This is used only for internal load balancing."'),
    backendServiceRef: {
      '#withExternal':: d.fn(help='"The ComputeBackendService selflink in the form \\"projects/{{project}}/global/backendServices/{{name}}\\" or \\"projects/{{project}}/regions/{{region}}/backendServices/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { backendServiceRef+: { external: external } } },
      '#withName':: d.fn(help='"The `name` field of a `ComputeBackendService` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { backendServiceRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeBackendService` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { backendServiceRef+: { namespace: namespace } } },
    },
    '#ipAddress':: d.obj(help="\"The IP address that this forwarding rule is serving on behalf of.\\n\\nAddresses are restricted based on the forwarding rule's load\\nbalancing scheme (EXTERNAL or INTERNAL) and scope (global or\\nregional).\\n\\nWhen the load balancing scheme is EXTERNAL, for global forwarding\\nrules, the address must be a global IP, and for regional forwarding\\nrules, the address must live in the same region as the forwarding\\nrule. If this field is empty, an ephemeral IPv4 address from the\\nsame scope (global or regional) will be assigned. A regional\\nforwarding rule supports IPv4 only. A global forwarding rule\\nsupports either IPv4 or IPv6.\\n\\nWhen the load balancing scheme is INTERNAL, this can only be an RFC\\n1918 IP address belonging to the network/subnet configured for the\\nforwarding rule. By default, if this field is empty, an ephemeral\\ninternal IP address will be automatically allocated from the IP\\nrange of the subnet or network configured for this forwarding rule.\""),
    ipAddress: {
      '#addressRef':: d.obj(help=''),
      addressRef: {
        '#withExternal':: d.fn(help='"The ComputeAddress selflink in the form \\"projects/{{project}}/regions/{{region}}/addresses/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { ipAddress+: { addressRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeAddress` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { ipAddress+: { addressRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeAddress` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { ipAddress+: { addressRef+: { namespace: namespace } } } },
      },
      '#withIp':: d.fn(help='', args=[d.arg(name='ip', type=d.T.string)]),
      withIp(ip): { spec+: { ipAddress+: { ip: ip } } },
    },
    '#metadataFilters':: d.obj(help='"Immutable. Opaque filter criteria used by Loadbalancer to restrict routing\\nconfiguration to a limited set xDS compliant clients. In their xDS\\nrequests to Loadbalancer, xDS clients present node metadata. If a\\nmatch takes place, the relevant routing configuration is made available\\nto those proxies.\\n\\nFor each metadataFilter in this list, if its filterMatchCriteria is set\\nto MATCH_ANY, at least one of the filterLabels must match the\\ncorresponding label provided in the metadata. If its filterMatchCriteria\\nis set to MATCH_ALL, then all of its filterLabels must match with\\ncorresponding labels in the provided metadata.\\n\\nmetadataFilters specified here can be overridden by those specified in\\nthe UrlMap that this ForwardingRule references.\\n\\nmetadataFilters only applies to Loadbalancers that have their\\nloadBalancingScheme set to INTERNAL_SELF_MANAGED."'),
    metadataFilters: {
      '#filterLabels':: d.obj(help='"Immutable. The list of label value pairs that must match labels in the\\nprovided metadata based on filterMatchCriteria\\n\\nThis list must not be empty and can have at the most 64 entries."'),
      filterLabels: {
        '#withName':: d.fn(help='"Immutable. Name of the metadata label. The length must be between 1 and 1024 characters, inclusive."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
        '#withValue':: d.fn(help='"Immutable. The value that the label must match. The value has a maximum length of 1024 characters."', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { value: value },
      },
      '#withFilterLabels':: d.fn(help='"Immutable. The list of label value pairs that must match labels in the\\nprovided metadata based on filterMatchCriteria\\n\\nThis list must not be empty and can have at the most 64 entries."', args=[d.arg(name='filterLabels', type=d.T.array)]),
      withFilterLabels(filterLabels): { filterLabels: if std.isArray(v=filterLabels) then filterLabels else [filterLabels] },
      '#withFilterLabelsMixin':: d.fn(help='"Immutable. The list of label value pairs that must match labels in the\\nprovided metadata based on filterMatchCriteria\\n\\nThis list must not be empty and can have at the most 64 entries."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='filterLabels', type=d.T.array)]),
      withFilterLabelsMixin(filterLabels): { filterLabels+: if std.isArray(v=filterLabels) then filterLabels else [filterLabels] },
      '#withFilterMatchCriteria':: d.fn(help='"Immutable. Specifies how individual filterLabel matches within the list of\\nfilterLabels contribute towards the overall metadataFilter match.\\n\\nMATCH_ANY - At least one of the filterLabels must have a matching\\nlabel in the provided metadata.\\nMATCH_ALL - All filterLabels must have matching labels in the\\nprovided metadata. Possible values: [\\"MATCH_ANY\\", \\"MATCH_ALL\\"]."', args=[d.arg(name='filterMatchCriteria', type=d.T.string)]),
      withFilterMatchCriteria(filterMatchCriteria): { filterMatchCriteria: filterMatchCriteria },
    },
    '#networkRef':: d.obj(help='"This field is not used for external load balancing. For internal load balancing, this field identifies the network that the load balanced IP should belong to for this forwarding rule. If this field is not specified, the default network will be used."'),
    networkRef: {
      '#withExternal':: d.fn(help='"A reference to an externally managed Compute Network resource. Should be in the format `projects/<projectID>/global/networks/<network>`."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { networkRef+: { external: external } } },
      '#withName':: d.fn(help='"The `name` field of a `ComputeNetwork` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { networkRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeNetwork` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { networkRef+: { namespace: namespace } } },
    },
    '#serviceDirectoryRegistrations':: d.obj(help='"Immutable. Service Directory resources to register this forwarding rule with.\\n\\nCurrently, only supports a single Service Directory resource."'),
    serviceDirectoryRegistrations: {
      '#withNamespace':: d.fn(help='"Immutable. Service Directory namespace to register the forwarding rule under."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { namespace: namespace },
      '#withService':: d.fn(help='"Immutable. Service Directory service to register the forwarding rule under."', args=[d.arg(name='service', type=d.T.string)]),
      withService(service): { service: service },
    },
    '#subnetworkRef':: d.obj(help='"Immutable. The subnetwork that the load balanced IP should belong to for this\\nforwarding rule. This field is only used for internal load\\nbalancing.\\n\\nIf the network specified is in auto subnet mode, this field is\\noptional. However, if the network is in custom subnet mode, a\\nsubnetwork must be specified."'),
    subnetworkRef: {
      '#withExternal':: d.fn(help='"The ComputeSubnetwork selflink of form \\"projects/{{project}}/regions/{{region}}/subnetworks/{{name}}\\", when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
      withExternal(external): { spec+: { subnetworkRef+: { external: external } } },
      '#withName':: d.fn(help='"The `name` field of a `ComputeSubnetwork` resource."', args=[d.arg(name='name', type=d.T.string)]),
      withName(name): { spec+: { subnetworkRef+: { name: name } } },
      '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeSubnetwork` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
      withNamespace(namespace): { spec+: { subnetworkRef+: { namespace: namespace } } },
    },
    '#target':: d.obj(help='"The target resource to receive the matched traffic. The forwarded traffic must be of a type appropriate to the target object. For INTERNAL_SELF_MANAGED load balancing, only HTTP and HTTPS targets are valid."'),
    target: {
      '#serviceAttachmentRef':: d.obj(help=''),
      serviceAttachmentRef: {
        '#withExternal':: d.fn(help='"The ComputeServiceAttachment selflink in the form \\"projects/{{project}}/regions/{{region}}/serviceAttachments/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { target+: { serviceAttachmentRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeServiceAttachment` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { target+: { serviceAttachmentRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeServiceAttachment` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { target+: { serviceAttachmentRef+: { namespace: namespace } } } },
      },
      '#targetGRPCProxyRef':: d.obj(help=''),
      targetGRPCProxyRef: {
        '#withExternal':: d.fn(help='"The ComputeTargetGrpcProxy selflink in the form \\"projects/{{project}}/global/targetGrpcProxies/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { target+: { targetGRPCProxyRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeTargetGrpcProxy` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { target+: { targetGRPCProxyRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeTargetGrpcProxy` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { target+: { targetGRPCProxyRef+: { namespace: namespace } } } },
      },
      '#targetHTTPProxyRef':: d.obj(help=''),
      targetHTTPProxyRef: {
        '#withExternal':: d.fn(help='"The ComputeTargetHTTPProxy selflink in the form \\"projects/{{project}}/global/targetHttpProxies/{{name}}\\" or \\"projects/{{project}}/regions/{{region}}/targetHttpProxies/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { target+: { targetHTTPProxyRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeTargetHTTPProxy` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { target+: { targetHTTPProxyRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeTargetHTTPProxy` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { target+: { targetHTTPProxyRef+: { namespace: namespace } } } },
      },
      '#targetHTTPSProxyRef':: d.obj(help=''),
      targetHTTPSProxyRef: {
        '#withExternal':: d.fn(help='"The ComputeTargetHTTPSProxy selflink in the form \\"projects/{{project}}/global/targetHttpProxies/{{name}}\\" or \\"projects/{{project}}/regions/{{region}}/targetHttpProxies/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { target+: { targetHTTPSProxyRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeTargetHTTPSProxy` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { target+: { targetHTTPSProxyRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeTargetHTTPSProxy` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { target+: { targetHTTPSProxyRef+: { namespace: namespace } } } },
      },
      '#targetSSLProxyRef':: d.obj(help=''),
      targetSSLProxyRef: {
        '#withExternal':: d.fn(help='"The ComputeTargetSSLProxy selflink in the form \\"projects/{{project}}/global/targetSslProxies/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { target+: { targetSSLProxyRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeTargetSSLProxy` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { target+: { targetSSLProxyRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeTargetSSLProxy` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { target+: { targetSSLProxyRef+: { namespace: namespace } } } },
      },
      '#targetTCPProxyRef':: d.obj(help=''),
      targetTCPProxyRef: {
        '#withExternal':: d.fn(help='"The ComputeTargetTCPProxy selflink in the form \\"projects/{{project}}/global/targetTcpProxies/{{name}}\\" or \\"projects/{{project}}/regions/{{region}}/targetTcpProxies/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { target+: { targetTCPProxyRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeTargetTCPProxy` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { target+: { targetTCPProxyRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeTargetTCPProxy` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { target+: { targetTCPProxyRef+: { namespace: namespace } } } },
      },
      '#targetVPNGatewayRef':: d.obj(help=''),
      targetVPNGatewayRef: {
        '#withExternal':: d.fn(help='"The ComputeTargetVPNGateway selflink in the form \\"projects/{{project}}/regions/{{region}}/targetVpnGateways/{{name}}\\" when not managed by Config Connector."', args=[d.arg(name='external', type=d.T.string)]),
        withExternal(external): { spec+: { target+: { targetVPNGatewayRef+: { external: external } } } },
        '#withName':: d.fn(help='"The `name` field of a `ComputeTargetVPNGateway` resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { target+: { targetVPNGatewayRef+: { name: name } } } },
        '#withNamespace':: d.fn(help='"The `namespace` field of a `ComputeTargetVPNGateway` resource."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { target+: { targetVPNGatewayRef+: { namespace: namespace } } } },
      },
      '#withGoogleAPIsBundle':: d.fn(help='', args=[d.arg(name='googleAPIsBundle', type=d.T.string)]),
      withGoogleAPIsBundle(googleAPIsBundle): { spec+: { target+: { googleAPIsBundle: googleAPIsBundle } } },
    },
    '#withAllPorts':: d.fn(help="\"Immutable. This field can only be used:\\n* If 'IPProtocol' is one of TCP, UDP, or SCTP.\\n* By internal TCP/UDP load balancers, backend service-based network load\\nbalancers, and internal and external protocol forwarding.\\n\\nThis option should be set to TRUE when the Forwarding Rule\\nIPProtocol is set to L3_DEFAULT.\\n\\nSet this field to true to allow packets addressed to any port or packets\\nlacking destination port information (for example, UDP fragments after the\\nfirst fragment) to be forwarded to the backends configured with this\\nforwarding rule.\\n\\nThe 'ports', 'port_range', and\\n'allPorts' fields are mutually exclusive.\"", args=[d.arg(name='allPorts', type=d.T.boolean)]),
    withAllPorts(allPorts): { spec+: { allPorts: allPorts } },
    '#withAllowGlobalAccess':: d.fn(help="\"This field is used along with the 'backend_service' field for\\ninternal load balancing or with the 'target' field for internal\\nTargetInstance.\\n\\nIf the field is set to 'TRUE', clients can access ILB from all\\nregions.\\n\\nOtherwise only allows access from clients in the same region as the\\ninternal load balancer.\"", args=[d.arg(name='allowGlobalAccess', type=d.T.boolean)]),
    withAllowGlobalAccess(allowGlobalAccess): { spec+: { allowGlobalAccess: allowGlobalAccess } },
    '#withAllowPscGlobalAccess':: d.fn(help='"This is used in PSC consumer ForwardingRule to control whether the PSC endpoint can be accessed from another region."', args=[d.arg(name='allowPscGlobalAccess', type=d.T.boolean)]),
    withAllowPscGlobalAccess(allowPscGlobalAccess): { spec+: { allowPscGlobalAccess: allowPscGlobalAccess } },
    '#withDescription':: d.fn(help='"Immutable. An optional description of this resource. Provide this property when you create the resource."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withIpProtocol':: d.fn(help="\"Immutable. The IP protocol to which this rule applies.\\n\\nFor protocol forwarding, valid\\noptions are 'TCP', 'UDP', 'ESP',\\n'AH', 'SCTP', 'ICMP' and\\n'L3_DEFAULT'.\\n\\nThe valid IP protocols are different for different load balancing products\\nas described in [Load balancing\\nfeatures](https://cloud.google.com/load-balancing/docs/features#protocols_from_the_load_balancer_to_the_backends).\\n\\nA Forwarding Rule with protocol L3_DEFAULT can attach with target instance or\\nbackend service with UNSPECIFIED protocol.\\nA forwarding rule with \\\"L3_DEFAULT\\\" IPProtocal cannot be attached to a backend service with TCP or UDP. Possible values: [\\\"TCP\\\", \\\"UDP\\\", \\\"ESP\\\", \\\"AH\\\", \\\"SCTP\\\", \\\"ICMP\\\", \\\"L3_DEFAULT\\\"].\"", args=[d.arg(name='ipProtocol', type=d.T.string)]),
    withIpProtocol(ipProtocol): { spec+: { ipProtocol: ipProtocol } },
    '#withIpVersion':: d.fn(help='"Immutable. The IP address version that will be used by this forwarding rule.\\nValid options are IPV4 and IPV6.\\n\\nIf not set, the IPv4 address will be used by default. Possible values: [\\"IPV4\\", \\"IPV6\\"]."', args=[d.arg(name='ipVersion', type=d.T.string)]),
    withIpVersion(ipVersion): { spec+: { ipVersion: ipVersion } },
    '#withIsMirroringCollector':: d.fn(help="\"Immutable. Indicates whether or not this load balancer can be used as a collector for\\npacket mirroring. To prevent mirroring loops, instances behind this\\nload balancer will not have their traffic mirrored even if a\\n'PacketMirroring' rule applies to them.\\n\\nThis can only be set to true for load balancers that have their\\n'loadBalancingScheme' set to 'INTERNAL'.\"", args=[d.arg(name='isMirroringCollector', type=d.T.boolean)]),
    withIsMirroringCollector(isMirroringCollector): { spec+: { isMirroringCollector: isMirroringCollector } },
    '#withLoadBalancingScheme':: d.fn(help='"Immutable. Specifies the forwarding rule type.\\n\\nMust set to empty for private service connect forwarding rule. For more information about forwarding rules, refer to\\n[Forwarding rule concepts](https://cloud.google.com/load-balancing/docs/forwarding-rule-concepts). Default value: \\"EXTERNAL\\" Possible values: [\\"EXTERNAL\\", \\"EXTERNAL_MANAGED\\", \\"INTERNAL\\", \\"INTERNAL_MANAGED\\", \\"\\"]."', args=[d.arg(name='loadBalancingScheme', type=d.T.string)]),
    withLoadBalancingScheme(loadBalancingScheme): { spec+: { loadBalancingScheme: loadBalancingScheme } },
    '#withLocation':: d.fn(help='"Location represents the geographical location of the ComputeForwardingRule. Specify a region name or \\"global\\" for global resources. Reference: GCP definition of regions/zones (https://cloud.google.com/compute/docs/regions-zones/)"', args=[d.arg(name='location', type=d.T.string)]),
    withLocation(location): { spec+: { location: location } },
    '#withMetadataFilters':: d.fn(help='"Immutable. Opaque filter criteria used by Loadbalancer to restrict routing\\nconfiguration to a limited set xDS compliant clients. In their xDS\\nrequests to Loadbalancer, xDS clients present node metadata. If a\\nmatch takes place, the relevant routing configuration is made available\\nto those proxies.\\n\\nFor each metadataFilter in this list, if its filterMatchCriteria is set\\nto MATCH_ANY, at least one of the filterLabels must match the\\ncorresponding label provided in the metadata. If its filterMatchCriteria\\nis set to MATCH_ALL, then all of its filterLabels must match with\\ncorresponding labels in the provided metadata.\\n\\nmetadataFilters specified here can be overridden by those specified in\\nthe UrlMap that this ForwardingRule references.\\n\\nmetadataFilters only applies to Loadbalancers that have their\\nloadBalancingScheme set to INTERNAL_SELF_MANAGED."', args=[d.arg(name='metadataFilters', type=d.T.array)]),
    withMetadataFilters(metadataFilters): { spec+: { metadataFilters: if std.isArray(v=metadataFilters) then metadataFilters else [metadataFilters] } },
    '#withMetadataFiltersMixin':: d.fn(help='"Immutable. Opaque filter criteria used by Loadbalancer to restrict routing\\nconfiguration to a limited set xDS compliant clients. In their xDS\\nrequests to Loadbalancer, xDS clients present node metadata. If a\\nmatch takes place, the relevant routing configuration is made available\\nto those proxies.\\n\\nFor each metadataFilter in this list, if its filterMatchCriteria is set\\nto MATCH_ANY, at least one of the filterLabels must match the\\ncorresponding label provided in the metadata. If its filterMatchCriteria\\nis set to MATCH_ALL, then all of its filterLabels must match with\\ncorresponding labels in the provided metadata.\\n\\nmetadataFilters specified here can be overridden by those specified in\\nthe UrlMap that this ForwardingRule references.\\n\\nmetadataFilters only applies to Loadbalancers that have their\\nloadBalancingScheme set to INTERNAL_SELF_MANAGED."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadataFilters', type=d.T.array)]),
    withMetadataFiltersMixin(metadataFilters): { spec+: { metadataFilters+: if std.isArray(v=metadataFilters) then metadataFilters else [metadataFilters] } },
    '#withNetworkTier':: d.fn(help="\"Immutable. This signifies the networking tier used for configuring\\nthis load balancer and can only take the following values:\\n'PREMIUM', 'STANDARD'.\\n\\nFor regional ForwardingRule, the valid values are 'PREMIUM' and\\n'STANDARD'. For GlobalForwardingRule, the valid value is\\n'PREMIUM'.\\n\\nIf this field is not specified, it is assumed to be 'PREMIUM'.\\nIf 'IPAddress' is specified, this value must be equal to the\\nnetworkTier of the Address. Possible values: [\\\"PREMIUM\\\", \\\"STANDARD\\\"].\"", args=[d.arg(name='networkTier', type=d.T.string)]),
    withNetworkTier(networkTier): { spec+: { networkTier: networkTier } },
    '#withNoAutomateDnsZone':: d.fn(help='"Immutable. This is used in PSC consumer ForwardingRule to control whether it should try to auto-generate a DNS zone or not. Non-PSC forwarding rules do not use this field."', args=[d.arg(name='noAutomateDnsZone', type=d.T.boolean)]),
    withNoAutomateDnsZone(noAutomateDnsZone): { spec+: { noAutomateDnsZone: noAutomateDnsZone } },
    '#withPortRange':: d.fn(help="\"Immutable. This field can only be used:\\n\\n* If 'IPProtocol' is one of TCP, UDP, or SCTP.\\n* By backend service-based network load balancers, target pool-based\\nnetwork load balancers, internal proxy load balancers, external proxy load\\nbalancers, Traffic Director, external protocol forwarding, and Classic VPN.\\nSome products have restrictions on what ports can be used. See\\n[port specifications](https://cloud.google.com/load-balancing/docs/forwarding-rule-concepts#port_specifications)\\nfor details.\\n\\nOnly packets addressed to ports in the specified range will be forwarded to\\nthe backends configured with this forwarding rule.\\n\\nThe 'ports' and 'port_range' fields are mutually exclusive.\\n\\nFor external forwarding rules, two or more forwarding rules cannot use the\\nsame '[IPAddress, IPProtocol]' pair, and cannot have\\noverlapping 'portRange's.\\n\\nFor internal forwarding rules within the same VPC network, two or more\\nforwarding rules cannot use the same '[IPAddress, IPProtocol]'\\npair, and cannot have overlapping 'portRange's.\"", args=[d.arg(name='portRange', type=d.T.string)]),
    withPortRange(portRange): { spec+: { portRange: portRange } },
    '#withPorts':: d.fn(help="\"Immutable. This field can only be used:\\n\\n* If 'IPProtocol' is one of TCP, UDP, or SCTP.\\n* By internal TCP/UDP load balancers, backend service-based network load\\nbalancers, internal protocol forwarding and when protocol is not L3_DEFAULT.\\n\\nYou can specify a list of up to five ports by number, separated by commas.\\nThe ports can be contiguous or discontiguous. Only packets addressed to\\nthese ports will be forwarded to the backends configured with this\\nforwarding rule.\\n\\nFor external forwarding rules, two or more forwarding rules cannot use the\\nsame '[IPAddress, IPProtocol]' pair, and cannot share any values\\ndefined in 'ports'.\\n\\nFor internal forwarding rules within the same VPC network, two or more\\nforwarding rules cannot use the same '[IPAddress, IPProtocol]'\\npair, and cannot share any values defined in 'ports'.\\n\\nThe 'ports' and 'port_range' fields are mutually exclusive.\"", args=[d.arg(name='ports', type=d.T.array)]),
    withPorts(ports): { spec+: { ports: if std.isArray(v=ports) then ports else [ports] } },
    '#withPortsMixin':: d.fn(help="\"Immutable. This field can only be used:\\n\\n* If 'IPProtocol' is one of TCP, UDP, or SCTP.\\n* By internal TCP/UDP load balancers, backend service-based network load\\nbalancers, internal protocol forwarding and when protocol is not L3_DEFAULT.\\n\\nYou can specify a list of up to five ports by number, separated by commas.\\nThe ports can be contiguous or discontiguous. Only packets addressed to\\nthese ports will be forwarded to the backends configured with this\\nforwarding rule.\\n\\nFor external forwarding rules, two or more forwarding rules cannot use the\\nsame '[IPAddress, IPProtocol]' pair, and cannot share any values\\ndefined in 'ports'.\\n\\nFor internal forwarding rules within the same VPC network, two or more\\nforwarding rules cannot use the same '[IPAddress, IPProtocol]'\\npair, and cannot share any values defined in 'ports'.\\n\\nThe 'ports' and 'port_range' fields are mutually exclusive.\"\n\n**Note:** This function appends passed data to existing values", args=[d.arg(name='ports', type=d.T.array)]),
    withPortsMixin(ports): { spec+: { ports+: if std.isArray(v=ports) then ports else [ports] } },
    '#withResourceID':: d.fn(help='"Immutable. Optional. The name of the resource. Used for creation and acquisition. When unset, the value of `metadata.name` is used as the default."', args=[d.arg(name='resourceID', type=d.T.string)]),
    withResourceID(resourceID): { spec+: { resourceID: resourceID } },
    '#withServiceDirectoryRegistrations':: d.fn(help='"Immutable. Service Directory resources to register this forwarding rule with.\\n\\nCurrently, only supports a single Service Directory resource."', args=[d.arg(name='serviceDirectoryRegistrations', type=d.T.array)]),
    withServiceDirectoryRegistrations(serviceDirectoryRegistrations): { spec+: { serviceDirectoryRegistrations: if std.isArray(v=serviceDirectoryRegistrations) then serviceDirectoryRegistrations else [serviceDirectoryRegistrations] } },
    '#withServiceDirectoryRegistrationsMixin':: d.fn(help='"Immutable. Service Directory resources to register this forwarding rule with.\\n\\nCurrently, only supports a single Service Directory resource."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='serviceDirectoryRegistrations', type=d.T.array)]),
    withServiceDirectoryRegistrationsMixin(serviceDirectoryRegistrations): { spec+: { serviceDirectoryRegistrations+: if std.isArray(v=serviceDirectoryRegistrations) then serviceDirectoryRegistrations else [serviceDirectoryRegistrations] } },
    '#withServiceLabel':: d.fn(help="\"Immutable. An optional prefix to the service name for this Forwarding Rule.\\nIf specified, will be the first label of the fully qualified service\\nname.\\n\\nThe label must be 1-63 characters long, and comply with RFC1035.\\nSpecifically, the label must be 1-63 characters long and match the\\nregular expression '[a-z]([-a-z0-9]*[a-z0-9])?' which means the first\\ncharacter must be a lowercase letter, and all following characters\\nmust be a dash, lowercase letter, or digit, except the last\\ncharacter, which cannot be a dash.\\n\\nThis field is only used for INTERNAL load balancing.\"", args=[d.arg(name='serviceLabel', type=d.T.string)]),
    withServiceLabel(serviceLabel): { spec+: { serviceLabel: serviceLabel } },
    '#withSourceIpRanges':: d.fn(help='"Immutable. If not empty, this Forwarding Rule will only forward the traffic when the source IP address matches one of the IP addresses or CIDR ranges set here. Note that a Forwarding Rule can only have up to 64 source IP ranges, and this field can only be used with a regional Forwarding Rule whose scheme is EXTERNAL. Each sourceIpRange entry should be either an IP address (for example, 1.2.3.4) or a CIDR range (for example, 1.2.3.0/24)."', args=[d.arg(name='sourceIpRanges', type=d.T.array)]),
    withSourceIpRanges(sourceIpRanges): { spec+: { sourceIpRanges: if std.isArray(v=sourceIpRanges) then sourceIpRanges else [sourceIpRanges] } },
    '#withSourceIpRangesMixin':: d.fn(help='"Immutable. If not empty, this Forwarding Rule will only forward the traffic when the source IP address matches one of the IP addresses or CIDR ranges set here. Note that a Forwarding Rule can only have up to 64 source IP ranges, and this field can only be used with a regional Forwarding Rule whose scheme is EXTERNAL. Each sourceIpRange entry should be either an IP address (for example, 1.2.3.4) or a CIDR range (for example, 1.2.3.0/24)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='sourceIpRanges', type=d.T.array)]),
    withSourceIpRangesMixin(sourceIpRanges): { spec+: { sourceIpRanges+: if std.isArray(v=sourceIpRanges) then sourceIpRanges else [sourceIpRanges] } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
